cozy/cozy-client

packages/cozy-pouch-link/src/CozyPouchLink.js
=> Improvements to CozyPouchPlugin

packages/cozy-client/src/CozyClient.js
Hooks provide the ability for a user of the library to
have a callback attached when something happens to a
document.
=> chore: ability to add hook

packages/cozy-client/src/CozyClient.js, packages/cozy-client/src/ObservableQuery.js, packages/cozy-client/src/Query.jsx, packages/cozy-client/src/associations/Association.js, packages/cozy-client/src/associations/HasManyAssociation.js, packages/cozy-client/src/associations/HasManyUNSAFEAssociation.js, packages/cozy-client/src/authentication/mobile.js, packages/cozy-client/src/withMutations.jsx, packages/cozy-pouch-link/src/CozyPouchLink.js, packages/cozy-stack-client/src/CozyStackClient.js, packages/cozy-stack-client/src/OAuthClient.js
This PR adds a (temporary) special has-many association for Banks plus minor fine-tunings around OAuth.
@ptbrowne I also added an `autoHydrate` option, so that we can disable it in banks for the time being.
=> Improvements for banks

.travis.yml, package.json, packages/cozy-client/package.json, packages/cozy-client/src/__tests__/CozyClient.spec.js, packages/cozy-client/src/__tests__/ObservableQuery.spec.js, packages/cozy-client/src/__tests__/withMutation.spec.jsx, packages/cozy-pouch-link/__tests__/CozyPouchLink.spec.js, packages/cozy-pouch-link/__tests__/mango.spec.js, packages/cozy-pouch-link/package.json, packages/cozy-pouch-link/src/CozyPouchLink.js, packages/cozy-stack-client/package.json, packages/cozy-stack-client/src/CozyStackClient.js, packages/cozy-stack-client/src/__tests__/OAuthClient.spec.js, packages/cozy-stack-client/src/__tests__/__snapshots__/OAuthClient.spec.js.snap, packages/cozy-stack-client/src/__tests__/setup.js, webpack.config.js, yarn.lock
There are a few failing tests, but I don't know if there's a regression behind them or not. I'll link to the travis with more details log once it's created.
=> Let's make things green 🌴

packages/cozy-pouch-link/package.json, yarn.lock
=> chore: Upgrade pouchdb to latest version

packages/cozy-client/src/CozyClient.js, packages/cozy-stack-client/src/AppCollection.js, packages/cozy-stack-client/src/CozyStackClient.js, packages/cozy-stack-client/src/DocumentCollection.js, packages/cozy-stack-client/src/FileCollection.js, packages/cozy-stack-client/src/OAuthClient.js, packages/cozy-stack-client/src/PermissionCollection.js, packages/cozy-stack-client/src/SharingCollection.js, packages/cozy-stack-client/src/__tests__/CozyStackClient.spec.js, packages/cozy-stack-client/src/__tests__/DocumentCollection.spec.js, packages/cozy-stack-client/src/__tests__/FileCollection.spec.js, packages/cozy-stack-client/src/__tests__/OAuthClient.spec.js, packages/cozy-stack-client/src/__tests__/SharingCollection.spec.js, packages/cozy-stack-client/src/__tests__/__snapshots__/CozyStackClient.spec.js.snap
Add a very low level fetch enhanced with the Cozy token and the Cozy URL and use it in the fetchJSON method.
=> Add a classic fetch in CozyStackClient

package.json, yarn.lock
Also, upgrade to latest version.
=> Fix lerna watch

packages/cozy-client/src/CozyClient.js, packages/cozy-client/src/ObservableQuery.js, packages/cozy-client/src/Query.jsx, packages/cozy-client/src/__tests__/associations.spec.js, packages/cozy-client/src/__tests__/connect.spec.jsx, packages/cozy-client/src/__tests__/store.spec.js, packages/cozy-client/src/connect.jsx, packages/cozy-client/src/store/index.js, packages/cozy-client/src/store/queries.js
- added test
- renamed methods
=> test: receiving update result should update all containing queries

package.json, yarn.lock
`commitlint-config-cozy` add Cozy commit convention on each commit
you can find more documentation on [guidelines][guidlines] or on
[commitlint-config-cozy][commitlint-config-cozy] repository.
[guidlines]: https://github.com/cozy/cozy-guidelines#commit-messages
[commitlint-config-cozy]: https://github.com/cozy/cozy-libs/tree/master/packages/commitlint-config
=> chore: Add cozy convention on commitlint 📏

docs/api.md, docs/guide.md, docs/toc.yml, package.json, packages/cozy-client/src/CozyClient.js, packages/cozy-client/src/hoc.js, packages/cozy-pouch-link/src/mango.js, packages/cozy-stack-client/src/AppCollection.js, packages/cozy-stack-client/src/CozyStackClient.js, packages/cozy-stack-client/src/DocumentCollection.js, packages/cozy-stack-client/src/FileCollection.js, packages/cozy-stack-client/src/OAuthClient.js, packages/cozy-stack-client/src/utils.js, yarn.lock
There's now a `yarn doc` command that will generate an API documentation based on jsdoc comments. i have updated the existing jsdoc where needed so that the generated doc makes sense.
I've also moved the existing README to the docs folder and added a `toc.yml` file so we can publish this doc on docs.cozy.io
=> Generate docs with jsdoc2md

package.json, packages/cozy-client/src/Query.spec.jsx, yarn.lock
=> chore: Add test to prevent double query bug

packages/cozy-client/src/CozyClient.js, packages/cozy-client/src/associations/Association.js, packages/cozy-client/src/associations/HasManyAssociation.js, packages/cozy-client/src/associations/index.js
There was some flaws in the associations. I worked with @ptbrowne to improve it.
=> Improve associations

packages/cozy-client/src/Query.jsx
ESLint was complaining about these variables not being used.
=> chore(Query): Remove unused vars

docs/dev.md, package.json, packages/cozy-client/src/CozyClient.js, packages/cozy-client/src/Query.jsx, packages/cozy-client/src/Query.spec.jsx, packages/cozy-client/src/__tests__/connect.spec.jsx
JSX were not linted before. Now they are.
=> chore: Lint jsx files

packages/cozy-stack-client/src/DocumentCollection.js, packages/cozy-stack-client/src/FileCollection.js, packages/cozy-stack-client/src/__tests__/DocumentCollection.spec.js, packages/cozy-stack-client/src/__tests__/FileCollection.spec.js, packages/cozy-stack-client/src/querystring.js
* remove FETCH_LIMIT, use the server limit by default
=> feat: remove default limit

packages/cozy-client/src/CozyClient.js, packages/cozy-client/src/ObservableQuery.js, packages/cozy-client/src/Query.jsx, packages/cozy-client/src/Query.spec.jsx, packages/cozy-client/src/__tests__/mocks.js, packages/cozy-client/src/hoc.spec.js
- Removed unsued queryId
- Use same method to mock client
- Add docstrings
=> Refactors and docstrings

packages/cozy-client/examples/relationships.js, packages/cozy-client/src/CozyClient.js
Runnable examples can serve as end to end test and also can be learned from.
=> docs: add runnable example for relationships

.gitignore, packages/cozy-client/src/CozyClient.js, packages/cozy-client/src/CozyClient.spec.js, packages/cozy-client/src/__tests__/ObservableQuery.spec.js, packages/cozy-client/src/__tests__/StackLink.spec.js, packages/cozy-client/src/__tests__/associations.spec.js, packages/cozy-client/src/__tests__/connect.spec.jsx, packages/cozy-client/src/__tests__/fixtures.js, packages/cozy-client/src/__tests__/utils.js, packages/cozy-client/src/__tests__/withMutation.spec.jsx, packages/cozy-pouch-link/src/CozyPouchLink.spec.js, packages/cozy-pouch-link/src/__tests__/fixtures.js, packages/cozy-pouch-link/src/jsonapi.js, packages/cozy-pouch-link/src/jsonapi.spec.js, packages/cozy-pouch-link/src/mango.spec.js
- allDocs sends back rows with doc inside
Some refactors along the way
=> fix: jsonapi needs to extract the doc from the rows

packages/cozy-pouch-link/src/CozyPouchLink.js
PouchLink exposes methods to start/stop replication.
=> feat: Public start/stop

packages/cozy-pouch-link/src/CozyPouchLink.js, packages/cozy-pouch-link/src/CozyPouchLink.spec.js, packages/cozy-pouch-link/src/jsonapi.js
All documents where returned when we needed only 1 document.
=> feat: Add ability to fetch only one document

packages/cozy-stack-client/src/FileCollection.js, packages/cozy-stack-client/src/FileCollection.spec.js, packages/cozy-stack-client/src/__snapshots__/FileCollection.spec.js.snap
Added a new function for one of the files special routes.
=> feat: Update file metadata

packages/cozy-client/src/associations/HasMany.js, packages/cozy-client/src/associations/HasMany.spec.js
Some interrogations: 
- Do I need to use `exists` before doing both action ? 
- Do I need to replace `_id` by the whole  document ? (cf `exists(document)` ?)
=> feat: Add addById / removeById to HasMany

packages/cozy-client/src/dsl.js, packages/cozy-client/src/index.js
- Export getQueryFromState for a component to access queries without
making a query
- Add limitBy method to query dsl
=> Small improvements

packages/cozy-client/src/CozyClient.spec.js, packages/cozy-client/src/__tests__/fixtures.js
- Cleanup test
- Add HasMany relationship to io.cozy.todos doctype
- Check that it is correctly instantiated after hydratation
=> test: Add second relationship tests after hydratation

packages/cozy-client/src/__tests__/store.spec.js
Mock Date.now to have time independent tests.
=> test: Do not rely on time

packages/cozy-client/src/store/documents.js
It's a temporary revert. I will work on the subject later today.
=> fix: Revert alloc

packages/cozy-pouch-link/src/CozyPouchLink.js, packages/cozy-pouch-link/src/PouchManager.js
I think these logs are useful to understand what's going on with replication while developing.
=> feat(pouch): Add dev logs

packages/cozy-client/examples/albums-relationships.js, packages/cozy-client/examples/file-relationships.js
Define a `HasManyReferenced` that allows to get all the albums referenced by each queried file.
=> Add albums example 

packages/cozy-pouch-link/src/PouchManager.js, packages/cozy-pouch-link/src/PouchManager.spec.js
When the database does not exist, the replication does not create it automatically. A call
to info() will ensure the database is created on the remote.
=> Fix ensure db exist

packages/cozy-pouch-link/src/PouchManager.js
Useful to have an idea of how much time a replication takes.
=> feat: Log time necessary to replicate a DB

packages/cozy-client/package.json, packages/cozy-client/src/authentication/mobile.js, yarn.lock
On iOS it's better to use SafariViewController to open authenticate page.
This code comes from https://github.com/cozy/cozy-drive/blob/b033f88209c83c7af7575119634b5e05429d57bc/src/lib/cozy-client/authentication/mobile.js
=> feat: Add authenticate with SafariViewController on mobile

packages/cozy-client/src/authentication/mobile.js
It works great until the call of the hide() method
=> fix: Rm safariViewController for Android

packages/cozy-stack-client/src/DocumentCollection.js, packages/cozy-stack-client/src/DocumentCollection.spec.js
We use this API in our services in Banks.
=> feat: Add fetch changes

packages/cozy-client/src/store/__snapshots__/queries.spec.js.snap, packages/cozy-client/src/store/queries.js, packages/cozy-client/src/store/queries.spec.js
=> fix: Do not crash if data is null

packages/cozy-client/src/associations/Association.js, packages/cozy-client/src/associations/HasOne.js, packages/cozy-client/src/associations/HasOne.spec.js, packages/cozy-client/src/associations/helpers.js, packages/cozy-client/src/associations/index.js, packages/cozy-client/src/index.js
This PR adds HasOne association ~~and make HasOneInPlace inherit from HasOne~~.
Needed into https://github.com/cozy/cozy-home/pull/1041/commits/336b10cb27fdba191248babd130efaa71d60d20d#r242760537
=> Implement HasOne

docs/how-tos.md, packages/cozy-client/src/connect.jsx
Add a deprecation message and update docs.
Closes #317
=> feat(cozy-client): Deprecate connect HOC

packages/cozy-stack-client/package.json, packages/cozy-stack-client/src/__snapshots__/urls.spec.js.snap, packages/cozy-stack-client/src/urls.js, packages/cozy-stack-client/src/urls.spec.js, yarn.lock
This PR is related with https://github.com/cozy/cozy-libs/pull/191
=> feat: Add urls helpers

docs/api/cozy-stack-client.md, packages/cozy-stack-client/src/CozyStackClient.js, packages/cozy-stack-client/src/TriggerCollection.js, packages/cozy-stack-client/src/__tests__/TriggerCollection.spec.js
This PR introduces base methods for creating and launching a trigger.
Status is WIP until I successfully use them in Cozy-Harvest-Lib.
=> Base for TriggersCollection ✨

docs/api/cozy-stack-client.md, packages/cozy-stack-client/src/AppCollection.js, packages/cozy-stack-client/src/CozyStackClient.js, packages/cozy-stack-client/src/__tests__/AppCollection.spec.js, packages/cozy-stack-client/src/__tests__/__snapshots__/AppCollection.spec.js.snap, packages/cozy-stack-client/src/__tests__/fixtures/apps.json, packages/cozy-stack-client/src/__tests__/fixtures/konnectors.json
For now we just to fetch all konnectors from `/konnectors` endpoint.
=> Handle konnectors with AppCollection

docs/api/cozy-stack-client.md, packages/cozy-stack-client/src/DocumentCollection.js, packages/cozy-stack-client/src/TriggerCollection.js, packages/cozy-stack-client/src/TriggerCollection.spec.js
Get the list of triggers. You can see documentation [here][1].
[1]: https://docs.cozy.io/en/cozy-stack/jobs/#get-jobstriggers
=> feat(cozy-stack-client): Add all function on TriggerCollection

docs/how-tos.md
CozyClient need a fetch method on node environment, we can add it using node-fetch
=> Add documentation about node environment

docs/how-tos.md
Not pushed for a previous PR before merging, sorry..
=> Fix documentation about node environment

docs/api/cozy-client.md, packages/cozy-client/src/CozyClient.js, packages/cozy-client/src/CozyClient.spec.js
In konnector/service context, CozyClient is instantiated from env vars. This PR
adds a method to do this automatically.
=> feat: Standard method of instantiating CozyClient from env vars

bin/build, docs/api/cozy-client.md, packages/cozy-client/src/index.js, packages/cozy-client/src/manifest.js, packages/cozy-client/src/manifest.spec.js, packages/cozy-client/src/registry.js, packages/cozy-client/src/registry.spec.js
Add app fetching and manifest sanitization.
=> feat: Add app fetching

packages/cozy-client/src/manifest.js
Thanks @edas for the suggestions.
=> refactor: Rename var and add others category

docs/api/cozy-stack-client.md, packages/cozy-stack-client/src/TriggerCollection.js, packages/cozy-stack-client/src/TriggerCollection.spec.js
Adds the ability to delete a `io.cozy.triggers`.
=> feat: Delete triggers

docs/api/cozy-client.md, packages/cozy-client/src/ObservableQuery.js
=> docs: Add docstrings

packages/cozy-stack-client/src/CozyStackClient.js, packages/cozy-stack-client/src/JobCollection.js, packages/cozy-stack-client/src/JobCollection.spec.js
=> feat: Add job creation + fetching

docs/api/cozy-stack-client.md, packages/cozy-stack-client/src/FileCollection.js, packages/cozy-stack-client/src/FileCollection.spec.js, packages/cozy-stack-client/src/__snapshots__/FileCollection.spec.js.snap
Add support for this functionality: https://github.com/cozy/cozy-stack/blob/master/docs/files.md#post-filesuploadmetadata
=> Support for file metadata creation

packages/cozy-stack-client/src/TriggerCollection.js, packages/cozy-stack-client/src/TriggerCollection.spec.js
Time has come where we are needing in cozy-harvest-lib.
=> StackClient: Implement TriggerCollection.get method

docs/api/cozy-stack-client.md, packages/cozy-stack-client/src/FileCollection.js, packages/cozy-stack-client/src/FileCollection.spec.js
Add a method to check if a file/directory belongs to a parent's hierarchy, based on its _id
=>  feat: IsChild 

docs/getting-started.md
Documentation on how to configure Jest for cozy-client.
=> docs: Update jest configuration

docs/api/cozy-client.md, packages/cozy-client/src/CozyClient.js, packages/cozy-client/src/CozyClient.spec.js
=> feat: Instantiate client from old client

docs/api/cozy-client.md, packages/cozy-client/src/CozyClient.js, packages/cozy-client/src/CozyClient.spec.js
Doc says it all ;)
Fix https://github.com/cozy/cozy-client/issues/445
=> feat: Add registerPlugin method

.github/auto-merge.yml, docs/dev.md, package.json, yarn.lock
probot automerge is configured to automerge if label `merge` is present on a PR and
at least 1 reviewer has approved the PR. Status checks must also pass.
=> chore: Configure automerge

docs/api/cozy-client.md, packages/cozy-client/src/CozyClient.js, packages/cozy-client/src/CozyClient.spec.js
=> feat: Change plugin interface

.eslintrc.json, bin/build, package.json, packages/cozy-client/src/__tests__/ObservableQuery.spec.js, packages/cozy-client/src/hoc.spec.js
1st part of a PR, only dealing with small refactors and chores.
=> feat: Small improvements and refactor

packages/cozy-stack-client/src/JobCollection.js, packages/cozy-stack-client/src/JobCollection.spec.js, packages/cozy-stack-client/src/KonnectorCollection.js, packages/cozy-stack-client/src/TriggerCollection.js, packages/cozy-stack-client/src/__tests__/KonnectorCollection.spec.js, packages/cozy-stack-client/src/__tests__/__snapshots__/KonnectorCollection.spec.js.snap
- Launch a konnector
- Update a konnector
- Wait for the completion of a job
=> feat: Add methods to {Trigger/Job}Collection

docs/api/cozy-client.md, packages/cozy-client/src/CozyClient.js, packages/cozy-client/src/__tests__/ObservableQuery.spec.js, packages/cozy-client/src/__tests__/associations.spec.js, packages/cozy-client/src/__tests__/connect.spec.jsx, packages/cozy-client/src/__tests__/store.spec.js, packages/cozy-client/src/associations/HasMany.js, packages/cozy-client/src/store/documents.js, packages/cozy-client/src/store/index.js, packages/cozy-stack-client/src/JobCollection.js
Various little improvements. Commits are really short and
have descriptions, so everything should be pretty self-explanatory.
There are two breaking changes, but they should not really concern
anyone.
=> Improvements

docs/api/cozy-stack-client.md, packages/cozy-stack-client/src/FileCollection.js
- createFile was not exposed to our documentation. fixed it. 
- added a few jsdoc
- fixed a few markdown issues
=> docs: Add a doc to tell how to upload a file

docs/architecture.md, docs/toc.yml
Note the architecture should be eventually completed with: 
* Init
* Associations
* Mutations
=> docs: Add cozy-client architecture

packages/cozy-client/src/registry.js
When we need the registry status of just one app instead of all of them :)
=> feat: Fetch a single app from the registry

packages/cozy-client/src/models/triggers.js, packages/cozy-client/src/models/triggers.spec.js
Last_execution is nested under current_state.
=> fix: Get last execution from right attribute

docs/react-integration.md
Adding a section on fetch policies in tutorial.
=> docs: Document fetch policies in tutorial

docs/api/cozy-client.md, packages/cozy-client/src/CozyClient.js, packages/cozy-client/src/index.js, packages/cozy-client/src/policies.js, packages/cozy-client/src/registry.js
This way we can import only fetchPolicies if needed
=> feat: Export fetchPolicies directly

packages/cozy-client/src/models/index.js, packages/cozy-client/src/models/instance.js, packages/cozy-client/src/models/instance.spec.js
Add an Instance model to manage instance's informations
=> feat: Add Instance Model to manage instance information

docs/api/cozy-client.md, packages/cozy-client/src/models/instance.js, packages/cozy-client/src/models/instance.spec.js
Create a link to the cozy's manager.
=> feat: Instance model add buildPremiumLink

docs/api/cozy-client.md, docs/api/cozy-stack-client.md, docs/react-integration.md, packages/cozy-client/src/CozyClient.js, packages/cozy-client/src/index.js, packages/cozy-client/src/utils.js, packages/cozy-stack-client/src/CozyStackClient.js, packages/cozy-stack-client/src/__tests__/CozyStackClient.spec.js, packages/cozy-stack-client/src/index.js
=> feat: Add helper functions

packages/cozy-client/src/models/applications.spec.js, packages/cozy-client/src/models/index.js
Forgot to export the new model!
=> feat: Export applications model

docs/api/cozy-client.md, packages/cozy-client/src/models/instance.js, packages/cozy-client/src/models/instance.spec.js
We need to check if an instance already subscribed to an offer
=> feat: Instance add method to check if already subscribed

docs/api/cozy-stack-client.md, packages/cozy-stack-client/src/FileCollection.js
Added the docstring for a missing method.
=> docs: Added FilsCollection.get

docs/react-integration.md
- Add TOC to React's integration
- Added example in React's integration on how to test with mockClient
=> Docs: Add how to use mockClient

docs/api/cozy-client.md, packages/cozy-client/src/models/file.js, packages/cozy-client/src/models/file.spec.js, packages/cozy-client/src/models/index.js
Add a few helpers for file. 
https://github.com/cozy/cozy-client/pull/571 is too consequent for now, will try to move it bit by bit
=> feat: Add file model

docs/api/cozy-client.md, packages/cozy-client/src/models/index.js, packages/cozy-client/src/models/note.js, packages/cozy-client/src/models/note.spec.js
Since Note is coming, we need an helper to centralize few utils.
Here, I just added a method to generate the link to a note from an other app.
=> feat: Add Note model

docs/api/cozy-client.md, packages/cozy-client/src/models/file.js, packages/cozy-client/src/models/file.spec.js
As requested in https://github.com/cozy/cozy-notes/pull/41#discussion_r360844792
=> feat: File normalization function

packages/cozy-client/package.json, yarn.lock
Some deps are necessary for createClientInteractive to work.
=> chore: Add deps necessary for createClientInteractive

docs/react-integration.md, packages/cozy-client/src/index.js, packages/cozy-client/src/node.js
* createMockClient is exported for the browser and node
* createClientInteractive is exported only for node
Also update documentation about mocked client
=> Add createMockClient and createClientInteractive exports

docs/api/cozy-client.md, packages/cozy-client/src/models/file.js, packages/cozy-client/src/models/index.js, packages/cozy-client/src/models/permission.js, packages/cozy-client/src/models/permission.spec.js
It is needed in cozy-notes, to see if we  should allows
write when displaying a shared document.
=> feat: Checks if a doc has read-only permissions

docs/api/cozy-client.md, docs/api/cozy-stack-client.md
Just to fix issue with our documentation
=> fix: Fix doc

docs/hooks.md, packages/cozy-client/src/hooks/index.js, packages/cozy-client/src/hooks/useCapabilities.jsx, packages/cozy-client/src/hooks/useCapabilities.spec.jsx
Add a hook to call capabilities endpoint
=> feat: Add useCapabilities hook

docs/api/cozy-client.md, packages/cozy-client/src/models/folder.js, packages/cozy-client/src/models/folder.spec.js, packages/cozy-client/src/models/index.js
This PR adds the functions exposed in the Folders class of cozy-doctypes here in cozy-client. Thjey help dealing with out magic folders.
=> feat: Added folder model

packages/cozy-stack-client/src/CozyStackClient.js, packages/cozy-stack-client/src/ShortcutsCollection.js, packages/cozy-stack-client/src/ShortcutsCollection.spec.js
Add a shortcutscollection to handle shortcut creation
=> feat: Add ShortcutsCollection

packages/cozy-stack-client/src/FileCollection.js, packages/cozy-stack-client/src/FileCollection.spec.js
This PR adds support for using bookmark based pagination on FileCollection.find(). 
The stack API is a bit strange on this route, it returns a link containing a `cursor` param which is technically a bookmark, and we need to call that route with the bookmark named `bookmark` 😁.  The inconsistencies start to be addressed [here](https://github.com/cozy/cozy-stack/pull/2427) but in the meantime we can abstract the difference away.
=> feat: Support cursor on FilesCollection.find

packages/cozy-stack-client/src/CozyStackClient.js, packages/cozy-stack-client/src/FileCollection.js, packages/cozy-stack-client/src/xhrFetch.js, packages/cozy-stack-client/src/xhrFetch.spec.js
Since fetch does not support upload progress event, we have to use
XMLHttpRequest
=> feat: Progress events for upload

docs/api/cozy-client.md, packages/cozy-client/src/hooks/useFetchJSON.js, packages/cozy-client/src/hooks/useFetchJSON.spec.js
Ability to use client's fetch json.
=> Add useFetchJSON

packages/cozy-client/codemods/use-client.js, packages/cozy-client/package.json, yarn.lock
Use hocReplacer from @cozy/codemods to replace withClient by useClient.
=> feat: Codemod to transform withClient into useClient

packages/cozy-client/codemods/use-client.js
Two small fixes due to a refactor
=> Two codemods fixes

packages/cozy-client/src/CozyClient.js, packages/cozy-client/src/CozyClient.spec.js, packages/cozy-client/src/store/index.js
Reset cozy client redux slice to initial state on logout.
=> fix: Reset state on logout

docs/api/cozy-stack-client.md, packages/cozy-stack-client/src/FileCollection.js, packages/cozy-stack-client/src/FileCollection.spec.js
Add a method to empty the trash
=> feat: Add emptyTrash method

docs/api/cozy-stack-client.md, packages/cozy-client/src/CozyClient.spec.js, packages/cozy-stack-client/src/FileCollection.js
Now we can do : 
```jsx
client.save({ ...file, name: 'newName' , _rev: file.meta.rev })
```
=> feat: Expose FileCollection.update() via CozyClient.save()

packages/cozy-pouch-link/src/CozyPouchLink.js, packages/cozy-pouch-link/src/CozyPouchLink.spec.js, packages/cozy-pouch-link/src/jsonapi.js, packages/cozy-pouch-link/src/jsonapi.spec.js
Two more little couch nits that end up causing errors. Commits & tests describe what's going on!
=> Aditionnal pouch fixes

packages/cozy-client/src/associations/HasManyTriggers.js, packages/cozy-client/src/models/index.js, packages/cozy-client/src/models/trigger.js, packages/cozy-client/src/models/trigger.spec.js, packages/cozy-client/src/models/utils.js, packages/cozy-client/src/models/utils.spec.js
- trigger.hasActionableError: returns whether the user can solve the error from the
trigger
- getCreatedByApp: returns the app that created the document
=> feat: Add methods

packages/cozy-stack-client/src/ContactsCollection.js, packages/cozy-stack-client/src/ContactsCollection.spec.js, packages/cozy-stack-client/src/CozyStackClient.js
To find the myself contact, we need to use a special route on
the stack. This routes creates the contact if it does not
exist
=> feat: Add ContactCollection

packages/cozy-client/src/models/utils.js, packages/cozy-client/src/models/utils.spec.js
Add models util function to check if a doc has been updated
by an app.
=> feat: Add hasBeenUpdatedByApp helper

docs/api/cozy-stack-client.md, packages/cozy-stack-client/src/FileCollection.js
Better docstring for CozyClient::destroy
=> docs: Improve docstrings

docs/hooks.md
Fix a broken link in hook page and add some links to missing hook
=> fix: Broken and missing links in hook

docs/react-integration.md
=> fix: Link from React Integration to fetchPolicies

.travis.yml, docs/api/cozy-client.md, packages/cozy-client/src/associations/HasMany.js, packages/cozy-client/src/associations/HasMany.spec.js, packages/cozy-client/src/associations/__snapshots__/HasMany.spec.js.snap, packages/cozy-client/src/models/account.js, packages/cozy-client/src/models/account.spec.js, packages/cozy-client/src/queries/dsl.js
Main feature is the addition of static helpers to deal with
HasMany relationship data.
There are smaller commits whose description should be enough.
=> Add static helpers for HasMany relationship

docs/relationships.md
=> docs: Update relationship

docs/api/cozy-client.md, packages/cozy-client/src/CozyClient.js, packages/cozy-client/src/ObservableQuery.js, packages/cozy-client/src/hooks/useQuery.js, packages/cozy-client/src/hooks/useQuery.spec.jsx, packages/cozy-client/src/store/documents.js, packages/cozy-client/src/testing/utils.js
=> Use query can return single doc data for single doc queries

docs/getting-started.md
As proposed in https://github.com/cozy/cozy-client/issues/751
=> docs: Mention query documentation

docs/api/cozy-client.md, packages/cozy-client/src/CozyClient.js
=> docs: Add singleDocData docs on getQueryFromState

docs/api/cozy-client.md, packages/cozy-client/src/models/contact.js, packages/cozy-client/src/models/contact.spec.js
- Add makeFullname, makeDisplayName, and makeDefaultSortIndexValue to come complete getFullname, getDisplayName etc.
- getIndexByFamilyNameGivenNameEmailCozyUrl renamed in getDefaultSortIndexValue
=> Add Contact's method to make fullname, displayName and defautlndexValue

docs/api/cozy-client.md, packages/cozy-client/src/associations/HasMany.js, packages/cozy-client/src/associations/HasMany.spec.js, packages/cozy-client/src/associations/__snapshots__/HasMany.spec.js.snap
Hello, I propose to add three static helpers for HasMany relationship
cf: #781
=> feat: Add setHasManyItems, removeHasManyItem & getHasManyItems  helpers

packages/cozy-client/src/models/document.spec.js
We now try to avoid logs in tests to minimize noise
=> fix: Do not log in tests

docs/architecture.md
Add text after architecture diagram.
Fix #819
=> docs: Improve architecture doc

docs/api/cozy-client.md, packages/cozy-client/src/models/file.js, packages/cozy-client/src/models/file.spec.js
fix https://github.com/cozy/cozy-client/issues/836
=> feat: Add isSharingShortcut and isSharingShortcutNew

docs/api/cozy-client.md, packages/cozy-client/src/store/queries.js, packages/cozy-client/src/store/queries.spec.js
fix https://github.com/cozy/cozy-client/issues/845
=> fix: Add partial index selectors to sift

packages/cozy-client/src/store/queries.js
=> refactor: Remove useless console log

docs/api/cozy-client.md, docs/timeseries.md, docs/toc.yml, packages/cozy-client/src/models/index.js, packages/cozy-client/src/models/timeseries.js, packages/cozy-client/src/models/timeseries.spec.js
We introduce a new doctype in Cozy to manipulate time serie ; those helpers are useful to save such data by ensuring the basic format is respected and to fetch it through a generic query. 
For the time series format, see: https://github.com/cozy/cozy-doctypes/pull/170
=> feat: Add TimeSerie helpers

packages/cozy-client/README.md
Add commands to update API docs and types in README.
=> docs: Add bit of docs on how to update docs and types

packages/cozy-stack-client/package.json, yarn.lock
See https://github.com/cozy/cozy-libs/pull/1273
=> feat: Upgrade cozy-flag to fix react import in node env

packages/cozy-stack-client/src/DocumentCollection.spec.js
This follows https://github.com/cozy/cozy-client/pull/884
=> test: Add coverage for index creation and migration

docs/api/cozy-client.md, docs/api/cozy-stack-client.md, packages/cozy-client/src/CozyClient.js, packages/cozy-client/src/Query.jsx, packages/cozy-client/src/context.js, packages/cozy-client/src/helpers.js, packages/cozy-client/src/hooks/useClient.js, packages/cozy-client/src/hooks/useClientErrors.jsx, packages/cozy-client/src/models/instance.js, packages/cozy-client/src/models/timeseries.js, packages/cozy-client/src/models/trigger.js, packages/cozy-client/src/queries/dsl.js, packages/cozy-client/src/types.js, packages/cozy-client/tsconfig.json, packages/cozy-client/types/CozyClient.d.ts, packages/cozy-client/types/cli/index.d.ts, packages/cozy-client/types/context.d.ts, packages/cozy-client/types/hooks/useClient.d.ts, packages/cozy-client/types/models/instance.d.ts, packages/cozy-client/types/models/permission.d.ts, packages/cozy-client/types/models/trigger.d.ts, packages/cozy-client/types/queries/dsl.d.ts, packages/cozy-client/types/types.d.ts, packages/cozy-stack-client/src/Collection.js
Add types and typedefs for initialisation of CozyClient from
node environment.
=> feat: Improve types for CozyClient.fromEnv

packages/cozy-client/examples/web/package.json, packages/cozy-client/examples/web/yarn.lock
To remove security warnings in Github
Nothing wrong for now, but the Github panel was annoying me. 
see https://github.com/cozy/cozy-client/security/dependabot 
hope it will close it
=> chore: Remove deps & upgrade others for CC examples

docs/api/cozy-client.md, docs/react-integration.md, packages/cozy-client/src/CozyClient.js, packages/cozy-client/src/__tests__/utils.js, packages/cozy-client/src/devtools/Flags.jsx, packages/cozy-client/src/devtools/LibraryVersions.jsx, packages/cozy-client/src/devtools/Queries.jsx, packages/cozy-client/src/devtools/index.jsx, packages/cozy-client/types/CozyClient.d.ts, packages/cozy-client/types/cli/index.d.ts, packages/cozy-client/types/types.d.ts
- Add how to activate VersionPlugin in Libraries panel
- Do not crash if there are no queries yet
- Use the correct object from cozy-flags
=> fix: Devtools improvements

packages/cozy-client/src/devtools/index.jsx, packages/cozy-client/types/types.d.ts
Hurray, we can resize the devtools panel.
Logic taken from react-query :blush:.
=> feat: Add devtools panel resize

docs/api/cozy-client.md, packages/cozy-client/src/hooks/useAppsInMaintenance.jsx, packages/cozy-client/src/hooks/useAppsInMaintenance.spec.jsx, packages/cozy-client/types/hooks/useAppsInMaintenance.d.ts
Allows to use it in other projects.
Today we use it in cozy-home.
We need to use it in cozy banks.
=> feat: Add useAppsInMaintenance

docs/api/cozy-client.md, packages/cozy-client/src/models/file.js, packages/cozy-client/src/models/file.spec.js, packages/cozy-client/src/types.js, packages/cozy-client/types/models/file.d.ts, packages/cozy-client/types/types.d.ts
ALBUMS_DOCTYPE, isOnlyOfficeFile,
shouldBeOpenedByOnlyOffice, isReferencedByAlbum,
hasMetadataAttribute
=> feat: Add some file models from Drive

docs/api/cozy-client.md, packages/cozy-client/package.json, packages/cozy-client/src/CozyClient.js, packages/cozy-client/src/__mocks__/react-native-inappbrowser-reborn.js, packages/cozy-client/src/__mocks__/react-native.js, packages/cozy-client/src/authentication/mobile.js, packages/cozy-client/types/CozyClient.d.ts, packages/cozy-client/types/__mocks__/react-native-inappbrowser-reborn.d.ts, packages/cozy-client/types/__mocks__/react-native.d.ts, packages/cozy-client/types/authentication/mobile.d.ts, yarn.lock
Add authentication method for react native environment
=> feat: Add react-native authentication

docs/api/cozy-client.md, packages/cozy-client/src/authentication/mobile.js, packages/cozy-client/src/authentication/mobile.native.js, packages/cozy-client/types/authentication/mobile.d.ts, packages/cozy-client/types/authentication/mobile.native.d.ts
Tested with the react native application
The native.js file will be ignored in other environment and shall cause no regression
This PR is made to replace https://github.com/cozy/cozy-client/pull/956 which did not work for connectors environment.
=> feat: Use native.js file to make react native really optional

packages/cozy-stack-client/src/JobCollection.js, packages/cozy-stack-client/src/JobCollection.spec.js
I was sur I did it in the previous PR.
=> fix: Add normalization to jobCollection.update

packages/cozy-client/README.md, packages/cozy-client/src/CozyClient.js, packages/cozy-client/src/CozyClient.spec.js
=> feat: Instanciating new CozyClient now add capabilities to it

packages/cozy-client/src/CozyClient.js, packages/cozy-client/src/CozyClient.spec.js
fix https://github.com/cozy/cozy-client/issues/977
=> fix: LoadInstanceOptionsFromDOM add root datas and cozy datas

docs/api/cozy-pouch-link.md, docs/devtools.md, packages/cozy-client/src/devtools/Pouch.jsx, packages/cozy-client/src/devtools/Queries.jsx, packages/cozy-client/src/devtools/index.jsx, packages/cozy-pouch-link/src/CozyPouchLink.js, packages/cozy-pouch-link/src/PouchManager.js, packages/cozy-pouch-link/src/PouchManager.spec.js, packages/cozy-pouch-link/src/localStorage.js
Add devtool panel that displays:
- the last synchronization date of pouches (for all databases)
- the doctypes managed by pouch
- Buttons to start/stop replication
- Button to destroy local pouches
=> Pouch panel

.github/workflows/codeql-analysis.yml
some false positives alert (fake token in spec files). Dismissed.
=> chore: Add CodeQL

docs/api/cozy-client/modules/models.folder.md, packages/cozy-client/src/models/folder.js, packages/cozy-client/src/models/folder.spec.js, packages/cozy-client/types/models/folder.d.ts
Pour les besoins de l'app Mes papiers, ajout de l'entrée `PAPERS` dans la constante `MAGIC_FOLDERS`
=> feat: Add papers path to MAGIC_FOLDERS contante

packages/cozy-client/src/authentication/mobile.native.js
On iOS, the # added to the URL by the stack for security
reason is encoded to %23. Because of this, URL().searchParams
is not working as expected since %23 is added to the param
instead of being ignored and assigned to the hash.
Let's convert back %23 to # manually.
I think the issue is related to Linking component but didn't
find any issues on github about it. Need to make a simple
reproduction case to create the issue.
Not proud of this one, but I need to move on the flagship app
See related issue https://github.com/cozy/cozy-client/issues/1071
=> fix: Login on RN iOS

docs/api/cozy-stack-client.md, packages/cozy-stack-client/src/FileCollection.js
- Add missing JS Docs on FileCollection file
=> fix(docs): Add JS Docs on File Collection

docs/api/cozy-client/modules/models.file.md, packages/cozy-client/src/models/file.js, packages/cozy-client/src/models/file.spec.js, packages/cozy-client/types/models/file.d.ts
Added the `fetchBlobFileById` function to simply retrieve the Blob of a file from its ID
=> feat: Add fetchBlobFileById function

packages/cozy-client/src/assets/qualifications.json
=> fix(qualification): Fix typo in identity

docs/api/cozy-client/modules/models.folder.md, packages/cozy-client/src/models/folder.js, packages/cozy-client/src/models/folder.spec.js, packages/cozy-client/types/models/folder.d.ts
To export the data always in the same folder, we need to add Coach_CO2 to Magic_Folders
=> feat: Add CoachCO2 to MAGIC_FOLDERS

package.json, yarn.lock
Because 0.75 is broken but 0.7.2 works
=> fix(deps): update dependency commitlint-config-cozy to v0.7.2

docs/api/cozy-client/README.md, packages/cozy-client/src/store/index.js, packages/cozy-client/types/store/index.d.ts
To be able to use redux-dev-tools browser extension
=> Add redux devtools to the store

docs/architecture.md
Try to explain how queries and documents slice are updated
=> docs: How CozyClient store works

docs/architecture.md
This document the update behaviour in the store that never removes existing fields
=> docs: Add doc about store updates

docs/api/cozy-stack-client.md, packages/cozy-stack-client/src/DocumentCollection.js, packages/cozy-stack-client/src/mangoIndex.js
=> chore(jsdocs): Fix incorrect naming in jsdocs

packages/cozy-client/src/assets/qualifications.json, packages/cozy-client/src/models/document/locales/en.json, packages/cozy-client/src/models/document/locales/fr.json
Adding specific qualification for contracts with energy providers
=> feat: Add energy contract qualification

docs/api/cozy-stack-client.md, packages/cozy-stack-client/src/FileCollection.js, packages/cozy-stack-client/src/FileCollection.spec.js
Will be used here https://github.com/cozy/cozy-drive/pull/2727
=> feat: Add copy in FileCollection

docs/api/cozy-stack-client.md, packages/cozy-stack-client/src/PermissionCollection.js
See warning to have more explanation
=> fix: Add deprecated PermCollection.findApps

docs/api/cozy-client/classes/CozyClient.md, packages/cozy-client/src/types.js, packages/cozy-client/types/types.d.ts
I follow the properties describe into the doc from cozy.io [GET /settings/capabilities](https://docs.cozy.io/en/cozy-stack/settings/#get-settingscapabilities). 
**Related PRs:**
- https://github.com/cozy/cozy-settings/pull/550
=> feat: Add types to client capabilities

docs/metadata.md
Update doc metadata with new possibility for sourceAccount and source AccountIdentifier
=> Update doc metadata

docs/api/cozy-client/modules/models.account.md, docs/api/cozy-client/modules/models.trigger.md, packages/cozy-client/src/models/account.js, packages/cozy-client/src/models/account.spec.js, packages/cozy-client/src/models/trigger.js, packages/cozy-client/src/models/trigger.spec.js, packages/cozy-client/src/types.js, packages/cozy-client/types/models/account.d.ts, packages/cozy-client/types/models/trigger.d.ts, packages/cozy-client/types/types.d.ts
These features will be used by harvest and any app willing to create accounts or triggers
I also tried to add proper jsdoc for those doctypes (+io.cozy.konnectors)
- feat: Import accounts and triggers features from harvest
- docs: Add ts-check + corresponding fixes
- docs: Build doc
=> feat: Import accounts and triggers features from harvest

docs/api/cozy-client/modules/models.account.md, packages/cozy-client/src/models/account.js, packages/cozy-client/src/models/account.spec.js, packages/cozy-client/types/models/account.d.ts
To know if a given account is associated to a trigger or not.
=> feat: Add account.isAccountWithTrigger

packages/cozy-stack-client/src/SettingsCollection.js, packages/cozy-stack-client/src/SettingsCollection.spec.js
id was set to path instead of _id.
=> fix: Return correct bitwarden id in SettingsCollection.getById

docs/api/cozy-client/interfaces/models.instance.SettingsInfo.md, docs/api/cozy-client/modules/models.instance.md, packages/cozy-client/src/models/bitwarden.js, packages/cozy-client/src/models/capability.js, packages/cozy-client/src/models/instance.js, packages/cozy-client/src/models/user.js, packages/cozy-client/src/models/user.spec.js, packages/cozy-client/types/models/bitwarden.d.ts, packages/cozy-client/types/models/capability.d.ts, packages/cozy-client/types/models/instance.d.ts, packages/cozy-client/types/models/user.d.ts
This helper is intended to harmonise the way we check whether the user has a password
=> feat: Add hasPassword helper

packages/cozy-client/src/models/geo.js, packages/cozy-client/src/models/geo.spec.js, packages/cozy-client/types/models/geo.d.ts
This adds methods to compute latitude and longitude deltas from a distance, which is typically useful to be able to query close coordinates.
We also add a centroid computation in a sphere, that is uesful to determine the center location of a set of geo points.
=> feat: Add geographic methods

docs/api/cozy-client/modules/models.geo.md, docs/api/cozy-client/modules/models.md, packages/cozy-client/src/models/index.js, packages/cozy-client/types/models/index.d.ts
It should be more useful like this
=> feat: Export geo methods

packages/cozy-client/src/models/countries.js, packages/cozy-client/src/models/countries.spec.js, packages/cozy-client/types/models/countries.d.ts
=> feat: Add countries model

docs/api/cozy-client/README.md, packages/cozy-client/src/hooks/index.js, packages/cozy-client/src/index.js, packages/cozy-client/src/utils.js, packages/cozy-client/types/hooks/index.d.ts, packages/cozy-client/types/index.d.ts, packages/cozy-client/types/utils.d.ts
=> Add and export isQueriesLoading and hasQueriesBeenLoaded

docs/api/cozy-client/modules/models.trigger.md, packages/cozy-client/src/models/trigger.js, packages/cozy-client/src/models/trigger.spec.js, packages/cozy-client/types/models/trigger.d.ts
Add an isKonnector method that check if its a clisk or a server side konnector.
Use this isKonnector in getKonnector since we want to get the konnectors, we don't want the implementation details (aka we don't care if its a clisk or not).
=> feat: Supports clisk for getKonnector

docs/api/cozy-stack-client.md, packages/cozy-stack-client/src/NotesCollection.js, packages/cozy-stack-client/src/NotesCollection.spec.js
This method will allow me to use real time on cozy-notes
=> feat(NotesCollection): Add get method

docs/api/cozy-client/classes/CozyClient.md, docs/metadata.md, packages/cozy-client/src/CozyClient.js, packages/cozy-client/src/CozyClient.spec.js, packages/cozy-client/src/__tests__/fixtures.js, packages/cozy-client/src/types.js, packages/cozy-client/types/CozyClient.d.ts, packages/cozy-client/types/__tests__/fixtures.d.ts, packages/cozy-client/types/types.d.ts
And add sourceAccountIdentifier in cozyMetadatas.sourceAccountIdentifier
=> [SCR-114] feat: Allow CozyClient to get sourceAccountIdentifier in appMetadatas

packages/cozy-client/src/models/document/documentTypeData.js
=> feat(Qualification): Change work & activity themes icon

packages/cozy-client/src/models/document/locales/en.json, packages/cozy-client/src/models/document/locales/fr.json, packages/cozy-client/src/models/paper.js, packages/cozy-client/src/models/paper.spec.js
Needed for https://github.com/cozy/mespapiers/pull/635
=> feat(Document): Update countries translation in Viewer informations

docs/api/cozy-client/modules/models.file.md
I didn't rebase before the merge of this [PR](https://github.com/cozy/cozy-client/pull/1508). The CI didn't launch again so I missed that the doc was broken. This PR fixes the deployment of the master branch 🙂
=> fix: Update docs after merge

packages/cozy-client/src/models/doctypes/locales/en.json, packages/cozy-client/src/models/doctypes/locales/fr.json
> **See https://github.com/cozy/cozy-doctypes/pull/266**
Added the io.cozy.calendar doctype and added io.cozy.timeseries.grades to the timeseries doctype as this is required for [Pronote konnector](https://github.com/konnectors/pronote).
=> docs: Added grades and calendar doctypes to locales

packages/cozy-stack-client/src/NextcloudFilesCollection.js
Only to trigger NPM release of cozy-stack-client
=> feat(NextcloudFilesCollection): Add spacing

CODEOWNERS
Goodbye @Crash--, hello @cballevre
=> chore(codeowners): Change repo codeowners

docs/api/cozy-pouch-link/classes/PouchLink.md, packages/cozy-client/src/CozyClient.js, packages/cozy-client/src/associations.spec.js, packages/cozy-client/src/models/file.js, packages/cozy-client/src/models/file.spec.js, packages/cozy-pouch-link/src/CozyPouchLink.js, packages/cozy-pouch-link/src/helpers.js, packages/cozy-pouch-link/types/helpers.d.ts
All commits have their respective description
=> fix: Fix some problems related to Offline feature

docs/api/cozy-client/classes/CozyClient.md, packages/cozy-client/src/CozyClient.js, packages/cozy-client/src/helpers/settings.js, packages/cozy-client/types/CozyClient.d.ts
With commit courtesy of @bastiendmt
=> docs: Fix dictionary typo

.github/workflows/ci-cd.yml
=> chore: Fixing the CI because of a stupid copy-and-paste mistake

packages/cozy-pouch-link/package.json, yarn.lock
Install latest version of `parcel` to get a more recent version of
`deasync` (one of its dependencies) as the current version prevents
installing dependencies in some cases.
=> fix(deps): Upgrade cozy-pouch-link's parcel

docs/api/cozy-stack-client.md, packages/cozy-stack-client/src/FileCollection.js, packages/cozy-stack-client/src/FileCollection.spec.js, packages/cozy-stack-client/src/SharingCollection.js, packages/cozy-stack-client/src/SharingCollection.spec.js
Add shared drive option when creating a sharing. I also included some refactoring too.
=> Add shared drive option when creating a sharing

docs/api/cozy-client/classes/CozyClient.md, docs/api/cozy-pouch-link/classes/PouchLink.md, packages/cozy-client/src/CozyClient.js, packages/cozy-pouch-link/src/CozyPouchLink.js, packages/cozy-pouch-link/src/db/pouchdb/getDocs.js, packages/cozy-pouch-link/src/errors.js, packages/cozy-pouch-link/src/files.js, packages/cozy-pouch-link/src/jsonapi.js, packages/cozy-pouch-link/types/CozyPouchLink.d.ts, packages/cozy-pouch-link/types/errors.d.ts, packages/cozy-pouch-link/types/files.d.ts, packages/cozy-pouch-link/types/jsonapi.d.ts
This includes various fixes and improvements to correctly handle queries in the DataProxy.
See commit descriptions for more insights
:warning:  It is based on https://github.com/cozy/cozy-client/pull/1606 that should be merged first
=> Correctly handle queries with DataProxy

docs/api/cozy-client/README.md, packages/cozy-client/src/utils.js, packages/cozy-client/types/utils.d.ts
This is useful for apps wanting to know whether the debug flag is enabled
=> feat: Add helper for debug flag

docs/api/cozy-client/README.md, packages/cozy-client/src/hooks/useFetchHomeShortcuts.jsx
It was breaking tests in cozy-bar.
=> fix: Use local import in useFetchHomeShortcuts
