cozy/cozy-client

- .gitignore
- README.md
- lerna.json
- packages/cozy-client/package.json
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/Mutation.js
- packages/cozy-client/src/__mocks__/cozy-stack-link.js
- packages/cozy-client/src/__tests__/CozyClient.spec.js
- packages/cozy-client/src/__tests__/connect.spec.jsx
- packages/cozy-client/src/__tests__/store.spec.js
- packages/cozy-client/src/__tests__/withMutate.spec.jsx
- packages/cozy-client/src/__tests__/withMutation.spec.jsx
- packages/cozy-client/src/connect.jsx
- packages/cozy-client/src/index.js
- packages/cozy-client/src/store/documents.js
- packages/cozy-client/src/store/index.js
- packages/cozy-client/src/store/mutations.js
- packages/cozy-client/src/store/queries.js
- packages/cozy-client/src/withMutate.jsx
- packages/cozy-client/src/withMutation.jsx
- packages/cozy-stack-link/package.json
- packages/cozy-stack-link/src/CozyStackLink.js
- packages/cozy-stack-link/src/DocumentCollection.js
- packages/cozy-stack-link/src/__tests__/CozyStackLink.spec.js
- packages/cozy-stack-link/src/__tests__/DocumentCollection.spec.js
Dans cette PR, j'introduis les mutations, c.a.d la MAJ de données. Je pense que le mieux est de commencer par lire la doc : https://github.com/goldoraf/cozy-client/blob/6ecce13921175d76b8913e30b5ed50935e7132e3/README.md#mutating-data
Ce système peut paraitre un peu compliqué d'un premier abord (surtout la partie `updateQueries`), mais il présente l'avantage d'être extrêmement flexible, ce qui est important, car toutes les mutations ne sont pas forcément du CRUD basique et, par conséquent, offrir la flexibilité de mettre à jour les queries manuellement est nécessaire. Cependant, pour les cas simples (comme ajouter un todo à une todolist), cela paraitrait vraiment trop compliqué. Aussi mon idée pour la suite (mais ce sera pour une autre PR bien entendu) serait d'enrichir les props injectées …
> Mutations basics

- packages/cozy-client/src/Query.jsx
Adding PropTypes helps to understand errors more quickly. IMHO it is essential for a library.
> Add proptypes to query

- packages/cozy-client/src/store/documents.js
Reducers throws when receiving documents without _type
> feat: throw when no _type

- package.json
Just a suggestion, but I don't think we should lint files before running tests. 
I assume we all sometimes write some crap code while writing tests, and it's really annoying if the test don't even run because the temporary code has linting errors.
> chore: don't lint before tests

- README.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyLink.js
- packages/cozy-pouch-link/src/CozyPouchLink.js
- packages/cozy-pouch-link/src/mango.js
- packages/cozy-stack-client/src/AccessToken.js
- packages/cozy-stack-client/src/CozyStackClient.js
- packages/cozy-stack-client/src/OAuthClient.js
- packages/cozy-stack-client/src/__tests__/OAuthClient.spec.js
- packages/cozy-stack-client/src/__tests__/__snapshots__/OAuthClient.spec.js.snap
- packages/cozy-stack-client/src/index.js
*Please ignore the changes right now, i just made them to get the PR started.*
The goal of this PR is to add OAuth support to Cozy Client. I'll base my work in large parts on the [cozy-client-js](https://github.com/cozy/cozy-client-js/blob/master/src/auth_v3.js) version, and we should get feature parity. Maybe.
I haven't written any code yet, but I'd like some feedback on the general plan.
Here are the things I'd like to keep from the public API — maybe renaming a few things in the process, we'll see:
- `registerClient`: well, registers a new OAuth client with the stack. Sends general information like client name, type, etc. This is required for the rest of the OAuth flow anyway
- `getClient` : gets the registered information from the stack for a given client. To be confirmed, but I think …
> OAuth support

- packages/cozy-stack-client/src/CozyStackClient.js
- packages/cozy-stack-client/src/DocumentCollection.js
- packages/cozy-stack-client/src/FileCollection.js
- packages/cozy-stack-client/src/PermissionCollection.js
- packages/cozy-stack-client/src/SharingCollection.js
- packages/cozy-stack-client/src/__tests__/SharingCollection.spec.js
This PR aims to support basic sharing features in Cozy apps. As the backend implementation is not complete right now (only files are fully supported for instance), this work shouldn't be considered as complete: there is still work to do, but we'll have to wait for the API to stabilize.
Regarding the changes:
- initially, I chose to put sharing by link code into the `DocumentCollection`, mainly because sharing by link uses some special kind of permissions documents. After discussing the matter with @y-lohse, we decided it was better to implement this in a specific `PermissionCollection`.
- sharing documents are some kind of a special beast too, therefore they needed their own `SharingCollection`.
- I added some tests, but clearly we need more.
> Support cozy-to-cozy files sharing

- packages/cozy-stack-client/package.json
- packages/cozy-stack-client/src/FileCollection.js
- yarn.lock
When trying to upload a directory in Firefox, there is a bug that prevents to get the directory files' mimetypes. Consequently, it's necessary to try to guess the mimetype from the extension so that files are not uploaded with a `application/octet-stream` mimetype. I chose to use a rather simple and light lib to do that.
> Added lib to detect file mimetypes from the extension

- packages/cozy-stack-client/src/SharingCollection.js
- packages/cozy-stack-client/src/__tests__/SharingCollection.spec.js
An 'one-way' sharing should use 'push' rules for a folder, and a sharing
for a single item should be revoked when this item is deleted.
> Fix sharing policy

- packages/cozy-stack-client/src/PermissionCollection.js
We already have the `destroy` method on the `PermissionCollection`, but we want to have a simple method for revoking a document's sharing link just by passing the document as arg.
> Added a method to revoke a document sharing link

- packages/cozy-stack-client/src/OAuthClient.js
I couldn't reproduce the initial problem so I don't have many details, but it appears `URLSearchParams.toString()` sometimes returns `[Object object]` — at least recently. Using a plain object seems to solve the problem.
> fix: generate query string without URLSearchParams

- packages/cozy-stack-client/src/OAuthClient.js
Mixed in with the oauth options, the `onTokenRefresh ` callback was occasionally getting eaten up.
> feat: Move token refresh callback to a separate option

- .travis.yml
- lerna.json
Adresses #20 .
Warning — this is experimental as fuck.
If everything goes according to plan, travis will generate a `.npmrc` file containing a token that lerna will use to publish to npm. This should happen on git tags only and the git tag will be used as version number.
The main problem that I don't know how to fix just yet is that the new version number won't be commited. The real version number will be in the git tags, and we should try to keep the code up to date.
If this PR works as intended, I'll try to work out a solution to that. Maybe semantic release or something like that.
> chore: Auto release using travis

- packages/cozy-stack-client/src/AppCollection.js
- packages/cozy-stack-client/src/CozyStackClient.js
As apps are retrieved with a specific endpoint, they need a custom implementation into an AppCollection class.
At this time, the only method needed is `all()`
> Add AppCollection

- README.md
The second parameter passed to the children callback of `Query` is an object containing all the mutations.
> fix: mutation example

- docs/dev.md
- lerna.json
- packages/cozy-client/package.json
* add prepublish script in cozy-client not to publish package without the `dist` folder
* switch to npm as yarn does not ask the login when publishing
* added doc in `docs/dev.md` as a reference for manual publication
> chore: publish improvements

- lerna.json
- packages/cozy-client/package.json
- packages/cozy-client/src/store/queries.js
When receiving a document, touch all the queries containing this
document.
Partially addresses https://github.com/cozy/cozy-client/issues/55
> feat: autoupdate queries when receiving document

- .babelrc
It was previously for node only and it can breaks some webpack build.
We can remove "react" here since it's handled by default in [`babel-preset-cozy-app`](https://github.com/CPatchane/create-cozy-app/tree/master/packages/babel-preset-cozy-app#react-boolean-true-by-default) for browsers.
> Use babel preset for browsers

- .babelrc
- package.json
- yarn.lock
It is breaking CSPs with cozy-client, the new version of the preset has an option to disable this plugin.
We will see in the future how things will happen.
> Disable regenerator transform in babel preset

- packages/cozy-stack-client/src/AppCollection.js
- packages/cozy-stack-client/src/CozyStackClient.js
- packages/cozy-stack-client/src/__tests__/AppCollection.spec.js
In #41 I added AppCollection but it was a little bit too soon, because it appeared later that it was not working as expected in Collect.
So there is a fix, before merging I wish to:
> Fix AppCollection

- packages/cozy-client/src/Query.jsx
No need to bind in render, this can be done in the constructor.
> perf: do not bind functions inside render

- README.md
`chain` is automatic with cozy-client when `link` are an array.
```
if (Array.isArray(this.link)) {
this.link = chain(this.link)
}
```
You can see [here](https://github.com/cozy/cozy-client/blob/6c93bc715e01f7373a7539dcf4d0dd9c8c4913f3/packages/cozy-client/src/CozyClient.js#L26-L28)
See https://github.com/cozy/cozy-client/pull/82
> docs: Fix link chain usage 🐛

- .travis.yml
- docs/dev.md
- lerna.json
- package.json
- packages/cozy-client/package.json
- yarn.lock
Following the example at https://github.com/cozy/cozy-libs, this PR
implements autopublish on npm with conventional commits.
- `commitlint` is used on `git commit` (using `husky`)
- when `lerna` publishes, it uses the conventional commits convention
to find out the type of release for each package
- the `CHANGELOG.md` for each package is updated
- On travis, `lerna` publishes on `npm`, adds the `git` tags, updates the `CHANGELOG.md`s, and commits under the username `cozy-bot`
Great blog post explaining the whole process: https://michaljanaszek.com/blog/lerna-conventional-commits
> chore: autopublish

- packages/cozy-client/src/ObservableQuery.js
- packages/cozy-client/src/Query.jsx
- packages/cozy-client/src/__tests__/ObservableQuery.spec.js
- packages/cozy-client/src/__tests__/store.spec.js
- packages/cozy-client/src/store/documents.js
- packages/cozy-client/src/store/queries.js
BREAKING CHANGE: before applications had to select the first item of the
results themselves, now it is done in the library
```diff
<Query query={client.get('doctype', 'id')}>
-  { ({ data: documents }) => {
-     const myDoc = documents[0]
+  { ({ data: myDoc }) => {
...
}}
/>
```
> fix: client.get query will return only 1 result

- bin/build
- package.json
- packages/cozy-client/package.json
- packages/cozy-pouch-link/package.json
- packages/cozy-stack-client/package.json
- yarn.lock
Since cozy-client is a library and will be used by applications
primarily using a bundler (like webpack), it is not useful to bundle
it before shipping it to npm. It has several drawbacks :
- libraries like lodash will be included twice in the final app bundle (one
for cozy-client, one for the app)
- tree shaking cannot be done
- increased compilation time
Only transpiling has the best of both worlds:
- we can use new es6 features like async/await
- compilation times are reduced since we only need to convert es6 to es5 instead
of resolving dependencies and including them
- shipped code is much smaller
fix #86
> chore: transpilation instead of bundling

- packages/cozy-client/src/StackLink.js
J'ai vu que l'on avait un paramètre `schema` dans `StackLink` alors que l'on ne passait pas le paramètre dans [l'initialisation de Cozy client](https://github.com/cozy/cozy-client/blob/6c93bc715e01f7373a7539dcf4d0dd9c8c4913f3/packages/cozy-client/src/CozyClient.js#L25). Après en avoir discuté avec @ptbrowne nous pensons que c'est un paramètre inutil dans StackLink.
> refactor: Remove unnecessary parameter 🔥

- bin/build
This script is used by the watch command "bin/build --watch". To work, it needs to forward the arguments.
> fix: Watch command 🐛

- README.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/StackLink.js
- packages/cozy-client/src/__tests__/CozyClient.spec.js
- packages/cozy-client/src/__tests__/StackLink.spec.js
- packages/cozy-pouch-link/__tests__/CozyPouchLink.spec.js
- packages/cozy-pouch-link/src/CozyPouchLink.js
Nous continuons notre travail pour intégrer `cozy-client` dans Cozy Banks et lors de l'implémentation du link `pouch` nous avons pensé à une simplification pour l'instanciation du client. Il est possible maintenant d'instancier des Link sans créer de client.
Avant:
```js
import CozyStackClient from 'cozy-stack-client'
import CozyClient, { StackLink } from 'cozy-client'
import PouchLink from 'cozy-pouch-link'
const stackClient = new CozyStackClient({ uri, token })
const stackLink = new StackLink({ client: stackClient })
const pouchLink = new PouchLink({ client: stackClient, doctypes: [...] })
const client = new CozyClient({ client: stackClient, links: [stackLink, pouchLink] })
```
Après:
```js
import CozyClient, { StackLink } from 'cozy-client'
import PouchLink from 'cozy-pouch-link'
const …
```
> feat: Remove client on Link initialisation 🔥 

- packages/cozy-client/src/Query.jsx
When not using `cache-only`, queries would en up being created twice — once through the call to `client.watchQuery`, and once through the actual call to `client.query`.
I've also moved the Query test file in the same folder as the other tests.
This would lead to infinite loading on the apps.
> Fix double query

- packages/cozy-stack-client/src/DocumentCollection.js
- packages/cozy-stack-client/src/__tests__/DocumentCollection.spec.js
Mango queries can't have opposing sorting orders (ie. one field `asc` and the other `desc`). But we had a default value of `desc`, so sorting by `asc` was impossible.
> fix: Use only one sorting order

- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/__tests__/CozyClient.spec.js
If watchQuery was called before the execution of the query, the store
was not created yet.
> fix: watchQuery calls getOrCreate store to ensure it has a store

- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/ObservableQuery.js
- packages/cozy-client/src/Provider.js
Provider or ObservableQuery should not create the store. I try to reduce the number of places the store can be created so that it is obvious.
* For now, `query`, `watchQuery` and `mutate` can create a store if it does not exist
* the user can setStore manually, maybe we should throw if the store has already been created by `query` or `watchQuery` ?
* the provider sets the store of the client when mounted.
> refactor: getOrCreateStore no longer called by Provider or ObservableQuery

- docs/guide.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/StackLink.js
- packages/cozy-client/src/__tests__/CozyClient.spec.js
- packages/cozy-client/src/__tests__/StackLink.spec.js
- packages/cozy-pouch-link/src/CozyPouchLink.js
- packages/cozy-pouch-link/src/CozyPouchLink.spec.js
- packages/cozy-stack-client/src/OAuthClient.js
- packages/cozy-stack-client/src/__tests__/OAuthClient.spec.js
When a user logout, we would like remove all references on this instance and
remove all user data. You can just use `cozyClient.logout()`.
This function make 3 actions:
- Delete OAuth Client on stack
- Remove pouch databases
- Remove all references on client
> Add logout function 👋

- packages/cozy-pouch-link/src/CozyPouchLink.js
- packages/cozy-pouch-link/src/helpers.js
- packages/cozy-pouch-link/src/helpers.spec.js
Acutellement on peut se retrouver avec des documents de design de pouchDB dans nos collections:
```
client.all(GROUP_DOCTYPE)
```
me retourne un document avec l'id `_design/...`
Le but de cette PR est de filtrer le retour de pouch pour supprimer ses documents inutils.
> feat: Remove design document on response 🤪

- packages/cozy-pouch-link/src/CozyPouchLink.js
The replication was resolving with undefined value because we didn't pass the result of the replication to the `resolve` function.
> [cozy-pouch-link] fix(pouch): Resolve with result after replication

- packages/cozy-client/src/CozyClient.js
Add a `login` method that is the opposite of `logout`: it (re)initializes things. Actually for now it is a public interface to `registerClientOnLinks`, which have an internal purpose.
I also refactored a little the links initialization.
> Add login method on client

- packages/cozy-client/src/authentication/mobile.js
- packages/cozy-stack-client/src/OAuthClient.js
- packages/cozy-stack-client/src/__tests__/OAuthClient.spec.js
This reverts commit 5d5ab5642d2e0c4b7eccea4443fa66015ccd121d.
This is related to https://github.com/cozy/cozy-client/issues/126
> Revert "fix: Use the right param for code in OAuth flow"

- docs/api.md
- packages/cozy-stack-client/src/FileCollection.js
- packages/cozy-stack-client/src/FileCollection.spec.js
- packages/cozy-stack-client/src/__snapshots__/FileCollection.spec.js.snap
`datetime` accidentally became `date` in a previous change.
> Fix datetime

- packages/cozy-pouch-link/src/CozyPouchLink.js
If the databases were already destroyed, this throws an error.
> feat(pouch): Handle errors for pouches destroy

- packages/cozy-stack-client/src/OAuthClient.js
When we do a PUT on `/auth/register/:clientID`, the stack don't return all the fields that were sent. So we need to merge the current data with what the stack returns. Otherwise there's a potential loss of data. For example on banks, we lost the `registrationAccessToken` key.
> fix(oauth): Don't forget data in updateInformation

- packages/cozy-client/src/CozyClient.js
I think this `console.log` was pushed by mistake.
> [client] Remove a forgotten console.log

- packages/cozy-stack-client/src/DocumentCollection.js
- packages/cozy-stack-client/src/__tests__/DocumentCollection.spec.js
- packages/cozy-stack-client/src/querystring.js
The ability to provide this `keys` option was broken by [this commit](https://github.com/cozy/cozy-client/commit/a7d414371d982c424409f4081d2d441fffdb35fa)
> Restored keys option for DocumentCollection.all()

- packages/cozy-pouch-link/src/CozyPouchLink.js
- packages/cozy-pouch-link/src/CozyPouchLink.spec.js
Not resetting `this.sync` was making `PouchLink` intercept all the requests even if it has been resetted and thus can't return anything.
> fix(pouch): Set sync to false on reset

- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
- packages/cozy-client/src/associations/HasManyAssociation.js
- packages/cozy-client/src/associations/HasManyUNSAFEAssociation.js
- packages/cozy-client/src/associations/helpers.js
- packages/cozy-client/src/associations/index.js
When trying to save documents that had relationships, the relationships object was saved
to the database. The document is now dehydrated before being sent.
> Dehydrate relationships before saving

- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
When using PouchLink replication, we need something to pass the result of the replication to the client. The idea is to provide a `setData` method that we can call when the pouch synced successfuly. The link passes the data synced during the replication process to `setData` and the internal store is updated accordingly.
> feat(client): Add setData method

- packages/cozy-pouch-link/examples/periodic-sync/index.js
- packages/cozy-pouch-link/src/CozyPouchLink.js
- packages/cozy-pouch-link/src/PouchManager.js
- packages/cozy-pouch-link/src/PouchManager.spec.js
- packages/cozy-pouch-link/src/__tests__/mocks.js
To be able to efficiently update the store with documents from
a replication, it is necessary to call onSync with the documents
that have been updated during the replication.
The 'change' event from pouch allows access to these documents.
They are accumulated during the replication and given to the `onSync`
callback grouped by doctype.
The link then normalize them (add _type and id/_id) before handling them to a callback defined in its options.
> feat: PouchLink calls onSync with updated documents

- packages/cozy-pouch-link/src/PouchManager.js
- packages/cozy-pouch-link/src/PouchManager.spec.js
The PouchDB synchronization was only being done remote to local. Now it is done in two way.
> feat: Use two way replication

- packages/cozy-pouch-link/src/PouchManager.js
- packages/cozy-pouch-link/src/helpers.js
- packages/cozy-pouch-link/src/helpers.spec.js
The replication process gets design and deleted documents. We filter them so they are not stored in the cozy client's store
> fix: Filter design and deleted docs in replication

- packages/cozy-pouch-link/src/CozyPouchLink.js
- packages/cozy-pouch-link/src/CozyPouchLink.spec.js
We already destroy Pouch dbs when we reset the pouch link. But when we register a new client on it, we also re-create the databases. It happens that when we logout then login, we tried to destroy databases already destroyed, throwing an error. This error was catched and displayed without breaking everything. But there still was a problem with the replication after that.
> fix(pouch): Avoid to destroy dbs already destroyed

- packages/cozy-stack-client/src/OAuthClient.js
This property was not mapped in `camelCaseOAuthData`, but we need it to be present in `register`, otherwise we send `undefined` to the stack, and we receive an error telling us that the `redirect_uris` parameter is mandatory.
> fix(stack-client): Map redirect_uris to camelcase

- packages/cozy-stack-client/src/DocumentCollection.js
- packages/cozy-stack-client/src/__tests__/DocumentCollection.spec.js
We were throwing when there was no database for methods other
than all. Here we are more resilient for :
- find
- getAll
- get
> fix: Return sensible data when database not found

- packages/cozy-stack-client/src/SharingCollection.js
We need to pass the recipient index, because it's not impossible to have many recipients with the same email...
> Changed revokeRecipient() signature

- package.json
- packages/cozy-client/examples/relationships.js
- packages/cozy-pouch-link/package.json
- yarn.lock
- Pour `jest` j'ai supprimé la configuration spécifique dans `cozy-pouch-link` puisque nous utilisons la même configuration pour l'ensemble des packages [ici](https://github.com/cozy/cozy-client/pull/180/files#diff-2dca5911f1d49b374db19352d739520c)
- Pour `eslint` j'ai ajouté les sources des exemples dans le script qui n'étaient pas vérifiées [ici](https://github.com/cozy/cozy-client/pull/180/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R31)
> Upgrade dependencies

- packages/cozy-pouch-link/src/CozyPouchLink.js
- packages/cozy-pouch-link/src/PouchManager.js
When an application is offline you must be able to query Pouch
A limitation has been put in place to avoid launching replications when device are in offline mode
> Fix offline on pouch link

- packages/cozy-stack-client/src/FileCollection.js
Some file types will be opened by the browser directly, even with a `download` attribute in the link — unless the server sends the correct header. Adding `Dl=1` does just that.
> fix: Really force file download

- docs/guide.md
- docs/how-to/existing-store.md
- docs/how-to/hoc.md
- docs/how-to/link-custom.md
- docs/how-to/oauth.md
- docs/link-design.md
Takes out some parts of the main guide and puts them in secondary guides.
The part about links will need some rewording, and we have to add links to the various How-to's. I think both can be done in subsequent PRs.
> Split parts of the docs

- packages/cozy-client/src/withMutations.jsx
Without this part, the HOC can get the client from context (the context is empty)
Fix #200
> Fix withMutations context issue

- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/Schema.js
Some stuff we missed in  #158.
The first commit is just a typo, but the second one is more important — to validate the uniqueness of an attribute, the `Schema` class needs a client. Not a CozyClient (so we still keep the separation we wanted), but one of the underlying clients (`StackClient` for example).
I don't like my fix too much because it doesn't remove the existing coupling between the 2 classes, but hopefully we can come up with something better next time.
> Schema class fixes

- packages/cozy-client/src/store/queries.js
Using `withMutations`, the method `deleteDocument()` was not working correctly, it does remove from the database but it was not removed from the app state.
I don't know if this is the good way to do that or if this is the good place to check that but it does the job. What do you think @drazik or @y-lohse?
Fix #201
> Fix destroy update

- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
- packages/cozy-client/src/Query.spec.jsx
- packages/cozy-client/src/__tests__/fixtures.js
- packages/cozy-client/src/__tests__/store.spec.js
- packages/cozy-client/src/store/index.js
- packages/cozy-client/src/store/mutations.js
- packages/cozy-client/src/store/queries.js
Before the fix, when receiving an `RECEIVE_MUTATION_RESULT` action concerning a reference, `Queries` concerned were not updated. 
To update those queries, we : 
- had add the `mutation definition` to `RECEIVE_MUTATION_RESULT`
- edit `autoQueryUpdater` to check `response.data` or `definition.document` as `response` was empty in that case.
> fix: Update queries when references are mutated

- packages/cozy-client/src/__tests__/store.spec.js
- packages/cozy-client/src/store/documents.js
- packages/cozy-client/src/store/index.js
- packages/cozy-client/src/store/queries.js
This PR has no content for now, I'm just going to explain what the problem is.
One very common use case we have is displaying lists of things — bank transactions, files, contacts, whatever. Doing this with the `Query` API is quite easy:
```
const query = client => client.find('io.cozy.todos')
const TodoList = () => (
<Query query={query}>
{({ data }) =>
<ul>{data.map(todo => <Todo data={todo} />)}</ul>
}
</Query>
```
One problem with this is that if any of the documents change in the store, we re-render the whole list. This happens if we actually alter the document, for example by changing the label — but it also happens if we simply re-fetch the document, because in that case we blindly override the one in the store without checking for actual differences (to be confirmed).
To mitigate …
> Granular access to query results

- packages/cozy-stack-client/src/DocumentCollection.js
- packages/cozy-stack-client/src/DocumentCollection.spec.js
Until now, sorting options where passed as a single object, like `{ zebras: 'asc', abyssinian: 'asc' }`. The problem is that the order of the sort usually matters, but with an object the order of keys is not guaranteed. Typically the example above would end up sorting on `abyssinian` first and `zebra` second.
The new format is the same as what mango expects: `[{ zebras: 'asc' }, { 'abyssinian': 'asc' }]`. 
The old format is *still* supported, although you'll get a deprecation warning. 
The breaking change comes from the usage of selectors combined with sorting order. A query with `{ selector: { done: true }, sort: { name: 'asc' } }` would previously resolve to a sorting order of `[{ done: 'asc' }, { name: 'asc' }]`, but now it becomes `[{ name: 'asc' }, { done: 'asc' }]`. This is …
> Breaking change: Respecting the sort order

- packages/cozy-client/src/__tests__/store.spec.js
- packages/cozy-client/src/store/documents.js
I found a problem with the previous fix that avoid useless documents updates: there are cases where we can get partial documents from the stack, so for example the first fetch will give `{ _id: 1, rev: 1, label: 'plop' }` and the second one will give `{ _id: 1, rev: 1, label: 'plop', done: true }`… same `rev`, same document, different content.
I think those are edge cases, but in order to solve them we need to *really* compare the 2 documents.
> fix: Deep compare documents updates

- packages/cozy-stack-client/src/FileCollection.js
- packages/cozy-stack-client/src/FileCollection.spec.js
Responses to the `/relationships/references` don't have a `rows` attribute, but they have a `next` property in the `links` when there is more content, as per the JSONAPi spec.
> fix(ReferencedFiles): Properly detect next pages

- packages/cozy-pouch-link/examples/periodic-sync/index.js
We found out that allDocs was slow, we could have known that earlier on
if we had this information in an example.
> feat: Add elapsed time

- packages/cozy-pouch-link/src/PouchManager.js
- packages/cozy-pouch-link/src/promises.js
We had an issue because the promise was not returned. It means that the replication loop was not waiting for the current iteration to be finished before triggering the next one.
Now, the behavior is the one intended: when we start the loop, the first replication is done, then we wait for a delay (30 seconds by default), then the second replication is done, and so on.
> fix(pouch): Wait end of replication before triggering another one

- packages/cozy-pouch-link/src/promises.js
- packages/cozy-pouch-link/src/promises.spec.js
Long story short : promises and fakeTimers do not play well together.
https://stackoverflow.com/questions/46710564/testing-a-promise-using-settimeout-with-jest
jest.advanceTimersByTime does not advance timers that are created in Promises.
```js
Promise.resolve().then(() => setTimeout(fn, 100))
jest.advanceTimersByTime(100)
// fn is not called since setTimeout is executed after advanceTimersByTime ❌
```
```js
Promise.resolve().then(() => setTimeout(fn, 100))
Promise.resolve().then(() => jest.advanceTimersByTime(100))
// fn is called ✅
```
> test: Add test for setIntervalPromise

- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
- packages/cozy-client/src/associations/helpers.js
In https://github.com/cozy/cozy-client/commit/a9fa010ed15c8b3c28fab426e78a47059d71968b, relationships filling was broken : the relationships attribute was no longer filled at fetch time. This was particularly important for documents whose relationship data was "on the other side" of the relation.
For example, for photo albums, relationship data for the photos, is on the file side of the relationship and this is returned in the `referencedBy` queries. This data needs to be stored on the album side, in the `relationships` attribute, for it to be easily managed on the client.
> fix: Repair HasMany files relationships

- packages/cozy-pouch-link/src/CozyPouchLink.spec.js
- packages/cozy-pouch-link/src/jsonapi.js
- packages/cozy-pouch-link/src/jsonapi.spec.js
PouchDB sends .rev attribute on documents. To avoid conflicts, it is
necessary to replace the ._rev on the document (that is lower in case
of a change on the document done by PouchDB). To remove confusion, we
keep only the _rev in our store and in CouchDB.
> fix: Discard rev from PouchDB results

- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
- packages/cozy-client/src/StackLink.js
- packages/cozy-client/src/__tests__/StackLink.spec.js
- packages/cozy-pouch-link/src/CozyPouchLink.js
- packages/cozy-pouch-link/src/CozyPouchLink.spec.js
- packages/cozy-pouch-link/src/PouchManager.js
- packages/cozy-stack-client/src/AppCollection.js
- packages/cozy-stack-client/src/DocumentCollection.js
- packages/cozy-stack-client/src/FileCollection.js
- packages/cozy-stack-client/src/PermissionCollection.js
- packages/cozy-stack-client/src/SharingCollection.js
- packages/cozy-stack-client/src/__tests__/setup.js
This PR supersedes https://github.com/cozy/cozy-client/pull/247.
The goal of this PR was for a link to be able to inject data in the store of CozyClient. This is necessary for the PouchLink that receives data asynchronously after a synchronization.
Previously, in Banks, the onSync handler was used to manually `setData`.
https://github.com/cozy/cozy-banks/blob/697ac7f8bb328cbc7d83f34145b811f0c7d34831/src/ducks/client/mobile.js#L80
This was done as a temporary solution. Now, this solution is backported into CozyClient. The link receives a reference to the CozyClient at registration time, saves the reference, and call `setData` when it receives new data asynchronously.
The links already received a `StackClient` at registration time but it was wrongly named `client` which caused confusion …
> feat: Links receive CozyClient

- packages/cozy-pouch-link/src/CozyPouchLink.js
- packages/cozy-pouch-link/src/PouchManager.js
- packages/cozy-pouch-link/src/PouchManager.spec.js
You can instanciate CozyPouchLink with pouchPlugins and pouchOptions
Example:
```js
const cozyPouchLink = new CozyPouchLink({
doctypes: offlineDoctypes,
pouch: {
plugins: [require('pouchdb-adapter-cordova-sqlite')],
options: { adapter: 'cordova-sqlite', location: 'default' }
}
})
```
> feat: Add pouch parameters

- package.json
- packages/cozy-pouch-link/package.json
- packages/cozy-pouch-link/src/CozyPouchLink.js
- packages/cozy-pouch-link/src/CozyPouchLink.spec.js
- packages/cozy-pouch-link/src/PouchManager.js
- packages/cozy-pouch-link/src/PouchManager.spec.js
- yarn.lock
The synchronization status was managed globally (eg set to true when all the doctypes have been synchronized). This lead to issues where some doctypes already synchronized couldn't be returned from Pouch because other doctypes are still synchronizing.
Now, the status is managed for each doctype. So if transactions are synchronizing and accounts already synchronized and we query the accounts, they are fetched from Pouch.
> feat(pouch): Manage sync status by doctype

- packages/cozy-stack-client/src/FileCollection.js
- packages/cozy-stack-client/src/FileCollection.spec.js
`createDirectory` was called with a `dirID` but was expecting a `dirId`.
> fix: ID case typo

- packages/cozy-stack-client/src/FileCollection.js
- packages/cozy-stack-client/src/FileCollection.spec.js
The problem might be more pervasive than just the `FileCollection`, but at least there we didn't encode some strings in our urls.
> URl encode parameters in pathes

- packages/cozy-client/src/CozyClient.spec.js
- packages/cozy-client/src/CozyLink.js
- packages/cozy-client/src/CozyLink.spec.js
- packages/cozy-client/src/StackLink.js
- packages/cozy-client/src/__snapshots__/CozyLink.spec.js.snap
- packages/cozy-pouch-link/src/CozyPouchLink.js
I needed to make a change to the [`upload`](https://github.com/cozy/cozy-client/blob/custom-requests/packages/cozy-client/src/CozyClient.js#L235) mutation function, but after consideration, I think it shouldn't be there at all.
Mutations like create/read/update/delete make perfect sense, and even adding/removing references is ok, as those are common across doctypes. But some doctypes have special behaviors — files, apps, settings, etc. If we want to support all these behaviors, we will need a lot of custom functions in the main CozyClient, and we will have [to integrate every one of them in all our Links](https://github.com/cozy/cozy-client/blob/custom-requests/packages/cozy-client/src/StackLink.js#L69). I think this will make cozy-client bloated and it's maintenance complicated. So I …
> Custom requests

- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
- packages/cozy-pouch-link/src/CozyPouchLink.js
- packages/cozy-pouch-link/src/CozyPouchLink.spec.js
- packages/cozy-pouch-link/src/PouchManager.js
We destroy all pouch dbs when the user logouts. But it happens asynchronously and can take several seconds. So during this time, the user can kill the app, aborting this process.
To avoid data leak between instances, this PR introduce two things:
* The Pouch databases are now named after the instance they correspond to
* If we still have references to some databases and we login on another instance, we destroy them
> feat(pouch): Destroy databases when login on another instance

- packages/cozy-stack-client/src/DocumentCollection.js
- packages/cozy-stack-client/src/DocumentCollection.spec.js
I don't understand how this hasn't been found before, but I think I've double checked everything and this really appears to be a bug.
If there are 10 rows in total, and we have a skip of `0` and no limit, we will get 10 rows in the result. This will evaluate to `0 + 10 <= 10`, which is `true`… but of course there are no next pages.
> fix(DocCollection): Correct pagination limits

- docs/getting-started.md
- docs/how-tos.md
Now that the schema is required for each doctype accessed by cozy-client, an update to the docs was required.
> Docs on the schema

- packages/cozy-stack-client/src/DocumentCollection.js
- packages/cozy-stack-client/src/DocumentCollection.spec.js
When fetching all the documents of a certain type without any criteria, we were using the `_all_docs` route. This route also returns design documents, which we had to remove from the results and would mess up the pagination.
Instead, there's now a new route called `_normal_docs`, which doesn't take into account design docs - so we're using that one instead.
Unfortunately, it doesn't support the `keys` option and the response is slightly different than the `_all_docs` response, but these difference can be abstracted away.
> feat(DocCollection): Use _normal_docs route

- packages/cozy-pouch-link/src/PouchManager.js
- packages/cozy-pouch-link/src/PouchManager.spec.js
Currently when a device goes offline in the middle of a replication the replication ends with an error and never restart.
With this PR during online / offline events we stop and restart replication explicitly
> feat: Stop Start replication when device is online/offline

- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
In banks, we run `cozyClient.login()` several times without doing it on purpose, I think that cozyClient must know how to manage its login state.
> feat: Save state of login to not start replication twice

- packages/cozy-pouch-link/src/PouchManager.js
- packages/cozy-pouch-link/src/PouchManager.spec.js
This event is only on iOS when you open settings bottom bar.
Replication must not stop when it does.
https://cordova.apache.org/docs/en/latest/cordova/events/events.html
> feat: Remove resign cordova event

- packages/cozy-pouch-link/src/PouchManager.js
When the replication is restarted by an event, it sees as a parameter
an Event and not a delay which had a problem. This parameter is not
really neccesarry, we can pass by `this.options.replicationDelay`.
> fix: Loop replication witout delay

- packages/cozy-stack-client/src/DocumentCollection.js
- packages/cozy-stack-client/src/DocumentCollection.spec.js
There is a `UNSAFE_noLimit` method in cozy-client. It sets the `limit` to `null` on a query definition. The goal is to be able to fetch all documents of a collection at once. But `DocumentCollection::all` was not handling this case properly. It was making a request to `_normal_docs` route, which has a hard limit of 100 set by the stack.
This PR fixes this behaviour by making a request to `_all_docs` if `limit` is intentionnally `null` (keeping the previous behaviour if it is `undefined`, so not breaking). It also filters design docs, which are present only when using `_all_docs` route.
We talked about adding a `UNSAFE_all` previously. But I think this behaviour is intended to be right inside `all`.
> fix(DocumentCollection): Return all docs if limit is null

- packages/cozy-stack-client/src/DocumentCollection.js
- packages/cozy-stack-client/src/DocumentCollection.spec.js
2 things in this PR : 
- First: filtering only when needed (ie all_docs)
- Second: We don't know yet, but sometimes on Drive (sharing) we receive an "null doc". So we need to check if doc !== null
> fix(DocumentCollection): Check if the doc is not null

- packages/cozy-client/src/associations/HasMany.js
- packages/cozy-client/src/associations/HasMany.spec.js
When using the `include()` option on a `HasMany` relationship, we use `HasMany.query()` to get a QueryDefinition that allows us to fetch the related documents (for example the tasks related to a todo).
At least in our case, this was not working properly — when constructing the QueryDefinition, we would have an array of ids that was looking like `[{ _id: '123', _type: 'io.cozy.tasks' }]`, instead of a plain `['123']` as we need to execute the query.
Note that we were also looking at `myTodo.tasks` instead of `myTodo.relationships.tasks.data` which iI think is odd too.
Was anyone else using `HasMany` relationships with includes? Or are we just the first to find this bug?
> Has many query

- packages/cozy-client/src/CozyClient.js
When using a mobile app, it can happen that a user wants to logout while being offline. In that case, cozy-client would fail in the middle of the `logout` method because the call to the stack to unregister the client would fail. The method crashes, preventing the links to `logout` themselves. I think we should handle it directly in cozy-client.
Here, I just catch the error and log it. The drawback of this is that the client will never be unregistered and will remain on Settings' sessions page.
> feat(client): Handle stack client unregister error

- docs/getting-started.md
- packages/cozy-client/src/Query.jsx
- packages/cozy-client/src/Query.spec.jsx
It seems that the client parameter was missing and that the code and behaviour were not consistent with the documentation.
> Fix Query's mutations prop

- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
- packages/cozy-client/src/__tests__/fixtures.js
- packages/cozy-stack-client/src/DocumentCollection.js
- packages/cozy-stack-client/src/__tests__/CozyStackClient.spec.js
Needed to create an agregator account. Agregator account is a single account used by several konnectors to connect on a remote API. An agregator accounts must be created with a fixed `_id`. Example : Budget Insight.
This PR :
* Now rely on _rev existence to determine if the action is an update or a creation
* Call the expected endpoint when created document has fixed _id attribute
__BREAKING CHANGE:__ To be updated, documents now requires a `_rev` attribute.
> Create with fixed id

- packages/cozy-stack-client/src/PermissionCollection.js
Trailing slash was causing a 404 error
> Permissions POST endpoint

- packages/cozy-client/src/store/__snapshots__/queries.spec.js.snap
- packages/cozy-client/src/store/queries.js
- packages/cozy-client/src/store/queries.spec.js
So far, we only use the `selector` field of the DSL to compare results with queries, but there are other fields that can contain filtering information, such as `id`, `ids`, `referenced`, and possibly more.
I think some bigger changes are needed in the DSL, but in the meantime this PR fixes the problem for queries with an `id` field.
> Queries with id selector

- packages/cozy-stack-client/src/PermissionCollection.js
- packages/cozy-stack-client/src/PermissionCollection.spec.js
The add method allows to add a permission for a given permissions document, app or konnector.
This method tests the type of the first parameter and call the related endpoint.
It throws an error if this type is unexpected.
Needed in https://github.com/cozy/cozy-home/pull/1041.
> Add add() method to PermissionCollection

- packages/cozy-stack-client/src/DocumentCollection.js
- packages/cozy-stack-client/src/DocumentCollection.spec.js
If we use the `keys` option on the `_all_docs` route and specify an invalid key, the row has an `error` field but no `id` or `doc`. This caused the normalisation function to crash.
> fix: Guard against rows containing errors

- docs/how-tos.md
There was no docs about `queryConnect`. The goal is to show how to use it with its simple form, and its props-based form.
This closes #314.
> docs: Add how-to about queryConnect

- packages/cozy-client/package.json
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/__tests__/associations.spec.js
- packages/cozy-client/src/associations/Association.js
- packages/cozy-client/src/associations/HasMany.js
- packages/cozy-client/src/associations/HasManyFiles.js
- packages/cozy-client/src/store/index.js
- yarn.lock
Right now, if I have a query like `client.get('io.cozy.todos', myTodoId).includes('files')`, we will load the first 100 associated files. There will be a `fetchMore` method exposed and if we call it, the store will be properly updated BUT the Query will not be re-rendered.
It took me a while to figure out why so let me explain:
1. [Calling `fetchMore`](https://github.com/cozy/cozy-client/blob/assoc-pagination/packages/cozy-client/src/associations/HasManyFiles.js#L5) will start a new query
2. Eventually we dispatch a `RECEIVE_QUERY_RESULT` which goes [through the main reducer](https://github.com/cozy/cozy-client/blob/master/packages/cozy-client/src/store/index.js#L60)
3. The action response contains the new *files*, but we still need to update the parent *todo*. 
4. To do this, we call the …
> Association pagination

- packages/cozy-pouch-link/src/PouchManager.js
- packages/cozy-pouch-link/src/PouchManager.spec.js
When we destroy localStorage we should remove `syncedDoctypes` data also
> fix: Clean syncedDoctypes

- packages/cozy-client/src/associations/HasMany.js
- packages/cozy-client/src/associations/HasMany.spec.js
Most relationships in cozy-client look like this:
```
relationships: {
tasks: {
data: {…}
}
}
```
But some have an extra `meta.count` field:
```
relationships: {
tasks: {
data: {…},
meta: { count: 5 }
}
}
```
In #328, we deprecated `HasManyFiles.add` and `HasManyFiles.remove`, replacing them with the more generic `HasManyFiles.addById`. But the deprecated functions were also updating the `meta.count` field, so this PR adds this behavior to  `addById` and `removeById`
> fix: Update relationship meta count

- packages/cozy-client/package.json
- yarn.lock
Upgrade cozy-device-helper to fix missing dependency to `@babel/runtime`
Fixes https://github.com/cozy/cozy-libs/issues/246
> chore(deps): Update dependency cozy-device-helper to 1.6.3

- packages/cozy-client/src/StackLink.js
- packages/cozy-client/src/__tests__/StackLink.spec.js
Before this change : 
```
const query = query.all(DOCTYPE).sortBy([{name: 'asc'}])
``` 
used the `_normal_docs` route and no use my sort option. And if we wanted to have a sortBy, we had to add a selector : 
```
const query = query.all(DOCTYPE).where({ _id: { $gt: null } }).sortBy([{name: 'asc'}])
``` 
Now, if a sort option is given (even without a selector) we will use the `find` route and the sortBy argument.
> feat(StackLink): Use find instead of all if a sort option is given

- packages/cozy-client/src/associations/helpers.js
- packages/cozy-client/src/store/documents.js
- packages/cozy-client/src/store/documents.spec.js
This is an alternative solution to #337 — we make sure the `relationships` attribute is kept in documents in the redux store when they are updated.
> fix: HasManyFiles relationships

- packages/cozy-client/src/associations/helpers.js
We were trying to apply `Object.keys` on something that could be undefined. I just added a check to avoid a `can't convert undefined to object` error.
> fix(client): Handle undefined relationships

- packages/cozy-client/src/associations/helpers.js
- packages/cozy-client/src/associations/helpers.spec.js
When a `query` uses `includes(['some_relationship'])`, we will fetch the included data and inject it into the main response. This is especially useful for `HasManyFiles` relationships where the main document doesn't contain the relationship info.
But we also have to be careful not to destroy any existing data in the `relationships` field.
This PR makes sure we don't accidentally override some relationship data, and adds tests for all situations I know of.
> Attaching relationships to objects

- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
Get documents from state can return null documents when queries contain references to documents that are absent and/or have not been fetched yet
> fix: Hydrating null documents failed

- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
- packages/cozy-client/src/associations/HasOneInPlace.js
- packages/cozy-client/src/associations/helpers.js
- packages/cozy-client/src/helpers.js
- packages/cozy-client/src/helpers.spec.js
- Added `dehydrate` method for HasOne
Without dehydrate method, the association was left
as is during dehydratation and during JSON serialization (while saving),
the value disappeared since the Association class
has no toJSON method.
- Throw if a relation is not dehydratable
This will prevent the `save` if a document has a relationship that is not dehydratable.
- Be more lenient when using `getDocumentFromState`
Since we have the bug in production, some documents were left without the id inside the relationship attribute (precisely, bank operations were left without their `account` attribute containing the id of the account they belong to). This led to a white screen since `getDocumentFromState` throws heavily when trying to access a document without id. With this change, …
> Dehydratation has one

- packages/cozy-client/src/__tests__/associations.spec.js
- packages/cozy-client/src/associations/HasMany.js
- packages/cozy-client/src/associations/HasMany.spec.js
- packages/cozy-client/src/associations/HasManyFiles.js
This is a breaking change as we are removing deprecated APIs.
> feat: Auto-save addById / removeById

- packages/cozy-client/src/withMutations.jsx
- packages/cozy-client/src/withMutations.spec.jsx
Useful for passing mutations from different modules.
> Allow multiple mutations as parameters for withMutations()

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/CozyStackClient.js
- packages/cozy-stack-client/src/getIconURL.js
- packages/cozy-stack-client/src/getIconURL.spec.js
- packages/cozy-stack-client/src/memoize.js
- packages/cozy-stack-client/src/memoize.spec.js
- Get icon content (need to XHR to send cookies on mobile)
- Return URL with URL.createObjectURL
If icon type cannot be determined or is not available (ios10), the app manifest is downloaded and the mime type is determined from the icon filename.
```
stackClient.getIcon({ type: 'konnector', slug: 'caissedepargne1' })
stackClient.getIcon({ type: 'app', slug: 'drive' })
stackClient.getIcon({ type: 'app', slug: 'drive', priority: 'registry' })
```
> feat: getIcon from stack or registry for apps and konnectors

- packages/cozy-stack-client/src/CozyStackClient.js
- packages/cozy-stack-client/src/getIconURL.js
- packages/cozy-stack-client/src/getIconURL.spec.js
- Passing options to fetch was unnecessary and actually led to a bug since the credentials options of stackClient::fetch is supposed to be the Authorization header
- Options object is modified during the fetch, this is why it is copied
> Fix stackClient:getIcon

- packages/cozy-pouch-link/src/CozyPouchLink.spec.js
The broken build of #365 reveals that the schema we provide to cozy client is broken in `CozyPouchLink.spec.js`.
Before this change, schema is equal to:
```
{ todos: { '0': 'i',
'1': 'o',
'2': '.',
'3': 'c',
'4': 'o',
'5': 'z',
'6': 'y',
'7': '.',
'8': 't',
'9': 'o',
'10': 'd',
'11': 'o',
'12': 's' } }
```
After the change:
```
{ todos: { doctype: 'io.cozy.todos' } } }
```
> test: Fix schema in CozyPouchLink tests

- packages/cozy-stack-client/src/getIconURL.js
- packages/cozy-stack-client/src/getIconURL.spec.js
Fix the app data fetching part of getIcon.
- Registry format is { latest_version: { manifest: { icon }}}
- App/konnector format is { data: { attributes: { icon }}}
> fix: Registry and app routes have different resp fmts

- docs/how-tos.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
- packages/cozy-client/src/__tests__/fixtures.js
- packages/cozy-client/src/__tests__/mockDate.js
- packages/cozy-pouch-link/src/CozyPouchLink.spec.js
Implements #363 — automatically inserting and updating `cozyMetadata`. I will add the relevant documentation after the first round of review.
Basically: if the app provides a `cozyMetadata` object in the schema, the keys will be added / updated to the documents. The schema also contains the values to use and when to update the various metadata fields.
> Automatic metadata

- packages/cozy-client/package.json
- packages/cozy-client/src/store/__snapshots__/queries.spec.js.snap
- packages/cozy-client/src/store/queries.js
- packages/cozy-client/src/store/queries.spec.js
- yarn.lock
Ok, so:
- A common practice when working with couchdb is to include a `{ $gt: null }` selector — telling couch to use that field as an index, but not using it as a real filter, since almost any value passes the `{ $gt: null }` filter. We do this every now and then in our queries and [it's all over their docs](http://docs.couchdb.org/en/latest/api/database/find.html#find-selectors).
- When documents in the cozy-client store change, we run the updated documents against the selectors of the `queries` to know which ones to update.
- We use [sift.js](https://github.com/crcn/sift.js) to run the selectors, but contrary to couchdb, sift returns no documents when using `{ $gt: null }` .
- Sift is mirroring mongodb behaviour, so it's not a bug on their side. [It might be a bug in …
> fix: Support $gt null in query selectors

- packages/cozy-client/src/CozyClient.spec.js
- packages/cozy-client/src/__tests__/fixtures.js
Remove `importedAt` and `importedFrom` from test `SCHEMA` to match the "real" `cozyMetadata` structure : https://github.com/cozy/cozy-doctypes/commit/1e60c8558b24be3ed3218d20c4414c1db81bd8b4
> Remove importedAt and importedFrom from fixture/tests

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/CozyStackClient.js
- packages/cozy-stack-client/src/OAuthClient.js
- packages/cozy-stack-client/src/__tests__/OAuthClient.spec.js
With the new onboarding process (with deeplink, access_code and state), we're not using "standard OAuth" since the client (aka our app) is not registering the OAuth Client anymore. This work is done by the stack. 
In order to manage the logout process correctly with this new onboarding, we have to reset manually the OAuth Client. 
We can do that manually in each app, or we can provide a small method in CozyClient.
> feat(OAuthClient): Add resetClient

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/package.json
- packages/cozy-stack-client/src/DocumentCollection.js
- packages/cozy-stack-client/src/DocumentCollection.spec.js
- yarn.lock
fetchChanges are not flexible and impose to download docs
With this commit we don't make breaking change and function
are more flexible
Change request when doc_ids parameter is used. Since length of URL is limited, it is better to use POST /{db}/_changes instead.
Documentation links:
- [Couch documentation](https://kutt.it/5r7MNQ)
- [Stack changes source](https://git.io/fhoLW)
- [Couch documentation POST](https://kutt.it/se1oRF)
> feat: Update changes route to match all couch parameters

- docs/api/cozy-stack-client.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-stack-client/src/CozyStackClient.js
- packages/cozy-stack-client/src/OAuthClient.js
- packages/cozy-stack-client/src/__tests__/OAuthClient.spec.js
- packages/cozy-stack-client/src/__tests__/__snapshots__/OAuthClient.spec.js.snap
- packages/cozy-stack-client/src/logDeprecate.js
Fix #368
- Deprecate CozyStackClient::setCredentials in favor of setToken
- Deprecate CozyStackClient::getCredentials in favor of getToken
- Put credentials='include' as `fetch` option even if the Authorization header
is not set.
- Override the default Authorization header via headers.Authorization
> feat: Saner internal API for stackClient/OAuthClient

- docs/api/cozy-client.md
- docs/how-tos.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
- packages/cozy-client/src/__tests__/fixtures.js
- don't use client.schema to add/update cozyMetadata. Metadata are updated directly in `ensureCozyMetadata` using `client.metadata` for data that have to be passed by the app
- new format for updatedByApps (see https://github.com/cozy/cozy-libs/pull/302 )
I still need to update the docs.
> feat: Don't use client.schema to add/update cozyMetadata, 

- packages/cozy-client/src/Query.jsx
Remove logs since too much logs distracts and hides important logs
In my mind, we should be able to selectively view logs from a
part of the app. Every library should namespace its logs and we
should be able to say "I want to see logs from cozy-client".
> chore: Remove log when query re-renders

- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
Add `metadataVersion` to `cozyMetadata` to match the structure defined in https://github.com/cozy/cozy-doctypes/pull/79
> Add metadata version

- packages/cozy-stack-client/src/AppCollection.js
- packages/cozy-stack-client/src/CozyStackClient.js
- packages/cozy-stack-client/src/KonnectorCollection.js
- packages/cozy-stack-client/src/__tests__/AppCollection.spec.js
- packages/cozy-stack-client/src/__tests__/CozyStackClient.spec.js
- packages/cozy-stack-client/src/__tests__/KonnectorCollection.spec.js
- packages/cozy-stack-client/src/__tests__/fixtures/apps.json
- packages/cozy-stack-client/src/__tests__/fixtures/konnectors.json
Prepare the future implementation for konnector endpoints.
For now it allow developers to user `stackClient.konnectors.all()` to fetch all konnectors.
It keeps `stackClient.collection('io.cozy.konnetors').all()` plugged to regular `DocumentCollection` to not introduce regression in Cozy-Banks. See https://github.com/cozy/cozy-banks/commit/a7c8ac3823d18300bd3d2ef09c57795fc48d47f3#diff-872b51c7bdb364ada730166a867a9d38R90
Related to https://github.com/cozy/cozy-client/issues/374
> StackClient: Add Konnector Collection basis

- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/__tests__/store.spec.js
- packages/cozy-client/src/store/documents.js
- packages/cozy-client/src/store/index.js
Goal: easily get all the fetched triggers.
`AddCollectionFromState()` allows to retrieve all document for a given doctype existing in CozyClient redux state.
Example:
```
await client.query(client.all('io.cozy.accounts').where(auth: '$exists'))
const accounts = client.getCollectionFromState('io.cozy.accounts')
```
It's the "get list" alternative of existing method `getDocumentFromState()`.
> Client: Add getCollectionFromState()

- README.md
- docs/how-tos.md
- packages/cozy-pouch-link/package.json
- packages/cozy-pouch-link/src/CozyPouchLink.js
- packages/cozy-pouch-link/src/PouchManager.js
- packages/cozy-pouch-link/src/logger.js
- yarn.lock
I propose that our libs use minilog for logging. It has namespaces and filtering abilities. This would allow us to view logs quickly without polluting the logs if we do care for them.
2.5kb minified/gzipped.
A package level logger is created. An application will be able to view logs via
```
require('minilog').enable()
```
Warn/errors logs are visible directly.
If an application wants to see the debug logs of cozy-pouch-link :
```
require('minilog').suggest.allow('cozy-pouch-link', 'debug')
```
> [pouch-link] feat: Log via minilog

- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
- packages/cozy-client/src/associations/helpers.js
We want to retrieve all the triggers for a given konnector to know which error they are containing.
For that, we will use a custom association in the konnector schema.
This association will have an async query method, which may return existing document.
The goal is to use an Association like this (naive implementation):
```js
class HasManyTriggers {
static async query(){
const triggers = await fethTriggers()
return triggers.filter(isTriggerForKonnector(slug)
}
}
```
This PR :
* Allows async query methods in Associations
* Allows a query method to return documents
* Fix a few things
> Client: Update fetchRelationships method

- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/Schema.js
- packages/cozy-client/src/Schema.spec.js
In the cozy-bar we will need to access konnectors, and we cannot be sure that CozyClient has been initialized with the expected schema.
This PR adds a method to dinamically add a schema.
```js
client.addSchema({
todos: {
doctype: 'io.cozy.todos'
}
})
```
> Client: Add Schema.add() method

- packages/cozy-stack-client/src/AppCollection.js
- packages/cozy-stack-client/src/CozyStackClient.js
- packages/cozy-stack-client/src/KonnectorCollection.js
- packages/cozy-stack-client/src/__tests__/KonnectorCollection.spec.js
Last step for us to be able to get installed konnectors and
their triggers as HasManyTriggers relationship.
Unfortunately we would like to do:
```
const konnectors = client.query(client.all('io.cozy.konnectors').include('triggers)
```
But [remember](https://github.com/cozy/cozy-client/pull/393), we have a blocking change in Cozy-Banks that forbid us to respond to client.all('io.cozy.konnectors') with a KonnectorCollection.
Here the good news, as `client.all('io.cozy.konnectors').where({ something })` rely internally on `KonnectorCollection.find()`, this PR made `AppCollection.find()` encapsulate a call to `DocumentCollection.find()`, which make everything works well (As `KonnectorCollection` extends `AppCollection`.
> StackClient: Update KonnectorCollection

- docs/api/cozy-client.md
- packages/cozy-client/src/associations/HasManyTriggers.js
- packages/cozy-client/src/associations/HasManyTriggers.spec.js
- packages/cozy-client/src/associations/index.js
- packages/cozy-client/src/index.js
- packages/cozy-stack-client/src/TriggerCollection.js
- packages/cozy-stack-client/src/TriggerCollection.spec.js
This PR prepares need of retrieving all the triggers for a given konnector, with the goal to detect all errors related to it.
It fixes a few mistakes in TriggerCollection and implements the find() method, which will allow us to do:
```js
const triggers = client.query(client.all('io.cozy.triggers').where({worker: 'konnector'})
```
It also introduces the `HasManyTriggers` association, which fetch all triggers or get them in CozyClient redux store. It then filters them to only get triggers related to the konnector having the association.
It is more or less a hack to manage the way that we only have the endpoint `/jobs/triggers` to retrieve triggers.
> StackClient/Client: Add HasManyTriggers and update TriggerCollection

- packages/cozy-stack-client/src/AppCollection.js
- packages/cozy-stack-client/src/KonnectorCollection.js
- packages/cozy-stack-client/src/__tests__/AppCollection.spec.js
- packages/cozy-stack-client/src/__tests__/KonnectorCollection.spec.js
Get back to throwing method for not implemented endpoints for apps an konnectors.
Follows feedback from #406.
> Client: Better AppColleciton and KonnectorCollection

- packages/cozy-client/package.json
- packages/cozy-client/src/CozyClient.js
Emitting events during login/logout provides a flexible way
for components/objects using CozyClient to setup/destroy
themselves. It lets the setup to be decoupled from where
the login/logout happens.
I think it can be a good way for example to init the bar.
```
cozyClient.on('login', setupBar)
cozyClient.on('logout', destroyBar)
```
I would like to have your views on this.
> feat: Client emits events for log{in,out}

- docs/api/cozy-client.md
- docs/api/cozy-stack-client.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/authentication/mobile.js
- packages/cozy-stack-client/src/CozyStackClient.js
- packages/cozy-stack-client/src/OAuthClient.js
- packages/cozy-stack-client/src/TriggerCollection.js
- packages/cozy-stack-client/src/__tests__/AppCollection.spec.js
- packages/cozy-stack-client/src/__tests__/CozyStackClient.spec.js
- packages/cozy-stack-client/src/__tests__/KonnectorCollection.spec.js
- Allowing to use stack client when not completely initialized enables to remove duplicated code from the authentication code. 
- Reduce timeout because who has 10s to lose ?
- When the login process has finished, it is ergonomic to do login(url, token) and have setURI and setToken done for you
> Oauth client improv

- packages/cozy-stack-client/src/KonnectorCollection.js
- packages/cozy-stack-client/src/__tests__/AppCollection.spec.js
- packages/cozy-stack-client/src/__tests__/KonnectorCollection.spec.js
expect().rejects.toBe()  returns a promise, it's necessary to await it otherwise if it fails, it is an unhandledRejections that does not make the test fail.
> Fix unhandled rejections

- packages/cozy-stack-client/src/KonnectorCollection.js
find() is used on KonnectorCollection. Removing it was a mistake :/
> fix: Find method was used for KonnectorCollection

- docs/api/cozy-client.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
- packages/cozy-client/src/__mocks__/cozy-stack-client.js
- packages/cozy-stack-client/src/CozyStackClient.js
- packages/cozy-stack-client/src/OAuthClient.js
- packages/cozy-stack-client/src/__tests__/CozyStackClient.spec.js
- packages/cozy-stack-client/src/errors.js
CozyStackClient calls a callback when revoked. CozyClient uses this
callback to emit an event and set a public attribute.
> feat: Event for revocation

- docs/api/cozy-client.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
- packages/cozy-stack-client/src/OAuthClient.js
- packages/cozy-stack-client/src/__tests__/OAuthClient.spec.js
- packages/cozy-stack-client/src/__tests__/__snapshots__/OAuthClient.spec.js.snap
While finishing https://github.com/cozy/cozy-libs/pull/401, I stumbled upon
bugs in revocation and unregister.
- unregister used a deprecated way to set headers which resulted in the
accessToken being used instead of the registrationAccessToken. Unregister
did not work with the accessToken
- When logging back in, we have to check if the client is revoked. After
revocation, the client is logged in (isLogged = true) and isRevoked = true.
This is a bit surprising (I thought at first to set isLogged to false in
handleRevocationChange when revocation is true) but in cozy-authentication we have to differentiate between never having logged (isLogged = false, show login form), and having logged but being revoked (isLogged = true, isRevoked = true, show
revocation modal). This is why I bypass the …
> Unregister and revocation

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/CozyStackClient.js
- packages/cozy-stack-client/src/OAuthClient.js
- packages/cozy-stack-client/src/__tests__/CozyStackClient.spec.js
If an app is opened too long, the stack token could expire. This PR allows the stack client to fetch a new token when needed. This is probably a rare case but the code should have no compatibility break.
> Allows to refresh app tokens

- package.json
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
Emit a beforeLogout when starting the logout process.
It lets us know when logout process has started so we can
display a message to the user in cozy-authentication:MobileRouter.
> [client] feat: Add beforeLogout event

- docs/api/cozy-client.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
Similarly to the beforeLogout event, the beforeLogin event
is sent when the login process has started and before the
links have been set up.
> feat: Add beforeLogin event

- packages/cozy-client/src/ObservableQuery.js
- packages/cozy-client/src/Query.jsx
- packages/cozy-client/src/Query.spec.jsx
- packages/cozy-client/src/__tests__/ObservableQuery.spec.js
- packages/cozy-client/src/__tests__/mocks.js
Sometimes we want to refetch the query, for example in the Bar we want to refetch the konnectors when we go back online, or when the app resumes. We had already fetchMore, I just added fetch to the object received by the renderProps function in `<Query />`.
> feat: Fetch method on ObservableQuery

- docs/api/cozy-client.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
I was surprised by https://github.com/cozy/cozy-bar/pull/545#discussion-diff-282847190R209
Most apps initialize Cozy-Client by providing an uri and a token to the constructor, without any explicit call to `login()`. This PR allows compatibility with all events and state variables like `isLogged` by calling `login()`automatically in this case.
The promise returned by `login()`is kept in case one explicitly call `login()` anyways so there should be no compatibility break
> feat: Cozy-client will autologin if initialized with uri and token

- packages/cozy-pouch-link/src/CozyPouchLink.js
- packages/cozy-pouch-link/src/CozyPouchLink.spec.js
It can be useful to trigger a sync for Pouch. We do this by restarting the
synchronization loop.
> feat: Sync pouch immediately

- packages/cozy-client/src/Query.jsx
- packages/cozy-client/src/Query.spec.jsx
If the CozyClient::Observable passed in context does not have fetch,
do not bind it.
> fix: Do not bind query.fetch if it does not exist

- packages/cozy-client/src/hoc.js
- packages/cozy-client/src/hoc.spec.js
It is useful in snapshots and in inspector to see the display names
of the components. queryConnect and withClient previously would lose
the displayName. Now they wrap the  display name of the wrapped component into "withName()".
⚠️ You might see changes in your snapshots if you use `withClient`.
> feat: Add display name for HOC

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/FileCollection.js
- packages/cozy-stack-client/src/FileCollection.spec.js
We need to be able to overwrite a file using `PUT` method for "Upload conflict management" card (more info here: https://trello.com/c/0cTBor9A/1761-%F0%9D%90%8B-upload-conflit-%C3%A9tape-1-%C3%A9craser-fichier-non-partag%C3%A9 )
> Add updateFile method to FileCollection

- packages/cozy-client/package.json
- packages/cozy-client/src/constants.js
- packages/cozy-client/src/index.js
- packages/cozy-client/src/registry.js
- packages/cozy-client/src/registry.spec.js
- packages/cozy-client/src/terms.js
- yarn.lock
Ability to install/uninstall an app.
```js
import { Registry } from 'cozy-client'
const registryAPI = Registry({ client })
await registryAPI.installApp(app, source) 
```
Functions taken from the store.
> feat: Add Registry API

- docs/api/cozy-client.md
- packages/cozy-client/src/utils.js
- packages/cozy-client/src/utils.spec.js
Wraps a promise and provides a `cancel` method.
.cancel() rejects the wrapped promise as soon as it is called.
`import { cancelable } from 'cozy-client/utils'`
> feat: Add cancelable util

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/FileCollection.js
- packages/cozy-stack-client/src/FileCollection.spec.js
Add a method to restore a file from its id in `FileCollection` (the implementation is exactly the same as `cozy-client-js` `restoreById` : https://github.com/cozy/cozy-client-js/blob/master/src/files.js#L384-L386 )
> Add restore method on FileCollection

- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
- packages/cozy-client/src/__mocks__/cozy-stack-client.js
- packages/cozy-stack-client/src/OAuthClient.js
#447 could not work with the [cozy-konnector-dev](https://github.com/konnectors/libs/tree/master/packages/cozy-jobs-cli) script because it uses an OAuth authentication and `fromEnv` was expecting a string from `COZY_CREDENTIALS`
This PR fixes this behaviour.
> fix: Allow fromEnv instantiation from oauth client

- packages/cozy-client/src/index.js
Export `cancelable` util directly to be able to do `import { cancelable } from 'cozy-client'`
I had issues trying to import it from `cozy-client/utils` (see #443 ) but it's maybe related to path resolution in drive
> Export cancelable util

- docs/api/cozy-client.md
- packages/cozy-client/src/Schema.js
- packages/cozy-client/src/Schema.spec.js
Schemas are necessary for relationships but are not really necessary for
simple doctypes. If a schema has not been added to the client, for now
we throw. I think it would be more ergonomic either to 
- return an empty object if we do not know the doctype.
- have a list of known doctypes that can be used without declaring them.
Here I added the `io.cozy.terms` doctype (the second solution). WDYT ? 
cc @edas ?
> feat: Implicitly create unknown schema

- packages/cozy-client/src/Schema.js
"[Object object]" was showing in the console since we were not logging
the `.name` of the schemas.
> fix(schema): Map on names to show duplicate error

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/AccessToken.js
- packages/cozy-stack-client/src/AppToken.js
- packages/cozy-stack-client/src/CozyStackClient.js
- packages/cozy-stack-client/src/__tests__/CozyStackClient.spec.js
- packages/cozy-stack-client/src/__tests__/OAuthClient.spec.js
`client.getStackClient().getAccessToken()`
I was sick of looking for
```
cozyClient.stackClient.token.accessToken
||
cozyClient.stackClient.token.token
```
> feat: Add an unified way to get the access token

- .travis.yml
- lerna.json
- package.json
- yarn.lock
Lerna can create a GitHub release with all the changes of the release.
It can then be used by renovate in its PRs.
> chore: Publish GitHub release with changes through lerna

- packages/cozy-client/src/withMutations.jsx
- packages/cozy-client/src/withMutations.spec.jsx
Get exposed prop-types is useful when you want to check or get an exhaustive list of provided props and the related types for developing or for testing
> fix(withMutations): Expose all withMutations provided props types

- packages/cozy-client/src/withMutations.jsx
- packages/cozy-client/src/withMutations.spec.jsx
Proptypes was put onto the wrapper instead of the Wrapped.component, causing undefined proptypes issues with React
> Put proptypes on wrapped component instead of wrapper

- packages/cozy-stack-client/src/CozyStackClient.js
- packages/cozy-stack-client/src/JobCollection.js
- packages/cozy-stack-client/src/__tests__/CozyStackClient.spec.js
We expect to get a `JobCollection` when we use `client.collection('io.cozy.jobs')`. This PR fixes this.
(context: we need `JobCollection` to be able to use the new zip worker for credit application)
PS: I'll create another PR to add `JobCollection` to the docs
> feat(stack): Expose JobCollection via client.collection('io.cozy.jobs')

- packages/cozy-client/src/associations/HasOne.js
- packages/cozy-client/src/associations/HasOne.spec.js
When trying to add a `HasOne` relationship on `io.cozy.bank.accounts` like this:
```js
const schema = {
bankAccounts: {
doctype: ACCOUNT_DOCTYPE,
attributes: {},
relationships: {
masterAccount: {
type: 'has-one',
doctype: ACCOUNT_DOCTYPE
}
}
},
}
```
Then access the `masterAccount.data` property on an account, I got an error:
```
Cannot read property 'masterAccount' of undefined
```
This was because in `HasOne.raw` getter `this.target.relationships` was undefined.
I handled it by using lodash's `get` to access `this.target.relationships[this.name].data` and fallback on null.
> fix(cozy-client): Association HasOne don't fail if there is no data

- packages/cozy-client/src/associations/HasOne.js
- packages/cozy-client/src/associations/HasOne.spec.js
These methods can be used to update the document that is associated to another one when using a `HasOne` relationship.
> feat(cozy-client): Add set and unset methods on HasOne

- docs/api/cozy-client.md
- docs/api/cozy-stack-client.md
- packages/cozy-client/examples/file-relationships.js
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/__tests__/associations.spec.js
- packages/cozy-client/src/associations/HasManyFiles.js
- packages/cozy-client/src/queries/dsl.js
- packages/cozy-client/src/store/__snapshots__/queries.spec.js.snap
- packages/cozy-stack-client/src/DocumentCollection.spec.js
- packages/cozy-stack-client/src/FileCollection.js
- packages/cozy-stack-client/src/querystring.js
This adds the possibility to use cursor-based pagination, just like [this](https://github.com/cozy/cozy-client-js/pull/288).
For a query on 2185 files referenced by a single album, it takes 14.1s with skip-based pagination and 7.6s with cursor-based pagination.
Note the Couch query itself is greatly sped up, especially with large skip, e.g. 343ms for a `skip=2000` vs 20ms with cursor.
> Add cursor-based pagination

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/FileCollection.js
- packages/cozy-stack-client/src/FileCollection.spec.js
Discussed on the mattermost channel a few days ago. Uses the route from the stack : https://docs.cozy.io/en/cozy-stack/files/#patch-filesfile-id-and-patch-filesmetadata
(well, maybe we could name it `permanentDelete` here too)
> Add deleteFilePermanently method

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/FileCollection.js
- packages/cozy-stack-client/src/FileCollection.spec.js
Same as https://github.com/cozy/cozy-client/commit/c9dbb6f50fe14e9084f8af62d955602b7203e537 but for updateFile. 
We can now attach a metadata to the updatedFile.
> feat(cozy-stack-client): Updatefile can create metadata

- packages/cozy-stack-client/package.json
- packages/cozy-stack-client/src/FileCollection.js
- packages/cozy-stack-client/src/FileCollection.spec.js
- yarn.lock
Mime-types depends of mime-db, which is mostly a 160kb JSON file. It is heavy, as it is embedded in most of our webapps. Mime is a lighter alternative: https://www.npmjs.com/package/mime.
Please note that I have made this change without testing anything! Be careful before merging it.
> feat: Use a lighter mime library

- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
- packages/cozy-client/src/__snapshots__/CozyClient.spec.js.snap
Today, we have to manually do the query loop everytime we need to query all documents with a given selector. Until now, we had [`Document::queryAll`](https://github.com/cozy/cozy-libs/blob/master/packages/cozy-doctypes/src/Document.js#L459) to achieve the same goal, but this logic can be implemented directly inside cozy-client.
We also have a [`UNSAFE_noLimit`](https://github.com/cozy/cozy-client/blob/master/packages/cozy-client/src/queries/dsl.js#L140-L142) method, but this can't be used with a selector (see https://github.com/cozy/cozy-client/blob/master/packages/cozy-stack-client/src/DocumentCollection.js#L45-L48)
It will be useful in [cozy-procedures](https://github.com/cozy/cozy-libs/pull/682#discussion_r306162578), where we precisely want to query all documents with a selector.
> feat(cozy-client): Add queryAll method

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/Collection.js
- packages/cozy-stack-client/src/DocumentCollection.js
- packages/cozy-stack-client/src/JobCollection.js
- packages/cozy-stack-client/src/JobCollection.spec.js
- packages/cozy-stack-client/src/TriggerCollection.js
This method is actually used here https://github.com/cozy/cozy-libs/blob/master/packages/cozy-harvest-lib/src/models/konnector/KonnectorJobWatcher.js#L100, and throw an error.
This PR also suggest to abstract get methods pattern into an higher utility classed named Collection.
> StackClient: Implement JobCollection.get() method

- packages/cozy-client/package.json
- yarn.lock
React should not be a direct dependency but instead a peer dependency. To have it in tests, it should also be a dev dependency.
> chore(cozy-client): Move react to peer deps

- packages/cozy-client/src/ObservableQuery.js
- packages/cozy-client/src/__tests__/ObservableQuery.spec.js
When getting results from queries that were being refetched, the fetch
status was "loading" but there was data so the consumer received unhydrated
data
> fix: Hydrate documents also for in-flight queries

- docs/api/cozy-stack-client.md
- packages/cozy-client/src/CozyClient.spec.js
- packages/cozy-client/src/StackLink.js
- packages/cozy-client/src/__tests__/fixtures.js
- packages/cozy-client/src/associations/HasManyFiles.js
- packages/cozy-client/src/associations/HasManyFiles.spec.js
- packages/cozy-client/src/index.js
- packages/cozy-client/src/queries/dsl.js
- packages/cozy-stack-client/src/FileCollection.js
- packages/cozy-stack-client/src/FileCollection.spec.js
- packages/cozy-stack-client/src/__snapshots__/FileCollection.spec.js.snap
This allows to add / remove referenced_by documents, from files. It implements the following routes: 
* https://docs.cozy.io/en/cozy-stack/references-docs-in-vfs/#post-filesfile-idrelationshipsreferenced_by
* https://docs.cozy.io/en/cozy-stack/references-docs-in-vfs/#delete-filesfile-idrelationshipsreferenced_by
For example, one can add / remove albums directly from a file.
> Add support for referenced-by

- docs/details.md
- packages/cozy-client/package.json
- packages/cozy-client/src/node.js
- packages/cozy-client/src/react.js
Following discussions on https://github.com/cozy/cozy-client/pull/494, I decided to open another PR.
The main entry point is exposing the API without react bindings. This
allows a node application to use cozy-client without having to import
modules from the `dist` directory and without having to install react as
a dependency.
The browsers entry point is exposing the entire API (with react
bindings). This changes nothing for web apps.
There is also the possibility to import react specific stuff from
`cozy-client/dist/react` in rare cases in which this could be useful.
This is just an escape hatch.
There is some duplication in `index.js`, `node.js` and `react.js` that I tried to avoid by doing the following in `index.js`:
```js
export * from './node.js'
export * from './react.js'
```
But …
> feat(cozy-client): Expose main and browsers entry points

- README.md
The how-to.md file has been removed since
https://github.com/cozy/cozy-client/pull/490 so these links are not
needed anymore.
> docs: Remove how to links from readme

- renovate.json
We now have a renovate config that does not pin dependencies.
See https://github.com/cozy/cozy-libs/blob/master/packages/renovate-config-cozy-libs/package.json
Related to https://github.com/cozy/cozy-client/pull/499
> chore: Use cozy-libs renovate config

- packages/cozy-client/package.json
- packages/cozy-pouch-link/package.json
- packages/cozy-stack-client/package.json
Since the packages here are libraries, they need to more lenient on the
libs they accept from their host otherwise there can be duplicates in the
final bundle
https://renovatebot.com/docs/dependency-pinning/
This is helpful to remove duplicate package warnings that we see with DuplicatePackageCheckerPlugin:
```
WARNING in lodash
Multiple versions of lodash found:
4.17.13 ./~/cozy-device-helper/~/lodash
4.17.14 ./~/cozy-client/~/lodash
4.17.15 ./~/lodash
WARNING in prop-types
Multiple versions of prop-types found:
15.6.2 ./~/cozy-client/~/prop-types
15.7.2 ./~/prop-types
> chore: Unpin dependencies

- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
- packages/cozy-client/src/ObservableQuery.js
- packages/cozy-client/src/Query.jsx
- packages/cozy-client/src/Query.spec.jsx
- packages/cozy-client/src/__tests__/ObservableQuery.spec.js
- packages/cozy-client/src/__tests__/connect.spec.jsx
- packages/cozy-client/src/__tests__/mocks.js
- packages/cozy-client/src/__tests__/utils.js
- packages/cozy-client/src/hoc.spec.js
- packages/cozy-client/src/utils.spec.js
- packages/cozy-stack-client/src/DocumentCollection.js
- packages/cozy-stack-client/src/DocumentCollection.spec.js
- packages/cozy-stack-client/src/__tests__/setup.js
- packages/cozy-stack-client/src/getIconURL.spec.js
By not changing objects passed to children function at each render (the objects changed due to {...spreading}), React.memo can do its job.
> Perf: Query.jsx not changing objects passed to children

- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
- packages/cozy-client/src/ObservableQuery.js
- packages/cozy-client/src/Query.jsx
- packages/cozy-client/src/Query.spec.jsx
- packages/cozy-client/src/__tests__/ObservableQuery.spec.js
- packages/cozy-client/src/__tests__/connect.spec.jsx
- packages/cozy-client/src/__tests__/mocks.js
- packages/cozy-client/src/__tests__/utils.js
- packages/cozy-client/src/hoc.spec.js
- packages/cozy-client/src/utils.spec.js
- packages/cozy-stack-client/src/DocumentCollection.js
- packages/cozy-stack-client/src/DocumentCollection.spec.js
- packages/cozy-stack-client/src/__tests__/setup.js
- packages/cozy-stack-client/src/getIconURL.spec.js
Previous PR was merged in the wrong branch. As soon as this is green, I merge since the previous PR #519 was approved.
> Perf: Return the same args for Query.Children()

- docs/api/cozy-client.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/Query.jsx
- packages/cozy-client/src/Query.spec.jsx
`fetchPolicy` gives the ability to decide if the query should be
refetched at mount time. See query prop documentation for more
information ;).
Note: The `cache-only` value did not work and was never used, this is why I went with a breaking change here.
> feat: Fetch policy

- package.json
- yarn.lock
When `yarn install`, I had the following warnings:
```
warning " > babel-loader@8.0.6" has unmet peer dependency "@babel/core@^7.0.0".
warning " > babel-loader@8.0.6" has unmet peer dependency "webpack@>=2".
warning " > eslint-loader@2.2.1" has unmet peer dependency "webpack@>=2.0.0 <5.0.0".
```
The presence of these deps was very strange, so I checked where they are used:
```
rg babel-loader
yarn.lock
2567:babel-loader@8.0.6:
2569:  resolved "https://registry.yarnpkg.com/babel-loader/-/babel-loader-8.0.6.tgz#e33bdb6f362b03f4bb141a0c21ab87c501b70dfb"
package.json
5:    "babel-loader": "8.0.6",
```
```
rg eslint-loader
package.json
13:    "eslint-loader": "2.2.1",
yarn.lock
5265:eslint-loader@2.2.1:
5267:  resolved "https://registry.yarnpkg.com/eslint-loader/-/eslint-loader-2.2.1.tgz#28b9c1 …
```
> chore: Remove unused dependencies

- docs/api/cozy-stack-client.md
- packages/cozy-client/src/Query.jsx
- packages/cozy-client/src/__tests__/ObservableQuery.spec.js
- packages/cozy-client/src/withMutations.spec.jsx
- packages/cozy-stack-client/src/CozyStackClient.js
- packages/cozy-stack-client/src/DocumentCollection.js
- packages/cozy-stack-client/src/DocumentCollection.spec.js
- Throw when refreshToken is used in a context where the token cannot be refreshed
I saw this error when developing for a service. The original error was "Need absolute URIs" since fetch("/") would fetch a URL that was not absolute (since it did not have the URL of the Cozy). Anyway, this method of refreshing the token by asking the server an HTML page cannot work in services, this is why I prefer a hard throw.
- Privatized methods from DocumentCollection as they were cluttering the docs
- Added updateAll and deleteAll in DocumentCollection. Originally from Document.
> Improvements

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/FileCollection.js
- packages/cozy-stack-client/src/FileCollection.spec.js
- packages/cozy-stack-client/src/__snapshots__/FileCollection.spec.js.snap
Use the new route to update file's metadata by creating a new
version of the file without having to upload it again.
See: https://github.com/cozy/cozy-stack/pull/2119/files
> feat(cozy-stack-client): Filecollection update file metadata

- packages/cozy-client/src/registry.js
Adds a new method that returns the list of apps that are in maintenance. It's literally just one line so I don't see any pertinent test to add, but let me know what you think.
> feat: Fetch maintenance apps

- docs/api/cozy-client.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/index.js
- packages/cozy-client/src/models/index.js
- packages/cozy-client/src/models/triggers.js
- packages/cozy-client/src/models/triggers.spec.js
Need helpers on triggers in Banks and finally took the leap and moved methods from Banks related to triggers in cozy-client 🎉 
This folder will serve to put all helpers on documents.
Bring helper methods from apps here.
Also bring non-network methods from cozy-doctypes here.
Network methods involving the stack must be put inside cozy-stack-client.
> Helper method on triggers

- packages/cozy-client/src/withMutations.jsx
- packages/cozy-client/src/withMutations.spec.jsx
withMutations HOC was modifying the original component proptypes. This
would result in warning during tests in Banks. If the original component
needs some props, it should put them itself and not rely on the HOC
to put them.
> fix: Do not modify wrapped component PropTypes

- docs/api/cozy-client.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/ObservableQuery.js
/!\ : Should change base branch to master when docstrings is merged
Since selectors can be a way for an app to get documents from client, it
is useful to be able to select already hydrated documents. It also enables to remove hydratation logic from the Query.
This is useful to fix a bug in Banks that was introduced when we changed to use selectors on the store : since we previously received the documents from `queryConnect`, they were already hydrated. After changing to use selectors, they
were not hydrated.
> feat: GetQueryFromState can hydrate documents directly

- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
- packages/cozy-client/src/__tests__/fixtures.js
I did not test so I did not see the bug. My bad :/
Since the doctype was not passed correctly, data came non hydrated out of getQueryFromState.
> fix: Did not pass the right attribute for hydratation

- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
The PR changes the behavior of `client.logout` to perform either an OAuth unregistration or a plain web client log out, depending on the situation.
> feat: Log out a web client

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/CozyStackClient.js
- packages/cozy-stack-client/src/SettingsCollection.js
- packages/cozy-stack-client/src/SettingsCollection.spec.js
This PR adds a simple Settings collection that can be used to query routes on [`/settings`](https://docs.cozy.io/en/cozy-stack/settings/#get-settingsinstance)., as discussed [here](https://github.com/cozy/cozy-home/pull/1369#discussion_r340784655).
> feat: Added a simple settings collection

- docs/api/cozy-client.md
- packages/cozy-client/src/cli/index.js
Add a way to instantiate a client from the CLI through an OAuth flow.
Taken mostly from ACH's client instantiation.
> chore: Add client creation for CLI

- docs/api/cozy-client.md
- packages/cozy-client/src/index.js
- packages/cozy-client/src/queries/dsl.js
- packages/cozy-client/src/queries/dsl.spec.js
As discussed in https://github.com/cozy/cozy-client/issues/533, the Q helper
is here to simplify the creation of a query definition (no need for a client
to build a query definition). It will be used then to merge "read" query
definitions making and "write" (mutation) query definitions making.
> feat: Expose Q helper to build query definitions

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/FileCollection.js
- packages/cozy-stack-client/src/FileCollection.spec.js
- packages/cozy-stack-client/src/utils.js
- packages/cozy-stack-client/src/utils.spec.jsx
Cozy-stack now supports file versioning. This PR adds the ability to download a specific revision of the file. We use the stack's route: https://github.com/cozy/cozy-stack/blob/94e62d16054c0bec33d0f283a6fc49ed1f6c8300/docs/files.md#post-filesdownloadsversionidfile_idversion_id 
Added a few test for the `download` method. 
Also add a small utility : getBeautifulSize() that expose a new utility to beautify the size of a file
> feat(cozy-stack-client): Download file version

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/FileCollection.js
- packages/cozy-stack-client/src/FileCollection.spec.js
In a mobile env, we need to get the content of a file (or a version) in order to write it on the local FS. 
This is an equivalent cozy-client-js' `downloadById`
> feat(cozy-stack-client): Files get binary of a file

- docs/api/cozy-client.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
Adds a method for CozyClient to expose the options injected by the stack into our web page templates.
> feat: Expose instance options

- packages/cozy-stack-client/src/SettingsCollection.js
- packages/cozy-stack-client/src/SettingsCollection.spec.js
ATM, if we use `SettingsCollection` as we don't return `data` even if we received a QUERY_RESULT our store is not updated with the latest status (and result). 
It can be considered as a BC but I think it is not currently usable since <Query or queryConnect will be "loading" for ever. I don't know... @y-lohse do you use it already?
> fix: SettingsCollection fix data response

- docs/api/cozy-client.md
- packages/cozy-client/src/models/instance.js
- packages/cozy-client/src/models/instance.spec.js
We now have an standardized way of saying if an instance is concerned by our offers or not. 
Changed the `isFreemiumUser` to take instanceInfo like other methods (as suggested by @ptbrowne in a previous PR) + added a test in order to prevent BC. Since this method is not used yet, I didn't tag the commit as BC
Next PR soon, an helper to wrap those 3 queries (context / instance / diskusage)
> feat: Add shoulDisplayOffers method

- babel.config.js
- packages/cozy-client/package.json
- packages/cozy-client/src/CozyClient.js
- yarn.lock
In order to be able to make a call to a new API or dealing with
new / old version, exposing the version makes it easier.
At the beginning I created a `getVersion` function in order to get the version, but I don't think it makes sense and brings complexecity since we'll have, in the app, to check if `getVersion` exists before calling it (or try/catch). Here, we juste have to do check if the result is not undefined 
To compare the versions, we just use something like this package : https://github.com/substack/semver-compare
> feat: Expose cozy client's version

- packages/cozy-stack-client/src/CozyStackClient.js
- packages/cozy-stack-client/src/__tests__/CozyStackClient.spec.js
We fount out a strange behavior in drive when our token was expired and we called a `find` with indexes and sort in the same time. 
The call to refresh token was done and we got a new token, but the recall of this find failed with a nice error  
After looking in my request panel, I find out that my request had a strange payload... 
With the help of @y-lohse we fixed the issue. 
It's pretty simple but deceitful in the same time. The fact is that we are adding a Content-Type header (https://github.com/cozy/cozy-client/blob/master/packages/cozy-stack-client/src/CozyStackClient.js#L214) to `options`. But since options is an object, the scope of this change is not the one we want. By adding this header, in the second call, we do not stringify our body (resulting in the `Object object`).
To fix …
> fix: Don't change my headers

- packages/cozy-stack-client/src/OAuthClient.js
This commit is only a jsDoc change. Its purpose is to trigger a
new release of cozy-stack-client. The real feature is on #584
> feat: Fix regeneratorRuntime

- docs/api/cozy-client.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/__mocks__/cozy-stack-client.js
- packages/cozy-client/src/associations/Association.js
- packages/cozy-client/src/mock.js
- packages/cozy-client/src/mock.spec.js
- packages/cozy-stack-client/src/index.js
Move mock client from banks to here. Client internal store can be
prefilled with data from fixtures and query is mocked so that calls
to the server use fixtures.
Related: https://github.com/cozy/cozy-client/issues/72
> feat: Add mockClient creation for use in tests

- packages/cozy-client/src/registry.js
- packages/cozy-client/src/registry.spec.js
I found a bit misleading the use of `options` in the signature function, which could suggest the parameters are optionnal ;)
> style: Use params instead of options

- packages/cozy-client/src/models/file.js
- packages/cozy-client/src/models/file.spec.js
My previous version was just checking if the attributes was existing, but since `version` is a number and not a string, if version === 0, then `(version && true) === false`
> fix: Test if note

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/PermissionCollection.js
- packages/cozy-stack-client/src/PermissionCollection.spec.js
This will be useful for cozy-notes. We want links to accept PATCH and PUT so the recipient can edit the note.
> feat: Share a link with special permissions

- packages/cozy-stack-client/src/DocumentCollection.js
- packages/cozy-stack-client/src/DocumentCollection.spec.js
Otherwise we have an error from the stack, since _type is a reserved
attribute
> feat: Destroy all removes the _type from the document

- docs/api/cozy-client.md
- packages/cozy-client/src/models/applications.js
- packages/cozy-client/src/models/applications.spec.js
With getStoreInstallationURL, the user was redirected to the store page
with the permissions modal. We want to be able to redirect to the app's
store page and make the user click on the "install" button, otherwise he
may not know what he is going to install. The getStoreURL method returns
the app's root page. And getStoreInstallationURL now uses it to return
the installation URL.
Also added tests for both methods.
There's a discussion about unifying the behavior in places where we use getStoreInstallationURL and now getStoreURL. See https://mattermost.cozycloud.cc/cozycloud/pl/bhwaet9md7gifg3y9g1tqyzzby
> feat(cozy-client): Add getStoreURL method to applications model

- docs/api/cozy-stack-client.md
- packages/cozy-client/package.json
- packages/cozy-client/src/cli/index.js
- packages/cozy-client/src/cli/index.spec.js
- packages/cozy-client/src/cli/tester.js
- packages/cozy-stack-client/src/OAuthClient.js
- yarn.lock
- Fix: Only token was taken from the credentials, which was not sufficient, since
we also need the clientID. Now we save both the token and oauth information, and restore the client from both informations.
- Feat: Added hashed scope to the credentials filename so that we have no collision when changing doctypes
Added tests.
> fix: Correctly create interactive client from saved credentials

- packages/cozy-client/src/models/trigger.js
- packages/cozy-client/src/models/trigger.spec.js
There was a straight up mistake in one of the tests, which means an error that is muted for a trigger that has no last success date was still being displayed.
> fix: Mute trigger errors without success

- docs/api/cozy-client.md
- packages/cozy-client/examples/perfs.js
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/queries/dsl.js
- packages/cozy-client/src/store/__snapshots__/queries.spec.js.snap
- packages/cozy-client/src/store/queries.js
- packages/cozy-stack-client/src/DocumentCollection.js
- packages/cozy-stack-client/src/DocumentCollection.spec.js
This enables [bookmark pagination](https://docs.couchdb.org/en/2.2.0/api/database/find.html#pagination) for "all" documents queries (the "find" queries will come afterwards).
It also adds a performance example, with some measures:
- 1 000 docs:
- no pagination: ~108 ms
- skip pagination: ~1 429 ms
- bookmark pagination: ~563 ms
- 10 000 docs:
- no pagination: ~932 ms
- skip pagination: ~165 741ms
- bookmark pagination: ~7 850 ms
>  feat: Use bookmark pagination for queryAll

- packages/cozy-pouch-link/src/helpers.spec.js
On a busy CPU, e.g. while running zoom + VM and/or mining coins, some heavy pouchdb tests might fail because of the default jest timeout, set to 5000ms (e.g. querying 2000 docs).
We increase the timeout to 10000ms for these tests to fix that.
> test: Increase timeout for pouch

- docs/react-integration.md
- package.json
- packages/cozy-client/codemods/use-q.js
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
- packages/cozy-client/src/__tests__/ObservableQuery.spec.js
- packages/cozy-client/src/__tests__/StackLink.spec.js
- packages/cozy-client/src/__tests__/connect.spec.jsx
- packages/cozy-client/src/associations/HasManyTriggers.js
- packages/cozy-client/src/hoc.spec.js
- packages/cozy-client/src/mock.js
- packages/cozy-client/src/mock.spec.js
- packages/cozy-client/src/node.js
- packages/cozy-pouch-link/src/CozyPouchLink.spec.js
- packages/cozy-pouch-link/src/mango.spec.js
- packages/cozy-stack-client/src/FileCollection.spec.js
- all is a bad name since it implies in the mind of the developer
that no pagination is done (whereas pagination is automatic
when using queries built with all)
- Q does the same as client.all but does not necessitate a client
(since no client is necessary to build a queryDefinition)
- Add a codemod to transform client.all into Q (and add the import
if necessary)
> feat: Deprecate client.all in favor of Q

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/CozyStackClient.js
- packages/cozy-stack-client/src/__tests__/CozyStackClient.spec.js
When Cozy-Client detect an expired token, it calls
`setToken` with the result of `refreshToken`.
Problem : refreshToken returns an AppToken but
setToken expect a jwt string.
OAuthClient has a code dealing with this. StackClient
doesn't. This change fix StackClient.
> fix: Refresh token on expiration

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/getIconURL.js
- packages/cozy-stack-client/src/getIconURL.spec.js
- packages/cozy-stack-client/src/memoize.js
- packages/cozy-stack-client/src/memoize.spec.js
Currently, if we render an `AppIcon` component with a `fetchIcon` props calling  :
```jsx
client.getStackClient().getIconURL({
type: 'konnector',
slug: konnector.slug
})
```
When first call this getIconURL being offline, it'll memoize the return of this function aka an error. If we're now online and then call this same method again, we'll not have the icon since we've memoized the first response. 
This fix was my first idea to quickly see if this was really the issue. And it seems that yes. I'm not sure this is the best way to fix it thought since if we go then offline, we will request the icon and since the `onLine` has changed, we will not hit the cache and try to really fetch the icon. 
So maybe the best solution is to not memoize when we're get an error ?
(I think it can fix the …
> fix: Don't memoize if the result is an error

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/CozyStackClient.js
- packages/cozy-stack-client/src/NotesCollection.js
- packages/cozy-stack-client/src/NotesCollection.spec.js
This PR adds a basic collection for `io.cozy.notes`. Here is the corresponding doc: https://docs.cozy.io/en/cozy-stack/notes/
I say basic because:
1. It doesn't support all the special routes
2. It has no pagination support yet, I'm creating an issue detailing the problem right away
> feat: Basic Notes collection

- docs/api/cozy-client.md
- packages/cozy-client/src/associations/HasMany.js
- packages/cozy-client/src/associations/HasMany.spec.js
BREAKING:
- HasMany::data does not return null values
- existsById changes of semantics
- containsById retains the previous behavior of existsById
---
- containsById does not check for document existence in the store
- existsById checks for existence of the document in the store
> feat: HasMany prunes absent documents before passing them down

- docs/api/cozy-client.md
- packages/cozy-client/src/CozyClient.js
Unlike other instantiators, `fromOldOAuthClient` needs to be awaited
so it seems appropriate to add a warning in its description.
The doc was not generated when the method was introduced.
> docs: Document `fromOldOAuthclient` method

- packages/cozy-client/src/CozyClient.js
I was trying to use cozy-client in the bar by making a query. But since I was instancing cozy-bar before making `client.setStore` in Drive, I had this error and I didn't know what to do.
thanks to @ptbrowne, I now know that, when you call a query before setting a store, cozy-client creates by itself its store. So calling setStore later throws an exception. 
Add a line about the error
> docs: Not call setStore too late

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/SharingCollection.js
- packages/cozy-stack-client/src/SharingCollection.spec.js
This route was not implemented yet in the SharingCollection. 
The idea is to be able to revoke all the members of a sharing if I'm the owner of this sharing.
> feat: Add revokeAllRecipients for a sharing

- packages/cozy-client/src/node.js
The models can be used in node environment, so they should be exported from the node entrypoint.
> feat(cozy-client): Export models in node entry point

- docs/api/cozy-client.md
- packages/cozy-client/src/helpers.js
- packages/cozy-client/src/helpers.spec.js
- packages/cozy-client/src/index.js
- packages/cozy-client/src/node.js
This helper meant to build URLs to Cozy applications lived in
`cozy-ui` although it would be useful to apps that don't need
`cozy-ui`.
This version adds the possibility to pass search parameters as well.
This should be useful for apps that need a share code for example.
> feat: Add generateWebLink helper

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/NotesCollection.js
- packages/cozy-stack-client/src/NotesCollection.spec.js
This method calls the `/notes/:id/open` stack endpoint to fetch the
required details to build a url that points to the note in the Notes
application on the note's owner's Cozy.
This means that a shared note will return a NoteUrl that points to the
owner Cozy, with the original note's id and a share code to get
permissions to see the note.
If the note is not shared then the details will point to the client's
Cozy and no share code.
> feat: Add Notes collection `fetchURL` method

- packages/cozy-client/package.json
- packages/cozy-client/src/cli/index.js
- packages/cozy-client/src/cli/index.spec.js
- yarn.lock
This package name changed and this now generates an annoying warning
message on install
https://github.com/sindresorhus/open/releases/tag/v7.0.0
> fix: Use open package instead of old opn

- docs/relationships.md
Fix some typos in the relationship doc, mainly closing code blocks whom the rendering was kind of broken in the website, e.g. https://docs.cozy.io/en/cozy-client/relationships/#add-a-relation-to-an-existing-document
> docs: Fix some typos

- packages/cozy-client/src/cli/index.js
Without this fix, when creating an interactive client, we have an
error on the login page from the stack:  "The redirect_uri parameter doesn\'t match the
registered ones"
With the parameter `url: true`, we have redirect_uri that is double
encoded.
```
before (wrong): redirect_uri=http%253A%252F%252Flocalhost%253A3333%252Fdo_access
after (correct): redirect_uri=http%3A%2F%2Flocalhost%3A3333%2Fdo_access
```
> fix: URL is already encoded, re-encoding it leads to a stack error

- docs/api/cozy-client.md
- docs/react-integration.md
- packages/cozy-client/src/associations/HasMany.js
- packages/cozy-client/src/withMutations.jsx
- packages/cozy-client/src/withMutations.spec.jsx
Instead of using withMutations, we have found that we prefer to use
withClient and methods using this client.
```
const doSomethingWithClient = client => {
...
}
const Component = withClient(({ client  }) => {
const handleClick = () => {
return doSomethingWithClient(client)
}
return <button onClick={handleClick}>click</button>
})
```
> feat: Add deprecation message for withMutations

- packages/cozy-client/examples/perfs.js
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/associations/helpers.js
- packages/cozy-client/src/store/queries.js
- packages/cozy-stack-client/src/DocumentCollection.js
- packages/cozy-stack-client/src/DocumentCollection.spec.js
- packages/cozy-stack-client/src/__tests__/setup.js
Add support for bookmark pagination for documents `find` queries. For the record, bookmark are now the [preferred way to paginate](https://github.com/cozy/cozy-stack/blob/master/docs/mango.md#pagination-cookbook), as it performs way faster than skip.
Note we remove the `meta: {count}` response, as we can no longer know the total count of returned docs, at the query level. This shouldn't be a problem as we can easily retrieve this information by doing a `data.length`, but it might break existing code if some apps are relying on it.
> Add bookmark support for documents find queries

- packages/cozy-stack-client/src/FileCollection.js
- packages/cozy-stack-client/src/FileCollection.spec.js
`isChildOf` was failing if the given child wasn't an object and the hierarchy deeper than 1
> fix: Consider data object from stat

- docs/api/cozy-client.md
- packages/cozy-client/src/associations/HasMany.js
- packages/cozy-stack-client/src/CozyStackClient.js
- packages/cozy-stack-client/src/__tests__/CozyStackClient.spec.js
- packages/cozy-stack-client/src/errors.js
We were refreshing the app token after expiration. 
Some users sometimes have  invalid token. The exact scenario that make this possible is still unknown  but this change allows cozy-client to try  to fix the problem by itself.
> feat: Refresh stack token when invalid

- packages/cozy-client/src/models/note.js
- packages/cozy-client/src/models/note.spec.js
We need a hash for the private url and a search params for the public one. I was doing the oposite.
> fix: Invert private / public params for a note url

- .travis.yml
- scripts/travis.sh
By moving the set -e inside its own file, it should prevent Travis bugs
where set -e prevents travis own error handling to pick up the logs
See https://github.com/travis-ci/docs-travis-ci-com/issues/1672 for more
information
https://docs.travis-ci.com/user/job-lifecycle/#breaking-the-build on what happens when a command exits with 1.
> chore: Do not truncate logs on script error

- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
Instead of injecting instance options with a multitude of variables like `{{.Locale}}`, `{{.Domain}}`, etc… we can also inject a single `{{.Cozy}}` variable. We want to support this as well when using `client.getInstanceOptions()`.
> feat: Support single cozy dataset in DOM

- packages/cozy-client/src/hooks/useAppLinkWithStoreFallback.jsx
Importing from the module itself has a side effect while mocking the client with `genMockFromModule`. We ended with a cozy-client instance without `Cozyclient.models.application` and it fails.
By importing methods from file, it works well. 
```jsx
TypeError: Cannot read property 'applications' of undefined
18 | var _cozyClient = require("cozy-client");
19 |
> 20 | var applications = _cozyClient.models.applications;
|                                       ^
21 |
22 | var useAppLinkWithStoreFallback = function useAppLinkWithStoreFallback(slug, client) {
23 |   var path = arguments.length > 2 && arguments[2] !== undefined ? arguments[2] : '';
at Object.applications (../cozy-client/packages/cozy-client/dist/hooks/useAppLinkWithStoreFallback.js:20:39)
at Object.require …
```
> fix: Don't import from cozy-client. Import from path

- docs/api/cozy-client.md
- packages/cozy-client/src/models/file.js
- packages/cozy-client/src/models/file.spec.js
Small PR... to spread the word ;) 
Just add a new method in the File's model to know if the current file is a shortcut or not. 
Shortcut is a new "kind" of io.cozy.files (https://github.com/cozy/cozy-stack/pull/2387) 
Since doc is ok now: https://docs.cozy.io/en/cozy-stack/shortcuts/
> feat: Add isShortcut method

- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
- packages/cozy-client/src/__snapshots__/CozyClient.spec.js.snap
- packages/cozy-client/src/testing/snapshots.js
Jest by default uses `jest-pretty-format` to serialize objects
in snapshots. `pretty-format` will introspect the object and print
all internal properties. This makes tests relying on snapshots
that use CozyClient very brittle, as even internal/private properties
will get snapshotted, and every implementation change will break snapshots.
`pretty-format` can use the toJSON method to serialize an object. It allows
us to customize the object that will be serialized into the snapshots.
An alternative to using `toJSON` to customize jest serialization would be to use a custom serializer. The problem I see with this approach is that every project wanting to snapshot CozyClient in a sane way would have to add a custom serializer.
Here, CozyClient carries with itself the serialization. It seems …
> feat: Snapshot the client in a simplified form

- packages/cozy-client/src/cli/index.js
After resolve/reject of the oauth process, it is important to clean all
timeouts, otherwise it leaves open handles that prevent node process
to completely shutdown. It was particularly visible since there was a
30 sec rejection timeout
See commit description for more details
> CreateClientInteractive improvements

- packages/cozy-client/src/cli/index.js
- packages/cozy-client/src/cli/index.spec.js
lodash/merge option were in the wrong order for server options
> fix: Allow custom token file path in createClientInteractive

- .eslintrc.json
- docs/api/cozy-client.md
- docs/api/cozy-stack-client.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/Provider.jsx
- packages/cozy-client/src/__tests__/Provider.spec.jsx
- packages/cozy-client/src/__tests__/mocks.js
- packages/cozy-client/src/cli/index.js
- packages/cozy-client/src/context.js
- packages/cozy-client/src/hoc.jsx
- packages/cozy-client/src/hoc.spec.jsx
- packages/cozy-client/src/hooks/index.js
- packages/cozy-client/src/hooks/useAppLinkWithStoreFallback.spec.jsx
- packages/cozy-client/src/hooks/useClient.js
- packages/cozy-client/src/hooks/useClient.spec.jsx
- packages/cozy-client/src/mock.js
- packages/cozy-client/src/queries/dsl.js
- packages/cozy-client/src/registry.js
- packages/cozy-stack-client/src/CozyStackClient.js
- packages/cozy-stack-client/src/TriggerCollection.js
We can now use a hook to get access to the CozyClient in
the context. Backward compatibility with withClient and
old context API is assured.
This is the first part of the ["hooks" PR](https://github.com/cozy/cozy-client/pull/547) that was
a bit too big, and takes a long time to be merged since
there is the useQuery work inside that still needs work. I think it is preferable
to split and get the useClient merged.
> useClient hook

- packages/cozy-client/src/store/queries.js
- packages/cozy-client/src/store/queries.spec.js
This is not an actual PR at this point, I just. want to discuss the issue and evaluate if it needs fixing, and if so how.
The problem occurs after the following steps:
1. Init query `toto` 👉query data is empty
2. Receive results for that query 👉query data contains some ids
3. Init query `toto` again 👉[query data still contains the ids](https://github.com/cozy/cozy-client/blob/master/packages/cozy-client/src/store/queries.js#L41)
4. Receive the same results for the same query 👉[query data gets duplicated](https://github.com/cozy/cozy-client/blob/master/packages/cozy-client/src/store/queries.js#L74)
To me this is a legitimate use case, it can happen simply by navigating several times to a view that makes the same query.
I'm less sure about the correct fix. initially I felt that when we init …
> fix: Make query data duplicate free

- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
- packages/cozy-client/src/ObservableQuery.js
This allows to use bookmark through `fetchMore` when available. 
It also fixes a logic issue that could cause a wrong dispatch of `initQuery` during pagination.
> fix: Use bookmark with fetchMore

- packages/cozy-client/src/hooks/useFetchShortcut.jsx
Found another typo in a hook, but this one is purely internal.
> fix: Typo in function name

- docs/api/cozy-client.md
- packages/cozy-client/src/models/file.js
- packages/cozy-client/src/models/file.spec.js
splitFilename was originally in cozy-doctypes. We prefer
to move all the methods there to cozy-client as it is
tree-shakeable.
> feat: Add splitfilename method

- packages/cozy-stack-client/src/PermissionCollection.js
- packages/cozy-stack-client/src/PermissionCollection.spec.js
`PermissionsCollection.add` did not normalize it's response, which means it didn't have a `_type` field, only a `type`. But all the functions in the collection, including `add` itself, expect the documents to have the `_type` field.
> fix: Normalize PermissionsCollection.add response

- packages/cozy-stack-client/src/xhrFetch.js
- packages/cozy-stack-client/src/xhrFetch.spec.js
Otherwise errors are not propagated to the caller :facepalm:.
> Add onerror handler to fetch XHR

- packages/cozy-stack-client/src/xhrFetch.js
- packages/cozy-stack-client/src/xhrFetch.spec.js
We should return the status and statusText to be
coherent with the fetch method since in a few apps
we test the status to know what to do
> fix: Handle correctly KO result

- packages/cozy-stack-client/src/CozyStackClient.js
Or else you get `ReferenceError: window is not defined` error message
Solves https://github.com/konnectors/libs/issues/673
> fix(cozy-stack-client): Allow fetch to work in node environment

- docs/api/cozy-client.md
- packages/cozy-client/src/hoc.jsx
- packages/cozy-client/src/hoc.spec.jsx
- packages/cozy-client/src/hooks/useQuery.js
- packages/cozy-client/src/hooks/useQuery.spec.jsx
- packages/cozy-client/src/index.js
- packages/cozy-client/src/testing/utils.js
queryConnect entails one nesting level for each query, which leads to a lot of nesting in Banks.
Example:
```jsx
const Component = () => {}
export default queryConnect({
transactions: { ... }, // query options for transactions
triggers: { ... }, // query options for triggers
accounts: { ... }, // query options for accounts
groups: { ... }, // query options for groups
})
```
When rendered, it will look like:
```jsx
<Query query={ transactionsQuery }>
<Query query={ accountsQuery }>
<Query query={ groupsQuery }>
<Query query={ triggersQuery }>
</Query>
</Query>
</Query>
</Query>
```
This makes it hard to debug in Banks and adds noise.
Add a new `useQueries` based on `useQuery` that returns an object
will all the responses.
queryConnect2 uses this hook to provide thoses responses as props …
> feat: Connection to multiple queries with less nesting

- docs/api/cozy-client.md
- packages/cozy-client/src/models/permission.js
- packages/cozy-client/src/models/permission.spec.js
`fetchOwn` was only used in `findPermissionFor`, but it is generally useful to load and parse our own permissions. In https://github.com/cozy/cozy-drive/pull/2017 for example, we don't want to know the permissions for a certain document, we need them for the general permission set.
> feat: Expose permission.fetchOwn

- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
- packages/cozy-client/src/associations/HasOne.js
- packages/cozy-client/src/associations/HasOne.spec.js
Problem: In banks, if a relationship is badly set to `null`, operations are not shown. 
Explanation: When retrieving operations, we retrieve also their relationship, via the query generated by the relationship, here `HasOne`. Since `relationship` was null, `relationship._id` failed and broke the retrieval of operations.
Why was `relationship` null ? Because when setting the category on a document that had not been linked to a recurrence, the dehydrated doc had its `relationships.recurrence.data` set to `null`. This is dealt with in https://github.com/cozy/cozy-client/pull/702/commits/2c5eeca71b6687bcf806591764e8cd3ce5575a7b. Now, when a document is not linked to another document, the relationships is not dehydrated at all, which prevents the creation of a useless …
> fix: Fixes to HasOne relationship

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/DocumentCollection.js
The create method has no jsdoc and I suppose this is why the create method is not visible in
https://docs.cozy.io/en/cozy-client/api/cozy-stack-client/#DocumentCollection
> docs: Make DocumentCollection.create visible in the documentation

- docs/api/cozy-stack-client.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-stack-client/src/CozyStackClient.js
- packages/cozy-stack-client/src/__tests__/CozyStackClient.spec.js
CozyClient passes the onTokenRefresh callback with options.onTokenRefresh.
This is not a breaking change since application that do set `cozyStackClient.onTokenRefresh` will still work after this change (since we call `this.onTokenRefresh` when receiving the token).
> fix: Correctly call callback for tokenRefresh passed in options

- docs/api/cozy-client.md
- docs/api/cozy-stack-client.md
- package.json
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
- packages/cozy-client/src/__tests__/fixtures.js
- packages/cozy-client/src/__tests__/store.spec.js
- packages/cozy-client/src/hooks/useFetchJSON.spec.js
- packages/cozy-client/src/queries/dsl.js
- packages/cozy-client/src/queries/dsl.spec.js
- packages/cozy-client/src/store/__snapshots__/queries.spec.js.snap
- packages/cozy-client/src/store/queries.js
- packages/cozy-client/src/store/queries.spec.js
- packages/cozy-client/src/testing/utils.js
- packages/cozy-stack-client/src/AppCollection.js
- packages/cozy-stack-client/src/Collection.js
- packages/cozy-stack-client/src/CozyStackClient.js
- packages/cozy-stack-client/src/DocumentCollection.js
- packages/cozy-stack-client/src/FileCollection.js
- packages/cozy-stack-client/src/OAuthClient.js
- packages/cozy-stack-client/src/PermissionCollection.js
- packages/cozy-stack-client/src/SharingCollection.js
- packages/cozy-stack-client/src/TriggerCollection.js
- packages/cozy-stack-client/src/__tests__/CozyStackClient.spec.js
- packages/cozy-stack-client/src/errors.js
- packages/cozy-stack-client/src/index.js
- File creation via client.create('io.cozy.files', { ... })
- Query keep their sort order if it has been configured at
query definition
> File creation + keep query sorted

- packages/cozy-pouch-link/src/CozyPouchLink.js
- packages/cozy-pouch-link/src/CozyPouchLink.spec.js
Query definitions support a `getByIds` method that is handled by the StackLink, but was so far ignored by the PouchLink.
> feat: Support query defs with multiple ids in pouch link

- packages/cozy-client/src/store/queries.js
- packages/cozy-client/src/store/queries.spec.js
`lodash.sortBy` is case-sensitive when ordering strings, whereas the stack is not. This PR removes the case-sensitivity from our sort.
> fix: Client-side query sort is case insensitive

- packages/cozy-client/src/store/queries.js
- packages/cozy-client/src/store/queries.spec.js
When receiving a query result, queries using `getByIds` would always be affected by new results, even if they had different ids.
> fix: Support multiple ids in store query updates

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/FileCollection.js
- packages/cozy-stack-client/src/FileCollection.spec.js
`FileCollection.statById` supports pagination, but in a way that is incompatible with the stack. The [stack route](https://docs.cozy.io/en/cozy-stack/files/#get-filesfile-id) expects a [JSON API style pagination](https://docs.cozy.io/en/cozy-stack/jsonapi/#pagination) with URL params such as `page[limit]` or `page[skip]`, but we only send plain `limit` and `skip` which are ignored.
I also added support for cursor based pagination, which involves supporting a `page[cursor]` param, and returning the `links` part of the response to get the next cursor.
> fix: FileCollection.statById pagination

- docs/api/cozy-pouch-link.md
- docs/mobile-guide.md
- packages/cozy-pouch-link/src/CozyPouchLink.js
- packages/cozy-pouch-link/src/PouchManager.js
- packages/cozy-pouch-link/src/PouchManager.spec.js
- packages/cozy-pouch-link/src/jsonapi.js
- packages/cozy-pouch-link/src/jsonapi.spec.js
PouchLink can now be configured to replicate certain doctypes only in one direction, which is useful for `io.cozy.files` for example that can't be replicated to the stack, but we'd still like to have the content in the local database. 
The API is debatable; fo the main use case (bi-directional replication), I think the current API is great (`new PouchLink({
doctypes: ['io.cozy.whatever'] })`) and doesn't need to move. I added support for a second, more advanced format, which is `new PouchLink({
doctypes: { readWrite: ['io.cozy.whatever'], readOnly: ['io.cozy.files'] } })`. It's flexible, duplication free and extandable with a `writeOnly` if we ever need that.
This PR also adds detection for next pages when results are paginated with `skip` and `limit`, which is how the `pouch.find` API …
> PouchLink improvements

- packages/cozy-client/src/hooks/useQuery.js
- packages/cozy-client/src/hooks/useQuery.spec.jsx
- packages/cozy-client/src/mock.js
- packages/cozy-client/src/queries/dsl.js
- packages/cozy-client/src/testing/utils.js
- fetchMore returning a promise is in line with ObservableQuery.fetchMore
- queries don't always have a bookmark to fetch more data, especially when coming from pouch
> fix: Use query support fetchMore without bookmark + fetchMore return

- docs/api/cozy-pouch-link.md
- packages/cozy-pouch-link/src/CozyPouchLink.js
- packages/cozy-pouch-link/src/CozyPouchLink.spec.js
Pouch replication can be : 
- time consuming 
- resource consuming
Dispatching those events give the opportunity to the app to react differently. For instance, I don't want to launch the "photo backup process" on Drive if Pouch is doing its replication since both are very expensive
> feat: Emit event during PouchLifeCycle

- packages/cozy-client/src/models/file.js
- packages/cozy-client/src/models/file.spec.js
`models.files.splitFilename` used to throw an error if the file had an empty string as a name, which is the case for the root folder. But it's still a valid file name, we shouldn't throw an exception in that case.
> fix: Split file name accepts empty names

- packages/cozy-client/src/models/file.js
- packages/cozy-client/src/models/file.spec.js
The file normalization was introduced in #602 but there seems to be a confusion between _type and type. `type` can be either `file` or `directory` and is added by the stack. `_type` refers to the doctype and is added by cozy-client.
> fix: Normalize _type but not type

- packages/cozy-stack-client/src/SettingsCollection.js
- packages/cozy-stack-client/src/SettingsCollection.spec.js
We can query the /settings routes through cozy-client, but these routes don't really return a document. Theywill especially tend not to include an `id` field which causes queries to end in error.
With this PR we now use an arbitrary document id  when there is none in the response.
> fix: Always have response ids for settings routes

- packages/cozy-client/src/queries/dsl.js
- packages/cozy-client/src/queries/dsl.spec.js
`null` values are sent through JSON and are interpreted by the stack, which can lead to errors when specifying invalid bookmarks. `undefined` on the other hand has the desired behavior of not being seriliazed to JSON.
> fix: Reset other offsets in queries

- .travis.yml
- docs/react-integration.md
- jest.config.js
- package.json
- packages/cozy-client/package.json
- packages/cozy-client/src/RealTimeQueries.jsx
- packages/cozy-client/src/RealTimeQueries.spec.jsx
- packages/cozy-client/src/index.js
- yarn.lock
This PR brings the RealTimeQueries component from drive to cozy-client, allowing documents of a given doctype to stay up to date through the realtime plugin.
> feat: RealTimeQueries component

- packages/cozy-pouch-link/src/PouchManager.js
Since we introduced the concept of strategy we can use
PouchDB.replicate or PouchDB.sync. But both don't share the
same API for the change's event.
see https://pouchdb.com/api.html#replication
and https://pouchdb.com/api.html#sync (see example response)
> fix: Take the right path to get the docs

- docs/api/cozy-client.md
- packages/cozy-client/src/models/contact.js
- packages/cozy-client/src/models/contact.spec.js
Add method to get primary cozy url domain only (withtout protocol part, and subdomain if 'www')
> feat: Add getPrimaryCozyDomain in contact models

- packages/cozy-client/src/models/contact.js
- packages/cozy-client/src/models/contact.spec.js
displayName is the name displayed for a contact. If the contact has no name and email, the cozy url is used. In that case, we don't want to show the protocol or pathname of the url, only the domain.
> fix: Get cozyDomain instead of primaryCozy for contact displayName

- packages/cozy-client/src/models/contact.js
- packages/cozy-client/src/models/contact.spec.js
- The method to get index by FamilyNameGivenNameEmailCozyUrl returns now an empty object instead of empty string when empty. This is a little trick to get empty value at the end, according to https://docs.couchdb.org/en/2.3.1/ddocs/views/collation.html#collation-specification
- Besides, the method capitalize the returned value to simplify things for sorting contacts in the application
- getInitials() now deals with cozy url and empty name object
> fix: Method to get contact index and contact initials

- packages/cozy-client/src/cli/index.js
When scope was not passed to createClientInteractive, the error
was a bit difficult to understand.
> feat: Throw if scope is not passed

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/PermissionCollection.js
- packages/cozy-stack-client/src/PermissionCollection.spec.js
Use Case: We want to be able to create permission for all kind of doctype. Today, we can do that with createSharingLink() but this method is too much paired to Files. 
We want here, to be able to create a permission with want we want, for instance : 
```
permissions: { groups: { type: GROUPS_DOCTYPE, verbs: ['GET'] }, contacts: { type: CONTACTS_DOCTYPE, verbs: ['GET'] } }
```
Before the change, we're able to do that, but we can't specify the `codes` we want to produced. Now we can create myCode1 and myCode2 : 
```
create({codes: 'myCode1,myCode2', permissions: { groups: { type: GROUPS_DOCTYPE, verbs: ['GET'] }, contacts: { type: CONTACTS_DOCTYPE, verbs: ['GET'] } } }
==> response 
shortcodes: {"myCode1": "adcdef", "myCode2": "abfdgds"}.
```
BREAKING CHANGE: By default, we defaulted the …
> feat: We can pass a codes argument at the perm creation

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/PermissionCollection.js
- packages/cozy-stack-client/src/PermissionCollection.spec.js
We can add a ttl param in order to create temporary permission. The permission will expire after this ttl
> feat: Add ttl params to create Permissions

- .eslintrc.json
- docs/api/cozy-client.md
- docs/api/cozy-stack-client.md
- package.json
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/ObservableQuery.js
- packages/cozy-client/src/Query.jsx
- packages/cozy-client/src/associations/HasMany.js
- packages/cozy-client/src/associations/HasManyFiles.js
- packages/cozy-client/src/helpers.js
- packages/cozy-client/src/hoc.jsx
- packages/cozy-client/src/hoc.spec.jsx
- packages/cozy-client/src/registry.js
- packages/cozy-stack-client/src/AccessToken.js
- packages/cozy-stack-client/src/CozyStackClient.js
- packages/cozy-stack-client/src/FileCollection.js
- packages/cozy-stack-client/src/OAuthClient.js
- packages/cozy-stack-client/src/urls.js
- yarn.lock
If queryConnect had one of its collection whose queryOpts was a
function, for the "query" and "as" to change based on props, there
was a problem : the queryDefinition would not change based on props,
and it would keep the 1st queryDefinition. This was due to reassignment
to function params.
After fixing the bug, and adding a test, I activated the eslint rule
to have it as errors, and fixed the other cases in all the repo.
Here is a simple example of the bug:
```
const hoc = queryOpts => Component => {
return props => {
queryOpts = typeof queryOpts === "function" ? queryOpts(props) : queryOpts;
Component(queryOpts)
}
}
const queryOpts = props => ({ docId: props.id })
const Component = queryOpts => {
console.log('Rendering the component', queryOpts)
} 
const hComponent = …
```
> Fix query props

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/PermissionCollection.js
- packages/cozy-stack-client/src/PermissionCollection.spec.js
If we have more than 30 sharing by links (/sharing-by-links is paginated at 30 per default), we had a bug when deleting a file with a related sharing. 
We now fetch all the sharing by links (by following resp.links.next) and then we map on them to check if they are concerned by the removal. If yes, we destroy the permission.
> fix: Revoke sharing links fetch all the related permissions

- packages/cozy-client/src/CozyClient.spec.js
- packages/cozy-client/src/__tests__/store.spec.js
- packages/cozy-client/src/store/documents.js
- packages/cozy-client/src/store/documents.spec.js
Previously, deleted documents were removed from queries, but the doc
was staying in the documents slice. This is problematic in the case
of relationships since the "parent" document linked to a document
that has been deleted, will still see the deleted document.
This is also problematic if we simply rely on the documents slice to
know if a document is deleted or not.
This PR fixes both situations.
> fix: Remove deleted document from store

- docs/api/cozy-client.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
- packages/cozy-client/src/Query.spec.jsx
- packages/cozy-client/src/cli/index.js
- packages/cozy-client/src/store/index.js
- packages/cozy-client/src/store/queries.js
- packages/cozy-client/src/store/queries.spec.js
This fixes a long standing bug : #526
Previously, after an initial load of data through query(), subsequent calls
to query() would set the fetchStatus to loading. It causes a problem in
case of fetchPolicy : if the fetchPolicy returns false, the
receiveQueryResult will never been dispatched and queryState.fetchStatus 
will stay to false.
To prevent the problem, an additional loadQuery call is introduced which 
sets the fetchStatus to loading. initQuery now does not set the fetchStatus
to loading if the query already has been fetched.
> Fix: initQuery doesn't set fetchStatus: loading on queries for noninitial calls

- docs/api/cozy-client.md
- packages/cozy-client/src/models/file.js
- packages/cozy-client/src/models/file.spec.js
We now have a type of file that's a bit special:
- they are `io.cozy.files`
- they are shortcut files (.url files)
- they point to a sharing preview page
- they get deleted when the sharing is accepted
I've added some functions to help us work with them in the files model.
> feat: Add model functions to deal with sharing shortcuts

- packages/cozy-client/src/models/contact.js
- packages/cozy-client/src/models/contact.spec.js
- packages/cozy-client/src/store/queries.js
- packages/cozy-client/src/store/queries.spec.js
**Problem to solve :** 
Before that, if we used nested attributes in `sortBy()` it was ignored and no sorting was done in cozy-client. As a consequence, after editing a document, the sorting was not done again if a new request was not launched. The documents remained in their original position.
**Improvements :** 
- We can now use `sortBy()` with nested attributes like `sortBy([{ 'deep.property': 'asc' }])` as we do here https://github.com/cozy/cozy-contacts/blob/master/src/helpers/queries.js#L57
- getIndexByFamilyNameGivenNameEmailCozyUrl() now tranforms the index in lower case (not capitalize) to match this :  https://github.com/cozy/cozy-client/blob/fix/queries/packages/cozy-client/src/store/queries.js#L176
- getIndexByFamilyNameGivenNameEmailCozyUrl() now return `null` (instead of …
> Client-side query sort can use deep objects properties

- docs/api/cozy-client.md
- packages/cozy-client/examples/complex-query.js
- packages/cozy-client/src/queries/dsl.js
- packages/cozy-client/src/queries/dsl.spec.js
- packages/cozy-pouch-link/src/CozyPouchLink.spec.js
- packages/cozy-pouch-link/src/mango.js
BREAKING CHANGE: in the absence of an `indexFields` directive, the
attributes order in a `where` selector will matter to create the index.
To force an attributes order for an index, use `indexFields`.
We used to sort the index fields to build its name, e.g.
"by_date_and_type", which allows to keep the same order independently
from their position in the `where` selector.
However, this breaks the `indexedFields` behavior: because of the sort,
the fields might be indexed in a wrong order, e.g. `[type, date]` will
actually produce a `[date, type]` index. As the order is important
in Mango, this can break some queries.
We remove this sort to be consistent with
[cozy-stack-client](https://github.com/cozy/cozy-client/blob/ea768adecaf0dd1c52e9876bf68e86d099579a9b/packages/cozy-stack-client/src/Doc …
> fix: Do not sort fields for index name

- packages/cozy-pouch-link/src/CozyPouchLink.js
- packages/cozy-pouch-link/src/CozyPouchLink.spec.js
We need to pass the index to the query so pouch knows which index to use. As a side effect, it was creating each mrview 2 times, which is very costful for instances with many documents, e.g. thousands.
Note this was already done in [stack-client](https://github.com/cozy/cozy-client/blob/master/packages/cozy-stack-client/src/DocumentCollection.js#L359), which is again related to https://github.com/cozy/cozy-client/issues/786 ;)
> fix: Use index for PouchDB mango queries

- packages/cozy-pouch-link/src/CozyPouchLink.js
- packages/cozy-pouch-link/src/CozyPouchLink.spec.js
PouchLink should not forward if this is a read only operation when the
sync strategy is read only.
> fix: PouchLink should not forward if this is a read only operation

- docs/api/cozy-client.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
To get a CozyClient instance from data injected by the stack in the DOM
in the main page
fixes issue #799
> feat: Add fromDOM method

- packages/cozy-client/src/hooks/useQuery.js
Otherwise we had warning for queries that were for multiple docs
and it makes no sense for them to add singleDocData in the options.
> fix: Do not show singleDocData warning for non single doc queries

- packages/cozy-stack-client/src/AppCollection.js
- packages/cozy-stack-client/src/__tests__/AppCollection.spec.js
This is not breaking but this is deprecating the get with only the slug.
```patch
- Q('io.cozy.apps').getById('banks') // Deprecated
+ Q('io.cozy.apps').getById('io.cozy.apps/banks') // OK
```
This is because otherwise we have an erroneous behavior when loading
all konnectors then only one.
```js
await client.query(Q('io.cozy.konnectors').getById('konn'), { as: 'konn' })
await client.query(Q('io.cozy.konnectors'), { as: 'konnectors' })
```
At this point "konn" query will have nothing in its `data` since the doc
id was cleared out of the query by the filtering that cozy-client does
when receiving new documents, since the id "io.cozy.konnectors/konn"
does not correspond to the id in the queryDefinition "konn".
To prevent this behavior, we have to include the full id when doing the
query.
To …
> feat: When an app/konnector is fetched by id, doctype should be present

- docs/api/cozy-client.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
- packages/cozy-client/src/Schema.js
- packages/cozy-client/src/associations/HasManyFiles.js
- The relationships attribute in CozyClient::create should only be used
for references. Here, it's made clearer by renaming the attribute to
references and by adding documentation
- In the case of references, if the relationship class does not
support them, we throw before creating the document, since the developer should probably use
the relationship attribute directly in the document (probably managing the relationship attribute
with helpers from HasMany)
> Fix document creation with relationships

- packages/cozy-client/src/associations/HasMany.js
- packages/cozy-client/src/associations/HasMany.spec.js
- packages/cozy-client/src/associations/__snapshots__/HasMany.spec.js.snap
We can setHasManyItem on a document that don't
have relationships yet.
> fix: HasMany helpers

- docs/api/cozy-stack-client.md
- packages/cozy-client/src/StackLink.js
- packages/cozy-stack-client/src/FileCollection.js
- packages/cozy-stack-client/src/FileCollection.spec.js
Deprecate fetchFileContent and replace it by fetchFileContentById()
> fix: Rename fetchFileContent to fetchFilecontentById

- packages/cozy-client/package.json
- packages/cozy-client/src/logger.js
- packages/cozy-pouch-link/package.json
- packages/cozy-pouch-link/src/logger.js
- yarn.lock
Let's use the cozy's fork of minilog to support `octal literals in strict mode`
> fix: Use cozy's fork of minilog

- packages/cozy-stack-client/src/PermissionCollection.js
CozyStack now includes the sharing member in
GET /permissions/self
This is used to have informations about the
member of the sharing. Specially if the
instance field is filled, it means that the
shortcut for this sharing has been created to
its cozy.
> feat: GetOwnPermissions returns included

- bin/build
- docs/api/cozy-client.md
- jest.config.js
- packages/cozy-client/src/assets/qualifications.json
- packages/cozy-client/src/models/document.js
- packages/cozy-client/src/models/document.spec.js
- packages/cozy-client/src/models/file.js
- packages/cozy-client/src/models/file.spec.js
- packages/cozy-client/src/models/index.js
This PR:
* Add the new qualification.json model
* Implement helpers so apps/konnectors can automatically qualify documents based on their labels
* Implement setters to customize the qualification
* Implement integrity checks on the qualification
* Add tests
* Add doc
Next steps:
* Update the documentation [here](https://github.com/cozy/cozy-doctypes/blob/master/docs/io.cozy.files_metadata.md#administrative-documents) and maybe add a how-to in cozy-client.
* Develop a migration service in Cozy Drive to requalify files having the old qualification
* Use the new qualification in cozy-scanner
* Use the new qualification in the concerned konnectors
> Document qualification

- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
https://github.com/cozy/cozy-client/commit/03e46d12574b897a76af925917b8d944fec4d929 introduced a bug that makes any call to `client.create` fails with `ReferenceError: document is not defined`
> fix: Use correct var in create

- packages/cozy-client/src/assets/qualifications.json
This qualification is useful for telecom bills grouping both mobile and box invoices. The konnector might specify "internet" and "phone" in the subjects
> feat: Add telecom invoice qualification

- docs/api/cozy-client.md
- docs/api/cozy-stack-client.md
- packages/cozy-client/src/models/permission.js
- packages/cozy-client/src/models/permission.spec.js
- packages/cozy-stack-client/src/PermissionCollection.js
- packages/cozy-stack-client/src/PermissionCollection.spec.js
- packages/cozy-stack-client/src/SharingCollection.js
- packages/cozy-stack-client/src/SharingCollection.spec.js
- Add get on sharing doctype to be able to client.query(client.get('io.cozy.sharings', sharingId))
- Add isShortcutCreatedOnTheRecipientCozy (from Drive, but we'll need it in Notes and others apps using sharing / permission)
> feat: Sharing get & permission check shortcut

- packages/cozy-client/src/assets/qualifications.json
This is useful to always have a 'other' choice in the Drive themes.
> feat: Add others qualifications

- docs/getting-started.md
- docs/react-integration.md
- docs/relationships.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
- packages/cozy-client/src/__tests__/ObservableQuery.spec.js
- packages/cozy-client/src/__tests__/StackLink.spec.js
- packages/cozy-pouch-link/src/CozyPouchLink.spec.js
- packages/cozy-stack-client/src/__tests__/KonnectorCollection.spec.js
By separating query building and result fetching, it is clearer which
method build queries, and which methods retrieve results.
By deprecating those two methods, we make it clear that for query
building, Q is the recommended way, and for executing a query,
client.query is to be used.
> feat: Deprecate query helpers on the client

- packages/cozy-client/src/registry.js
- packages/cozy-client/src/registry.spec.js
This will allow a cleaner solution to the growing number of connectors
and apps in the store application.
The next step is to add proper pagination handling for this collection.
See https://github.com/cozy/cozy-store/pull/705#issuecomment-739244759
for more context
> feat: Allow registry collection fetch to have a limit parameter

- packages/cozy-client/src/assets/qualifications.json
This qualification is useful for receipt docs, for instance, coming from [the tax](https://github.com/konnectors/impots/blob/master/src/metadata.js#L71)
> feat: Add receipt qualification

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/PermissionCollection.js
- packages/cozy-stack-client/src/PermissionCollection.spec.js
By passing tiny=true in the Query String, we can now create a tiny
shortcode composed by only 6 digits.
Cozy-Stack has a few conditions to enable this tiny shortcode. ATM, we
have to specify a ttl < 1h to be able to do so.
I didn't want to "hardcode" these conditions here since they can change,
so I linked to the cozy-stack documentation
Added by https://github.com/cozy/cozy-stack/pull/2813
> feat: Can create tiny code (6 digits)

- docs/getting-started.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
- packages/cozy-pouch-link/package.json
- packages/cozy-stack-client/package.json
- packages/cozy-stack-client/src/DocumentCollection.js
- packages/cozy-stack-client/src/DocumentCollection.spec.js
- packages/cozy-stack-client/src/FileCollection.js
- yarn.lock
Add  a `perfs.execution_stats` flag that enables an `execution_stats` flag for find queries, to get insights about query execution: https://docs.couchdb.org/en/2.3.1/api/database/find.html#execution-statistics
> feat: Support for perfs.execution_stats flag 

- docs/api/cozy-client.md
- packages/cozy-client/src/models/file.js
This was previously done by cozy-doctypes, but seems more relevant in cozy-client that handles the qualification model: https://github.com/cozy/cozy-libs/blob/master/packages/cozy-doctypes/src/administrativeProcedures/AdministrativeProcedure.js#L57
> feat: Add helper to get files by qualification rules

- packages/cozy-client/src/models/file.js
The query was filtering 'file' to exclude directories, but it was on a wrong field: `class` is used to differentiate file type, e.g. 'pdf', 'image', etc, as stated [in the doc](https://github.com/cozy/cozy-doctypes/blob/master/docs/io.cozy.files.md#files).
And, in any case, this filtering is useless, as we index on the `metadata.qualification` field, which will exclude directories.
> fix: Do not filter on class

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/Collection.js
- packages/cozy-stack-client/src/DocumentCollection.js
- packages/cozy-stack-client/src/DocumentCollection.spec.js
Note this is temporary workaround as we realized that https://github.com/cozy/cozy-client/pull/857 might require extra work to avoid recomputing all indexes.
Sometimes, an app might run 2 concurrent queries on the same index. If
this index happens to be not created yet, it might result into a
creation conflict. In cozy-drive, this was causing an interface error,
which is a pity as this only occur for new users leading to a bad
first impression.
Here, we fix this by simply retrying the index creation when a
conflict is detected.
Furthermore, we plan to improve the index creation in a nearby
future to avoid unecessary index creation requests.
> feat: Handle index conflicts

- packages/cozy-client/src/associations/HasOne.js
- packages/cozy-client/src/associations/HasOneInPlace.js
- packages/cozy-client/src/hooks/useCapabilities.jsx
client.get is deprecated. Q is preferred as it can be used statically (no
need for a cozy-client) and more versatile as you can build any query
with it (with client.find and client.get, you are limited, to Q::where()
and Q::getById()).
> feat: Use Q instead of client.get

- packages/cozy-client/src/associations/HasManyFiles.js
A depreciation warning was triggered each time a HasMany file was used
> refactor: Use new Q API to avoid warning on files relationships

- packages/cozy-client/src/StackLink.js
- packages/cozy-client/src/registry.js
- packages/cozy-client/src/registry.spec.js
- packages/cozy-stack-client/src/AppCollection.js
- packages/cozy-stack-client/src/KonnectorCollection.js
- packages/cozy-stack-client/src/__tests__/AppCollection.spec.js
**Besoin :** On souhaite pouvoir récupérer depuis la stack les données d'un connecteur grâce à son id (slug), prioritairement depuis la `stack`, ou depuis la `registry` si la `stack` renvoie une erreur.
**Modifications :** Ajout de la possibilité de définir une ou des sources lors d'une requête d'une app par son id, en passant un tableau en valeur de l'attribut `sources` d'une requête : 
```
qDef = Q('io.cozy.konnectors').getById('io.cozy.konnectors/slug')
qDef.sources = ['stack', 'registry']
```
Cet exemple retourne le connecteur selon son `slug`, depuis la première source (ici la `stack`) si possible, sinon depuis la deuxième (ici la `registry`).
Cette modification n'est pas dans le DSL pour le moment mais directement dans l'`AppCollection`.
> feat: Add possibility to use sources props to a get query

- .gitignore
- packages/cozy-stack-client/src/TriggerCollection.js
- packages/cozy-stack-client/src/TriggerCollection.spec.js
When query definition had a type, /data/io.cozy.triggers was fetched
instead of '/jobs/triggers'.
> fix: Add type to path

- jest.setup.js
- packages/cozy-client/src/CozyClient.spec.js
- packages/cozy-client/src/ObservableQuery.spec.js
- packages/cozy-client/src/Provider.spec.jsx
- packages/cozy-client/src/StackLink.spec.js
- packages/cozy-client/src/__tests__/console.js
- packages/cozy-client/src/associations.spec.js
- packages/cozy-client/src/store.spec.js
- packages/cozy-client/src/withMutation.spec.jsx
- packages/cozy-client/src/withMutations.spec.jsx
- packages/cozy-stack-client/src/utils.spec.js
- Move spec files near implementation
Test files are easier to find and imports from the spec file match
imports from the implementation file.
- Make console warn and errors fail during tests
This makes it easier to enforce a no-warning-during-tests policy.
> Test improvements

- packages/cozy-client/src/associations/HasOneInPlace.js
- packages/cozy-client/src/associations/HasOneInPlace.spec.js
A previous refactor broke the data() method from HasOneInPlace.
A test is added so that we do not make the same kind of mistake
in the future
> fix: HasOneInPlace correctly gets its data

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/Collection.js
- packages/cozy-stack-client/src/DocumentCollection.js
- packages/cozy-stack-client/src/DocumentCollection.spec.js
- packages/cozy-stack-client/src/FileCollection.js
- packages/cozy-stack-client/src/TriggerCollection.spec.js
- packages/cozy-stack-client/src/mangoIndex.js
- packages/cozy-stack-client/src/mangoIndex.spec.js
We used to have a pessimistic index creation strategy: for each find
query, a index creation query was sent to the database, and ignored if
the index was already created.
Most of the time, these index creation queries are useless, as the index
is created when the app is first used.
Therefore, we now adopt an optimistic strategy, that is, running the
find query, and create the index afterwards only if a missing index is
returned.
It also now creates a named index, i.e. `_design/by_selector_field` and
catch index creation conflicts.
This fixes  https://github.com/cozy/cozy-client/issues/719
EDIT 04/02/20
As mentioned [here](https://github.com/cozy/cozy-client/pull/857#issuecomment-766918762), the first draft of this PR had the drawback to force the re-creation of all existing indexes. So, …
> feat: Optimistic index creation

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/Collection.js
- packages/cozy-stack-client/src/DocumentCollection.js
- packages/cozy-stack-client/src/DocumentCollection.spec.js
- packages/cozy-stack-client/src/mangoIndex.js
This fixes 2 things introduced with #857
* For some queries, CouchDB returns a `no_usable_index` error, instead of a `no_index` error when the index is missing. 
Therefore, we handle this case to create the index after this error 
* For indexes with a partial index, we sort the fields to ease the comparison when looking for existing indexes. This sort was changing the original `indexedFields`, leading to potentially wrong index definition
> Fixes for optimist index

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/SharingCollection.js
- packages/cozy-stack-client/src/SharingCollection.spec.js
By default, Cozy-Stack gets the app_slug from the token.
But we can define the app_slug when creating the sharing. In that case
the cozy-stack will use this slug in the mail sent for a cozy-to-cozy
sharing.
It enables the fact, that the app1, can generate a link to an app2.
> feat: Can use app_slug when creating a sharing

- docs/api/cozy-client.md
- packages/cozy-client/src/models/fsnative.js
- packages/cozy-client/src/models/fsnative.spec.js
to easily open a file on mobile devices in an external app
Méthode rapatriée de Drive https://github.com/cozy/cozy-drive/blob/master/src/drive/web/modules/actions/utils.js#L178
Les throw ont été ajustés pour que l'`Alerter` soit exécuté dans l'app et non dans cozy-client, de la manière : 
```
try {
await openFileWith(client, file)
} catch (error) {
Alerter.info(`Viewer.error.${error}`, { fileMime: file.mime })
}
```
> feat: Add openFileWith in fsnative

- packages/cozy-stack-client/src/DocumentCollection.js
- packages/cozy-stack-client/src/DocumentCollection.spec.js
Lors d'une toute première requête sans option sur un index inexistant, donc avec un indexedFields undefined, la fonction plantait au moment de la création du nom de l'index, la méthode utilisée `getIndexNameFromFields` prend indexedFields comme argument
> fix: HandleMissingIndex can now deal with undefined indexedFields

- docs/api/cozy-client.md
- packages/cozy-client/src/models/timeseries.js
It probably makes more sense to have an interval query with symmetric operators, i.e. `$gte` and `$lte`, to avoid confusion
> feat: Make interval query consistent on operators

- packages/cozy-client/src/authentication/mobile.js
In node environment, window is not defined.
> fix: Do not assign window to win if window is not defined

- packages/cozy-stack-client/package.json
- yarn.lock
When used in a node environment, an error was thrown because of
cozy-flags using react.
See https://github.com/cozy/cozy-libs/pull/1269
> fix: Upgrade cozy-flags to avoid error in node env

- packages/cozy-client/src/cli/index.js
Saw this when trying to resolve a "fetch" is not a function in a service
from the home.
After investigation:
- Home services try do their polyfill if global.fetch is not yet defined
- global.fetch is already defined
- this because cozy-client/dist/cli.js is exported from index.node.js
- global.fetch was assigned at the module level in cli.js
When doing this fix, global.fetch is not polyfilled here and is
polyfilled directly by the service of the home.
I think we should improve how we polyfill, it is still a bit unclear but
right now, we expect the service to polyfill fetch themselves.
It is in the documentation: docs/node.md.
With this fix, there is no surprise, since the assignment to global is
done in the main, and no more at import level : if you do not use the
cli.js main, …
> feat: Do not polyfill at the module level

- docs/api/cozy-client.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/Query.jsx
- packages/cozy-client/src/__tests__/mocks.js
- packages/cozy-client/src/types.js
- packages/cozy-client/types/CozyClient.d.ts
- packages/cozy-client/types/Query.d.ts
- packages/cozy-client/types/__tests__/mocks.d.ts
- packages/cozy-client/types/cli/index.d.ts
- packages/cozy-client/types/types.d.ts
When instantiating a client from the DOM, the client has
the "capabilities" attributes filled.
I also changed the signature of the fromDOM call, to have
the selector in second, it is a breaking change but I checked and we do not use fromDOM much yet:
```
notes
libs
contacts
drive
store
banks
src/ducks/client/web.js
settings
src/lib/client.js
home
```
I'll take care of changing the call in Banks.
> Add capabilities inside cozy-client

- packages/cozy-client/src/CozyClient.js
If the selector cannot be found, we should not ignore the error and
return undefined. Better to throw explicitly
> feat: Throw instead of returning undefined in fromDOM

- packages/cozy-client/package.json
- packages/cozy-pouch-link/package.json
- yarn.lock
This update will remove a pinned dependency on lodash from
cozy-device-helper.
This resulted in warnings like :
WARNING in lodash
Multiple versions of lodash found:
4.17.15 ./~/cozy-client/~/cozy-device-helper/~/lodash
4.17.19 ./~/lodash
> feat: Update cozy-device-helper

- docs/api/cozy-stack-client.md
- packages/cozy-pouch-link/src/CozyPouchLink.js
- packages/cozy-stack-client/src/DocumentCollection.js
- packages/cozy-stack-client/src/DocumentCollection.spec.js
- packages/cozy-stack-client/src/TriggerCollection.spec.js
- packages/cozy-stack-client/src/mangoIndex.js
- packages/cozy-stack-client/src/mangoIndex.spec.js
This fixes two things: 
- queries missing the `_design/` prefix on index name
- new index wrongly created after a creation (see description of 154728f )
- old indexes with inconsistent states (see 0bbbd9d and its description)
> Fix failing index

- docs/react-integration.md
- packages/cozy-client/src/hooks/useQuery.js
- packages/cozy-client/src/testing/utils.js
The original issue is https://github.com/cozy/cozy-client/issues/910, drazik found out that without ReduxProvider, useQuery failed : it uses the default useSelector from redux that expects to have the redux context provided by redux provider.
Here, the useSelector used in useQuery is created from the client context, meaning that it works by getting the store from the cozy-client context instead of the redux context. An app is no longer required to wrap its app with ReduxProvider to use `useQuery`.
> Remove need for Redux provider

- docs/api/cozy-pouch-link.md
- packages/cozy-pouch-link/package.json
- packages/cozy-pouch-link/src/PouchManager.js
- packages/cozy-pouch-link/src/PouchManager.spec.js
- packages/cozy-pouch-link/src/helpers.js
- packages/cozy-pouch-link/src/localStorage.js
- packages/cozy-pouch-link/src/remote.js
- packages/cozy-pouch-link/src/startReplication.js
- packages/cozy-pouch-link/src/startReplication.spec.js
- yarn.lock
At initialization time, we used to replicate docs from CouchDB to
PouchDB by using the replication protocol. This is problematic
because it replicates the revision history, making the indexing
potentially slower and increasing the database size.
Moreover, the replication protocol is also slower than just queyring
the _all_docs and inserting the documents in bulk.
Here are some numbers we measured on a database with 10K docs and
about 100K updates:
* Replication with CouchDB replication protocol: 34s
* Includes revision history
* Replication with _all_docs + bulk insert: 13s
* Does not include revision history
* Indexing with revisions: 38s
* Indexing without revisions: 26s
Note this only concern the initial replication, we continue to use the
CouchDB replication protocol for the next …
> Init replication

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/JobCollection.js
- packages/cozy-stack-client/src/JobCollection.spec.js
This allows to set a job's state.
This will only work for jobs of @client type. For this type of jobs, the client side launcher needs to set the result of the job itself since it is not launched in the stack's
environment.
> feat: Add job setState

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/FileCollection.js
- packages/cozy-stack-client/src/FileCollection.spec.js
- packages/cozy-stack-client/src/__snapshots__/FileCollection.spec.js.snap
We add methods to list, add and remove synchronization exclusions for
a given OAuth client.
These will be used to configure which directories should be
synchronized with a given Desktop client.
> feat: Add synchronization exclusions methods

- packages/cozy-stack-client/src/TriggerCollection.js
- packages/cozy-stack-client/src/TriggerCollection.spec.js
The trigger api allows the specification of multiple Workers like we already to for the `type` parameter
Now, if you want to get multiple types of workers in on request, you can do :+1: 
```javascript
await collection.find({worker: { $in: ['client', 'konnector']})
```
> feat: Handle multiple workers in TriggerCollection.find

- packages/cozy-client/src/mock.js
During tests, it can be useful to instantiate a query with null to test edge cases, for example testing a component to see that it does not crash while the query has not been loaded yet.
EDIT: better description
> feat: Allow to pass null to instantiate a query

- packages/cozy-client/README.md
`yarn typecheck` should be run after `yarn build` on repository's root
If not TS may not be able to resolve dependencies between `cozy-client`
and `cozy-stack-client`
> docs: Add build instructions required to run `yarn typecheck`

- docs/api/cozy-client.md
- packages/cozy-client/src/associations/Association.js
- packages/cozy-client/src/associations/HasMany.js
- packages/cozy-client/src/associations/HasManyFiles.js
- packages/cozy-client/src/associations/HasManyInPlace.js
- packages/cozy-client/src/associations/HasOne.js
- packages/cozy-client/src/associations/HasOneInPlace.js
- packages/cozy-client/src/models/timeseries.js
- packages/cozy-client/types/associations/Association.d.ts
- packages/cozy-client/types/associations/HasMany.d.ts
- packages/cozy-client/types/associations/HasManyInPlace.d.ts
- packages/cozy-client/types/associations/HasOne.d.ts
- packages/cozy-client/types/associations/HasOneInPlace.d.ts
- packages/cozy-client/types/models/timeseries.d.ts
Those modifications are needed to make `cozy-pass-web` compilation work as this project is in Typescript.
Two modifications has to be discussed : 
- `timeseries.js` : TS was unable to type `fetchTimeSeriesByIntervalAndSource` arguments.
- I removed deconstruction from parameters so it is easier to add type to it. But maybe there is another way do document types for destructured params?
- I typed it with `TimeSeries` and I added the optional `limit` member to existing `@typedef`. I don't have enough knowledge on this project to tell if it should has its own type instead of reusing `TimeSeries`.
- `Association.js` : this class is inherited by `HasOneInPLace`, `HasOne`, `HasManyInPlace`, and `HasMany`.
- Each of those children override `query()` but with 3 parameters.
- Typescript complains …
> fix: improve types for cozy pass web

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/FileCollection.js
- packages/cozy-stack-client/src/FileCollection.spec.js
- packages/cozy-stack-client/src/__snapshots__/FileCollection.spec.js.snap
Before the sanitize function was only called
during the creation of a file not during the 
update.
> fix: Updating a file also sanitize its name

- packages/cozy-client/src/store/__snapshots__/queries.spec.js.snap
- packages/cozy-client/src/store/queries.js
- packages/cozy-client/src/store/queries.spec.js
- packages/cozy-client/types/types.d.ts
- yarn.lock
We had a crash when sorted queries that are updated from a response
have ids for documents that have been deleted. In this case,
the properId helper would crash since it expects documents. A
filtering pass after retrieving each document is necessary to
remove deleted documents ids from the query state.
> fix: Remove docs ids that have been removed from docs slice

- docs/api/cozy-client.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/types/CozyClient.d.ts
Improved documentation by using correct type on `CozyClient.fromDOM` instead of generic `object`
> feat: Improve type documentation for CozyClient.fromDOM

- packages/cozy-client/src/CozyClient.js
Forgotten in the precedent commit
> fix: Remove useless omit import

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/DocumentCollection.js
- packages/cozy-stack-client/src/DocumentCollection.spec.js
Fetch changes needs to have the docs included in the changes response
since it filters null documents, deleted documents, and design docs.
With include_docs: false, fetchChanges was not functional, thus it makes
no sense to support it. Now, the caller of fetchChanges doesn't need to
pass include_docs: true, it is set automatically by
DocumentCollection::fetchChanges.
Fix https://github.com/cozy/cozy-client/issues/966
See https://github.com/cozy/cozy-banks/pull/2124/commits/b358741e8949e9e158194e84ca77e94e02695902 for an example of bug that can be avoided with this change (include_docs: true had been forgotten, thus no doc changes were returned).
> feat: Include_docs is done by default by fetchChanges

- packages/cozy-client/src/authentication/mobile.js
This log was mistakenly removed in a previous [commit](https://github.com/cozy/cozy-client/commit/390f46d47c8c80917c93d518ac201a1b40868329?branch=390f46d47c8c80917c93d518ac201a1b40868329&diff=unified#diff-e879aaa33e459b749f1f68b01b84a2faf1fccd65cc819c96e7afc6c8bcbb2c36L168) but it is necessary to authenticate in standalone mobile mode for apps such as Drive.
> fix: Restore the log URL for mobile authentication

- packages/cozy-client/package.json
@types should not be in `dependencies` but `devDependencies`
This may create interferences with other @types in projects where cozy-client is imported
> fix: Move @types to devDependencies

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/SharingCollection.js
- packages/cozy-stack-client/src/SharingCollection.spec.js
In order to implement folders and ciphers sharing inside of Cozy Pass we need to implement rules that are specific to Bitwarden's organizations
Note: in the Cozy's context, a folder is equivalent to a Bitwarden's organization containing a single collection with the same name. That's why the name "folder" doesn't appears in this new code
This PR is needed for https://github.com/cozy/cozy-pass-web/pull/32
> feat: Add sharing rules for bitwarden organizations

- packages/cozy-client/package.json
In a previous commit abd847ce4bb29f405fc80109fd78f65fd780d5f2 (https://github.com/cozy/cozy-client/pull/987), I moved `@types/xxx` from `dependencies` to `devDependencies` but I was wrong.
Some of those types are exposed to the package's API and may be manipulated by consuming apps.
For example : 
- `index.js` contains `export { default as compose } from 'lodash/flow'`
- `CozyClient.js` declares `getIncludesRelationships` which contains `return fromPairs(....`. This function is from `lodash` and return a lodash `Dictionary`
Due to this the generated `.d.ts` file will contain references to lodash :
```ts
getIncludesRelationships(queryDefinition: any): import("lodash").Dictionary<any>;
```
Then consuming TS apps (here `cozy-pass-web`) will require to install `@types/lodash` in order to …
> fix: Move @types back to dependencies

- docs/api/cozy-pouch-link.md
- packages/cozy-pouch-link/src/CozyPouchLink.js
- packages/cozy-pouch-link/src/PouchManager.js
- packages/cozy-pouch-link/src/localStorage.js
- packages/cozy-pouch-link/src/migrations/adapter.js
- packages/cozy-pouch-link/src/migrations/adapter.spec.js
- packages/cozy-pouch-link/src/utils.js
PouchDB can use different kind of adapter, e.g. idb, sqlite, etc.
We want to be able to migrate the adapter, typically to use the new and
more performant IndexedDB adapter.
To perform such migration, we run a local replication between the old
and new database instance. By doing so, the user can migrate its data
without requiring an internet connection.
Note the migration can take some time, i.e. several minutes depending on
the device, the database size, etc.
It is the responsability of the app to to call the `migrateAdapter` API
and handle this migration on the UI level.
Once the adapter is migrated, the old database is removed, and the page
reloaded so the client will use the new Pouch. The adapter name is saved
in the localstorage to inform the app which adapter should be used.
> Add API for Pouch migration

- docs/api/cozy-client/classes/registry.md
- packages/cozy-client/src/registry.js
- packages/cozy-client/src/registry.spec.js
- packages/cozy-client/types/registry.d.ts
Getting the latest version of a channel is need by amiral app to be able to get the source code of the conector latest version of the channel installed on cozy-stack
> feat: Add registry.fetchAppLatestVersion

- docs/api/cozy-client/classes/registry.md
- packages/cozy-client/src/registry.js
- packages/cozy-client/src/registry.spec.js
- packages/cozy-client/types/devtools/Pouch.d.ts
- packages/cozy-client/types/registry.d.ts
The stack's registry API also allow to get a specific version of an app
and this is needed by the amiral app.
This is a breaking change since the fetchAppLatestVersion won't exist
anymore, but it is not used yet. I think it is safe to replace it now.- feat: Replace fetchAppLatestVersion by fetchAppVersion
> feat: Replace fetchAppLatestVersion by fetchAppVersion

- docs/api/cozy-client/classes/cozyclient.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
- packages/cozy-client/src/__snapshots__/CozyClient.spec.js.snap
- packages/cozy-client/types/CozyClient.d.ts
- packages/cozy-pouch-link/src/CozyPouchLink.js
- packages/cozy-pouch-link/src/CozyPouchLink.spec.js
- packages/cozy-pouch-link/src/PouchManager.js
- packages/cozy-pouch-link/src/jsonapi.js
- packages/cozy-pouch-link/src/jsonapi.spec.js
**Contexte :** 
Sur mobile, lors d'un `queryAll` on ne sortait jamais de la boucle `while` car l'attribut `next` ne basculait jamais à `false`. De plus on s'appuie sur le même comportement que `query` en utilisant `offsetBookmark` ou `offset` selon si on a un `bookmark` ou non.
**Correctif :** 
- ajout d'attributs `_rev` et `_deleted` au document lors de la suppression sur mobile (iso desktop)
- correction de l'attribut `next` pour Pouch
- `queryAll` a maintenant un comportement proche de celui de `query`
On avait le souci dans banks, sur mobile, lors de la suppression d'un compte.
> fix queryAll

- docs/api/cozy-client/classes/stacklink.md
- docs/api/cozy-client/interfaces/models.permission.document.md
- docs/api/cozy-client/interfaces/models.permission.permission.md
- docs/api/cozy-client/interfaces/models.permission.permissionitem.md
- docs/api/cozy-client/modules/models.file.md
- docs/api/cozy-client/modules/models.folder.md
- docs/api/cozy-client/modules/models.permission.md
- packages/cozy-client/src/StackLink.js
- packages/cozy-client/src/associations/HasManyFiles.js
- packages/cozy-client/src/associations/HasManyFiles.spec.js
- packages/cozy-client/src/cli/index.js
- packages/cozy-client/src/const.js
- packages/cozy-client/src/models/file.js
- packages/cozy-client/src/models/folder.js
- packages/cozy-client/src/models/fsnative.js
- packages/cozy-client/src/models/permission.js
- packages/cozy-client/types/const.d.ts
When using a HasManyFiles relationship, we can manipulate documents from
the referenced doc, or from the referencing doc.
Let's assume the following photo albums:
```
{
_id: '1234'
_type: 'io.cozy.photos.albums'
}
```
And the following file, with a reference to the album:
```
{
_id: '5678'
_type: 'io.cozy.files',
referenced_by: [
{
id: '1234'
type: 'io.cozy.photos.albums'
}
]
}
```
Previously, it was only possible to query the files from the album.
But, we might want to query the album directly from the file. This is
what we add here, by querying documents specified in the `referenced_by`
relationship specified in the file, through their id.
> feat: Allow to query a HasManyFiles relation in both ways 

- docs/api/cozy-pouch-link.md
- packages/cozy-pouch-link/src/CozyPouchLink.js
It can be useful for an app to know which adapter is currently used, typically to
perform adapter migration.
Fix https://github.com/cozy/cozy-client/issues/1005
> feat: Expose method to get the adapter name

- packages/cozy-pouch-link/src/CozyPouchLink.js
This was causing a migration failure.
> fix: Correcty iterate over object keys

- packages/cozy-pouch-link/src/CozyPouchLink.js
in order to use it without instantiating PouchLink
Car nous avons besoin d'utiliser cette méthode avant l'instanciation de PouchLink, afin de déterminer comment instancier un new PouchLink.
> fix: Method to get adapter name should be static

- packages/cozy-stack-client/src/CozyStackClient.js
- packages/cozy-stack-client/src/CozyStackClient.spec.js
This commit from ~~[me](https://i.kym-cdn.com/photos/images/original/001/079/173/ed2.png)~~ @Crash-- fixes `refreshToken()` to work with the new `data-cozy-*` form.
> fix: Refresh CozyStackClient Token

- packages/cozy-stack-client/src/OAuthClient.js
- packages/cozy-stack-client/src/OAuthClient.spec.js
Now, in a specific workflow we can receive an registerToken and
we need to pass it to the authorize endpoint
So let's use the oauthOptions to write it
documentation is currently tested with a partner. I'll write it down to cozy-client after the first iteration
> feat: Handle Onboarding V2

- packages/cozy-client/src/associations/HasManyFiles.js
- packages/cozy-client/src/associations/HasManyFiles.spec.js
When dealing with HasManyFiles relationships, the relationship might be
file->doc or doc->file. The former is specific as the the io.cozy.files
uses referenced_by: their data retrieval is now supported
> feat: Implement data retrieval for HasManyFiles

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/FileCollection.js
- packages/cozy-stack-client/src/FileCollection.spec.js
We used to expect the updated file to be a File object with its name set
directly inside the File.
However, we could also manipulate files as ArrayBuffer. Hence, it is
necessary to be able to pass the name as a param.
> feat: Pass name as param in updateFile

- packages/cozy-stack-client/src/FileCollection.js
- packages/cozy-stack-client/src/FileCollection.spec.js
We used to infer the file content-type only for File objects. However,
it can be useful to extend this for binary structs such as ArrayBuffer,
typically when dealing with encryption. Say we have decrypted a file,
represented as an ArrayBuffer: we have no way to know its content-type
without inferring it from the name, as it was previously encrypted with
a specific content-type.
> feat: Infer content-type from file extension

- packages/cozy-stack-client/src/SharingCollection.js
- packages/cozy-stack-client/src/SharingCollection.spec.js
When Alice delete an organization that is shared with Bob, then we
want to revoke Bob's access to this organization
This allow to cast a `deleted` realtime event to Bob so the
organization is removed from their vault without having to refresh the
client
> fix: Change sharing rule for `com.bitwarden.organizations`

- docs/api/cozy-client/classes/hasmany.md
- docs/api/cozy-client/classes/hasmanytriggers.md
- docs/api/cozy-client/classes/hasone.md
- docs/relationships.md
- packages/cozy-client/src/associations/HasMany.js
- packages/cozy-client/src/associations/HasMany.spec.js
- packages/cozy-client/src/associations/HasOne.js
- packages/cozy-client/src/associations/HasOne.spec.js
- packages/cozy-client/types/associations/HasMany.d.ts
- packages/cozy-client/types/associations/HasOne.d.ts
We used to have `addById/removeById` for has-many relationships and
`set/unset` for has-one relationships, with different behaviour:
has-many saves the relationship in database, but not has-one.
To be consistent, we add `save/remove` API for both relationships.
> feat: Use add and remove API for both has-one and has-many

- packages/cozy-client/src/store/documents.js
When there many documents in the same doctype, and queryAll is used to
fetch them all, it can be very slow. It looks like Cozy-Client is taking
more and more time between requests to update its state.
The extractAndMergeDocument function is used to merge the documents in
state and the documents in the response. It was iterating on both sets
of documents, which seems useless. By iterating on just the new
documents, it can be faster and avoid the growing time between requests.
> feat: Makes queryAll faster with many requests

- packages/cozy-stack-client/src/DocumentCollection.js
The hard limit on the `_normal_docs` route in cozy-stack is 1000, not
100.
> chore: Update comment about _normal_docs limit

- packages/cozy-client/package.json
- yarn.lock
We previously merged an upgrade of open.
But Since it requires node 12 now. Let's
create a breaking change in cozy-client
to do the things correctly.
> fix: Revert open upgrade

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/CozyStackClient.js
- packages/cozy-stack-client/src/OAuthClientsCollection.js
- packages/cozy-stack-client/src/OAuthClientsCollection.spec.js
The `io.cozy.oauth.clients` doctype is protected so we need to
manually build a collection to query it.
We only add the `all`, `get` and `destroy` methods as they can be used
right away in the Settings app.
> feat: Add OAuthClientsCollection

- docs/api/cozy-stack-client.md
- packages/cozy-client/src/RealTimeQueries.jsx
- packages/cozy-client/src/RealTimeQueries.spec.jsx
- packages/cozy-client/src/types.js
- packages/cozy-client/types/RealTimeQueries.d.ts
- packages/cozy-client/types/models/permission.d.ts
- packages/cozy-client/types/types.d.ts
- packages/cozy-stack-client/src/OAuthClientsCollection.js
- packages/cozy-stack-client/src/OAuthClientsCollection.spec.js
Using the `realtime` plugin and `RealTimeQueries` component with `io.cozy-oauth.clients` documents would not work for 2 reasons:
1. the realtime subscriptions would always set documents' doctype to `io.cozy.files`, no matter what data they would receive
2. the `OAuthClientsCollection.destroy()` method would expect cozy-stack to return data while the `DELETE /settings/clients/:id` route only returns a response header when successful
> Fix OAuth clients' realtime updates

- docs/api/cozy-client/classes/hasmany.md
- docs/api/cozy-client/classes/hasmanytriggers.md
- packages/cozy-client/src/CozyClient.spec.js
- packages/cozy-client/src/associations/HasMany.js
- packages/cozy-client/src/associations/HasManyFiles.js
- packages/cozy-client/src/associations/HasManyFiles.spec.js
- packages/cozy-client/types/associations/HasMany.d.ts
- packages/cozy-stack-client/src/FileCollection.js
- packages/cozy-stack-client/src/FileCollection.spec.js
- packages/cozy-stack-client/src/__snapshots__/FileCollection.spec.js.snap
We had two issues with files relationships:
* When adding/removing the answer from the stack is `{type, id}`, which was causing an issue in the store as we always expect a `_type`.
* When adding/removing, we call the dedicated stack routes from HasManyFiles, but we were trying to save the file again from HasMany association, which is useless (it's only relevant for relationships different from io.cozy.files)
> Fix references

- packages/cozy-client/src/RealTimeQueries.jsx
- packages/cozy-client/src/RealTimeQueries.spec.jsx
- packages/cozy-client/src/types.js
- packages/cozy-client/types/types.d.ts
Although we tend to rely on the `_id` for all documents, we sometimes
also rely on `id`, which is a legacy that we encounter in some apps such
as Drive. Therefore, e23239fc2a17f8362a74dabdda0e3f816dfc6eb2 introduced
a regression in Drive as the `id` was missing.
> fix: Add id in CozyClientDocument for RealTime

- packages/cozy-client/src/models/file.js
This king of regex was not supported by Safari.
Let's revert it
This reverts commit 3d7cce2a8f7e185edfd86b137e13401dd561abcc.
> fix: Use regex supported by Safari

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/FileCollection.js
- packages/cozy-stack-client/src/FileCollection.spec.js
- packages/cozy-stack-client/src/__snapshots__/FileCollection.spec.js.snap
After updating a file's `referenced_by` attribute, `cozy-stack` will
not only return the updated file but also a `meta` object containing
the file's new revision and the file's new references count.
Fixes a regression introduced by https://github.com/cozy/cozy-client/pull/1048
> fix: Return meta after file's referenced_by update

- docs/api/cozy-client/classes/cozyclient.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
We offer 2 methods to build new `CozyClient` instances from an old
client built by `cozy-client-js`:
- `CozyClient.fromOldClient` to build WebApp clients
- `CozyClient.fromOldOAuthClient` to build OAuth clients
However, the options we passed to the `CozyClient` constructor when
building an OAuth client were not adequate and we ended up with a
WebApp client.
This would work most of the time though because of the way we make
requests to the Cozy and the fact that the OAuth token was still
passed but it would fail once we tried to refresh the token.
We're now extracting the OAuth credentials and scope from the old
client to instantiate the new one properly.
> fix: Build new OAuth client from old OAuth client

- packages/cozy-client/types/CozyClient.d.ts
This step was forgotten in the latest PR which was still merged.
> chore: Update types

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/FileCollection.js
- packages/cozy-stack-client/src/FileCollection.spec.js
We introduce a new method to fetch `io.cozy.files` changes from the
Cozy which does not go directly to CouchDB but uses the new
`cozy-stack` `/files/_changes` route.
This new route allows us to filter out trashed and deleted files from
the returned changes without using the CouchDB `selector` parameter
which can make queries really slow if the Cozy has lots of deleted
documents and thus time out.
This will be especially useful for the Desktop client.
This route has other benefits such as requesting specific fields or
for the path of files (i.e. as opposed to directories).
It also comes with limitations such as not being able to request
changes on specific documents via their ids.
This change is based on https://github.com/cozy/cozy-stack/pull/3200
and as such should probably not be merged …
> feat: Add FileCollection.fetchChanges() method

- docs/api/cozy-client/README.md
- docs/api/cozy-client/classes/querydefinition.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/queries/dsl.js
This is useful to know which query is involved by a warning message
> feat: Be more explicit on query warning messages

- docs/api/cozy-client/README.md
- packages/cozy-client/src/index.js
- packages/cozy-client/types/index.d.ts
On this PR #1076, the association helpers exports from the cozy-client index are missing
> fix: Re-export associations helpers

- docs/api/cozy-client/modules/models.file.md
- docs/api/cozy-stack-client.md
- packages/cozy-client/src/__tests__/fixtures.js
- packages/cozy-client/src/models/file.js
- packages/cozy-client/src/models/file.spec.js
- packages/cozy-client/types/__tests__/fixtures.d.ts
- packages/cozy-stack-client/src/FileCollection.js
- packages/cozy-stack-client/src/FileCollection.spec.js
- packages/cozy-stack-client/src/ShortcutsCollection.js
- packages/cozy-stack-client/src/ShortcutsCollection.spec.js
- packages/cozy-stack-client/src/__snapshots__/FileCollection.spec.js.snap
- packages/cozy-stack-client/src/getIllegalCharacter.js
- packages/cozy-stack-client/src/getIllegalCharacter.spec.js
To alert in Drive when filename contains illegal characters instead of 'the name already exists'
[waiting for equivalent MR in cozy-drive](https://github.com/cozy/cozy-drive/pull/2442)
> fix(filename): Get illegal characters from file name and returns them

- packages/cozy-stack-client/src/AppCollection.js
- packages/cozy-stack-client/src/AppCollection.spec.js
- packages/cozy-stack-client/src/KonnectorCollection.spec.js
- packages/cozy-stack-client/src/__tests__/fixtures/apps.js
- packages/cozy-stack-client/src/__tests__/fixtures/konnectors.js
Or else the id in the manifest would replace the stack's id
attribute in io.cozy.konnectors doctype
And this could cause a crash in the home application
> fix: Konnectors collection now ignores id in manifest

- docs/api/cozy-stack-client.md
- packages/cozy-client/src/models/permission.js
- packages/cozy-client/src/models/permission.spec.js
- packages/cozy-stack-client/src/PermissionCollection.js
- prevent warnings in app consuming permission
> fix: Use fetchOwnPermissions instead of deprecated getOwnPermissions

- packages/cozy-client/src/hooks/useQuery.js
- packages/cozy-client/src/hooks/useQuery.spec.jsx
fetch was missing from the API. So making
a request from <Query or with queryConnect
didn't share the same API than useQuery.
So let's fix it.
https://github.com/cozy/cozy-client/blob/master/packages/cozy-client/src/ObservableQuery.js#L49-L51
> fix: UseQuery returns fetch method

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/OAuthClient.js
Simple facade to get flagship app session_code without directly using the fetchJSON method
> feat: Add a method to get session_code

- packages/cozy-client/package.json
This modifies the compileSdkVersion from 27 to 28 to avoid a compile bug when looking for sdk28 components
> feat: Use lib alias for safetynet

- docs/api/cozy-client/README.md
- docs/api/cozy-client/classes/invalidcozyurlerror.md
- docs/api/cozy-client/classes/invalidprotocolerror.md
- packages/cozy-client/src/helpers.js
- packages/cozy-client/src/helpers.spec.js
- packages/cozy-client/src/index.js
- packages/cozy-client/src/index.node.js
- packages/cozy-client/types/helpers.d.ts
- packages/cozy-client/types/index.d.ts
- packages/cozy-client/types/index.node.d.ts
To help our users connect our applications to their Cozy, we want them
to be able to simply use any URL of their Cozy copied from their
browser as their Cozy URL (e.g.
`https://claude-drive.mycozy.cloud/#/folder/io.cozy.files.root-dir`).
Without this help, we would not recognize the above URL as a valid
Cozy URL and would refuse to attempt the connection.
The new `rootCozyUrl` helper will reduce it down to the user's Cozy
URL (e.g. `https://claude.mycozy.cloud`) and return it or reject if:
- the domain does not exist
- the provided protocol is not HTTP or HTTPS
- no instance could be found with the resulting URL
Since our applications can be connected to a self-hosted Cozy, we also
handle URL ports.
> feat: Add rootCozyUrl helper

- docs/api/cozy-client/classes/querydefinition.md
- docs/api/cozy-client/modules/models.folder.md
- docs/api/cozy-pouch-link.md
- docs/api/cozy-stack-client.md
- packages/cozy-client/src/RealTimeQueries.jsx
- packages/cozy-client/src/associations/HasManyFiles.js
- packages/cozy-client/src/flagship-certification/typedefs.js
- packages/cozy-client/src/queries/dsl.js
- packages/cozy-client/src/queries/dsl.spec.js
- packages/cozy-client/src/types.js
- packages/cozy-client/types/flagship-certification/typedefs.d.ts
- packages/cozy-client/types/queries/dsl.d.ts
- packages/cozy-client/types/types.d.ts
- packages/cozy-pouch-link/src/PouchManager.js
- packages/cozy-pouch-link/src/utils.js
- packages/cozy-stack-client/src/DocumentCollection.js
- packages/cozy-stack-client/src/FileCollection.js
- packages/cozy-stack-client/src/FileCollection.spec.js
- packages/cozy-stack-client/src/NotesCollection.js
- packages/cozy-stack-client/src/OAuthClientsCollection.js
- packages/cozy-stack-client/src/mangoIndex.js
- packages/cozy-stack-client/src/querystring.js
When `FileCollection.fetchChanges()` was introduced, we found that
Arrays in query-string parameters were not URI encoded in the standard
way and we had our own URL generation function in the `querystring`
module.
Since the new method would pass a `fields` Array parameter which
needed to be encoded in the standard way, we decided to use
`URLSearchParams()` to encode the parameters.
While this would work for this particular parameter, this broke
pagination when a CouchDB view cursor would be used as this cursor is
an Array and needs the custom encoding.
Therefore, we're reverting the previous decision to use
`URLSearchParams` and go back to using our own `querystring` module to
generate URLs.
Since the `fields` parameter in the `fetchChanges()` method was in
fact already turned into a …
> fix: Generate FileCollection URLs with querystring

- packages/cozy-stack-client/src/FileCollection.js
- packages/cozy-stack-client/src/FileCollection.spec.js
close #690 #699 
We can now use xhr to upload file in order to get process callback. But it comes with a drawback... For security reason, Chromium based browser, don't let us set the Date header for a file. (https://bugs.chromium.org/p/chromium/issues/detail?id=38382 & https://stackoverflow.com/questions/6973403/chrome-extension-refuse-header-date-in-ajax-request/6974039 )
We use now a QueryString updated_at & created_at in order to avoid using this Date header.
It needs a modification of cozy-stack to accept this new updated_at QS.
https://github.com/cozy/cozy-stack/blob/master/web/files/files.go#L153-L163
> feat(file): Fill last modified date in UpdatedAt path query string

- packages/cozy-client/src/store/documents.js
- packages/cozy-client/src/store/documents.spec.js
In Banks, we noticed the reference of the state.cozy.documents[doctype]
does not change when we refetch more transaction.
This was dued to extractAndMergeDocument that created a new
mergedData object but providing again the same properties.
Our property that got updated, from 1000 documents to 1500, was still
inside the same reference, so reselect did not recompute after store
got updated, and users faced this bug while moving from home page with
reimbursements, users see old reimbursements from home/transactions
instead of seeing the full reimbursements fetched on Reimbursements page.
when removing memoize options and adding `console.log('documents', documents ? Object.keys(documents).length : 0)` inside documentSelector line 72 => …
> fix(documents): Reducer should assign new object for concerned doctype

- packages/cozy-stack-client/src/JobCollection.js
- packages/cozy-stack-client/src/JobCollection.spec.js
We had the capacity to launch trigger `manually`. But there was no way to create a `manual` job. 
Since https://github.com/cozy/cozy-stack/pull/3308 we can create the job with the `manual` argument. 
What is this `manual` stuff? By default, jobs are queued and the gozy-worker enqueue the jobs progressively. But sometimes, we need to run a job as quick as possible since the user is currently waiting for the response of the job. To achieve that, we have this concept of `manual` job. The job is still async, but not in the `global` queue. 
This is needed when we want to launch the banking connector to get a temporary token in order to create the account on the BI's side.
> feat: Add Manual to Job creation

- packages/cozy-client/src/flagship-certification/flagship-certification.js
- packages/cozy-client/src/flagship-certification/flagship-certification.spec.js
- packages/cozy-client/src/flagship-certification/store-attestation.js
Flagship certification heavily depends on the Google and Apple official
stores API
Not every devices are compatible with those API like for iOS old
devices or F-Droid based devices
We don't want to block those devices' users so we allow them to certify
the app using alternative 2FA verification
The 2FA verification is handled by the cozy-stack so we only need to
continue the OAuth flow instead of throwing an error
This requires cozy/cozy-stack#3287
> feat: Ignore flagship certification failure to allow 2FA certification

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/CozyStackClient.js
- packages/cozy-stack-client/src/getIconURL.js
- packages/cozy-stack-client/src/getIconURL.spec.js
Need upgrade in cozy-ui as well + test + working without breaking change
https://github.com/cozy/cozy-ui/pull/2064
> fix(stack-client): Get Icon Url uses preloaded url when oAuth not needed

- packages/cozy-stack-client/src/FileCollection.js
- packages/cozy-stack-client/src/FileCollection.spec.js
[Drive] Régression : le téléversement d’un fichier dont le nom contient une esperluette « & »tronque le no
m
> fix(upload): Handle Ampersand characters in file name while xhr used

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/getIconURL.js
- packages/cozy-stack-client/src/getIconURL.spec.js
some AppIcon contains only a slug, so appData was undefined, breaking Home icons used by konnectors
> fix(stack-client): Fetch icon url when no appData and slug is passed

- packages/cozy-client/src/models/document/locales/fr.json
energy_invoice is not only for electricity, correction the fr locale, english one is OK.
> fix: Correct fr locale 'facture d'énergie' in cozy-client

- packages/cozy-client/src/models/dacc.js
- packages/cozy-client/src/models/dacc.spec.js
- packages/cozy-client/src/types.js
This provides an API to send measures to the DACC through a remote
doctype and check the parameters to ensure their correctness.
> feat: Add DACC model

- packages/cozy-client/src/assets/qualifications.json
- packages/cozy-client/src/models/document/locales/en.json
- packages/cozy-client/src/models/document/locales/fr.json
This is useful for online grocery bills, or grocery receipts.
> feat: Add grocery invoice qualification

- docs/api/cozy-client/modules/models.md
- docs/api/cozy-client/modules/models.sharing.md
- packages/cozy-client/src/const.js
- packages/cozy-client/src/models/index.js
- packages/cozy-client/src/models/sharing.js
- packages/cozy-client/src/models/sharing.spec.js
- packages/cozy-client/types/const.d.ts
- packages/cozy-client/types/models/index.d.ts
- packages/cozy-client/types/models/sharing.d.ts
Added `getSharingLink` function to generate a sharing link for one or more files.
This function already exists in different libraries like `cozy-sharing` or `cozy-mespapiers-lib`, and soon in `cozy-ui`.
So I think it's good to centralize it in `cozy-client`.
> feat: Add getSharingLink function

- docs/api/cozy-client/interfaces/models.file.FileUploadOptions.md
- docs/api/cozy-client/modules/models.file.md
- docs/api/cozy-stack-client.md
- packages/cozy-client/src/CozyClient.spec.js
- packages/cozy-client/src/models/file.js
- packages/cozy-client/src/models/file.spec.js
- packages/cozy-client/src/types.js
- packages/cozy-client/types/models/file.d.ts
- packages/cozy-client/types/types.d.ts
- packages/cozy-stack-client/src/FileCollection.js
- packages/cozy-stack-client/src/FileCollection.spec.js
This introduces the `encrypted` field in the io.cozy.files, used to determine if a file is client-side encrypted.
Note this `encrypted` attribute will be simply ignored by the stack as long as this [PR](https://github.com/cozy/cozy-stack/pull/3378) isn't merged.
> Encrypted attribute in io.cozy.files

- docs/api/cozy-client/classes/CozyClient.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
In our ReactNative app we will need to display cozy-apps from a webview
served from a local HTTP Server
By doing so, the webview's base URL is using an unsecure `http`
protocol
As cozy-client's URI is often created using `window.location.protocol`
then it would register itself to the cozy-stack using the same unsecure
`http` protocol from the webview's base URL
With current code, cozy-client has no clue if it should trust
`window.location.protocol` or not
As this info is known by the ReactNative app, we should to inject the
information into the webview by using the
`window.cozy.isSecureProtocol` global object
So when `new CozyClient()` is called, if `window.cozy.isSecureProtocol`
is set to true, then cozy-client now transforms the URI's protocol into
a secure `https` one
> feat: Add secure protocol to URI when window.cozy.isSecureProtocol=true

- packages/cozy-client/package.json
- packages/cozy-pouch-link/package.json
- yarn.lock
BREAKING CHANGE: We need to upgrade cozy-device-helper
in order to be able to run cozy-client within a node
context. So let's upgrade it.
You need to install cozy-device-helper >= 2.1.0 in
your app.
> fix: Cozy-Client runs on node

- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
We should not rely on `window` since CozyClient can be used in a Node env. 
This commit https://github.com/cozy/cozy-client/commit/3a9d557bbf70f6c7a30acbdad225000b40a23215 introduced a regression for our app's services.
> fix: CozyClient can be used in a node env

- packages/cozy-stack-client/src/FileCollection.js
- packages/cozy-stack-client/src/FileCollection.spec.js
When updating a file we might either want to update its CouchDB
attributes, e.g. the name, or the binary itself.
To do so, the app used to go through the collection, and call `.update`
for attributes or `.updateFile` to update the binary.
It is now possible to directly use `client.save` for both cases. When a
`data` attribute is passed to the document, is is considered as a binary
update.
> feat: Support client.save for files 

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/OAuthClient.js
This endpoint is similar to `POST /auth/login`, but it allows the
flagship app to also obtain OAuth access and register tokens without
having to make the OAuth dance (which can be awkward for the user)
Related PR: cozy/cozy-stack#3400
> feat(cozy-stack-client): Add loginFlagship entry point

- docs/api/cozy-client/README.md
- docs/api/cozy-client/classes/QueryDefinition.md
- packages/cozy-client/src/queries/dsl.js
- packages/cozy-client/src/queries/dsl.spec.js
- packages/cozy-client/types/queries/dsl.d.ts
- packages/cozy-pouch-link/src/CozyPouchLink.spec.js
When a `.select` is used in a query definition, it MUST includes all
the fields expressed in the selector and partial index. This is because
we evaluate queries on the store thanks to sift, and it requires to have
all the necessary fields to evaluate the query. If one is missing, the
query will return nothing.
See this example:
```
Q('io.cozy.todos).where({date: $gt: { null}}).select(['name'])
```
When this query will be run, only the todos name will be in the store.
Then, when later evaluated in the store, sift won't find any todos with
a date ; thus it will return nothing and consider all the existing todos
should be removed from the store.
> feat: Throw an error when fields do not include all searched attributes

- docs/api/cozy-client/interfaces/models.dacc.Params.md
- docs/api/cozy-client/modules/models.dacc.md
- packages/cozy-client/src/models/dacc.js
- packages/cozy-client/src/models/dacc.spec.js
- packages/cozy-client/src/types.js
- packages/cozy-client/types/models/dacc.d.ts
- packages/cozy-client/types/types.d.ts
This will be useful for apps aiming to fetch aggregates from the DACC, e.g. coachCO2.
Also, it copes with the remote-doctype change: https://github.com/cozy/cozy-doctypes/pull/201/files
> feat: Add method to fetch DACC aggregates

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/DocumentCollection.js
- packages/cozy-stack-client/src/DocumentCollection.spec.js
- packages/cozy-stack-client/src/mangoIndex.js
- packages/cozy-stack-client/src/mangoIndex.spec.js
When using a partial index, its fields weren't part of the index name.
Therefore, we might have a conflict situation where there is already an
existing index without the partial index.
Fix https://github.com/cozy/cozy-client/issues/1054 and https://github.com/cozy/cozy-client/issues/1091
> feat: Add the partial filter fields in the index name

- packages/cozy-client/src/store.spec.js
- packages/cozy-client/src/store/documents.js
- packages/cozy-client/src/store/documents.spec.js
When we merge object with the spread operator, it
doesn't make a deep merge, it replace the second
level.
Exemple:
```js
d1 = {a: 1, b: {b1: 1}}
d2 =  {c: 3, b: {b2: 2}}
merge = {...d1, ...d2}
// merge = { a: 1, b: { b2: 2 }, c: 3 }
```
This is not what we want in this case. We want a
fully merged object, not a replace. We expect the
result to be:
```
// mege = { a : 1, b { b1: 1, b2: 2}, c: 3}
```
To achieve that, we use lodash merge!
Fix #1175
(credits to @paultranvan for the finding!)
> fix: Make a correct deep merge on objects.

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/Collection.js
- packages/cozy-stack-client/src/DocumentCollection.js
- packages/cozy-stack-client/src/DocumentCollection.spec.js
- packages/cozy-stack-client/src/mangoIndex.js
- packages/cozy-stack-client/src/mangoIndex.spec.js
When a partial filter is defined and the index is not created yet,
CouchDB might fallback on another existing index and return a warning
saying the specified index was not used.
This is not what we want, because the existing index might not actually
use the partial filter and make a full-scan on the index to evaluate
it.
> Fix partial filter

- packages/cozy-stack-client/src/DocumentCollection.js
- packages/cozy-stack-client/src/DocumentCollection.spec.js
We were checking only in resp.warning, but we can also have this warning in resp.meta.warning. 
We now handle the both case
> fix: Check the correct path to get the warning

- packages/cozy-stack-client/src/CozyStackClient.js
- packages/cozy-stack-client/src/CozyStackClient.spec.js
- packages/cozy-stack-client/src/OAuthClient.js
- packages/cozy-stack-client/src/OAuthClient.spec.js
Previous `fetchJSON` and `refreshToken` implementation called
`onTokenRefresh()` before `setToken()`, which would result to emitting
`tokenRefreshed` event with cozy-client not being updated yet
___
Related PR:
- https://github.com/cozy/cozy-react-native/pull/313
___
TODO:
> fix: Call `onTokenRefresh()` after `setToken()` when refreshing token

- packages/cozy-client/src/store/documents.js
- packages/cozy-client/src/store/documents.spec.js
By not creating a new object, we kept the same
referencial equality and then some components
that checked this equality was not re-rendering.
> fix: Lodash.merge is not creating a new object

- docs/api/cozy-client/README.md
- docs/api/cozy-client/classes/InvalidCozyUrlError.md
- docs/api/cozy-client/classes/InvalidProtocolError.md
- packages/cozy-client/src/helpers.js
- packages/cozy-client/src/helpers.spec.js
- packages/cozy-client/src/index.js
- packages/cozy-client/src/types.js
- packages/cozy-client/types/helpers.d.ts
- packages/cozy-client/types/index.d.ts
- packages/cozy-client/types/types.d.ts
Sometimes we have to manipulate Cozy's URLs as strings and we want to
deconstruct them to retrieve data like slug, or Cozy's name
This is the case on `cozy-notes` as we can retrieve a `returnUrl` from
the URL's searchParams. In a mobile app, we wan't to extract the target
slug from the `returnUrl` so we can call `openApp()` for this slug
In order to ease the process, `deconstructCozyWebLinkWithSlug()`
requires the Cozy's URL to contain a slug
Without knowing if the URL contains a slug or not, it would be not
possible to correctly extract data from the URL as we can't guess if a
part of the URL should be a subdomain, or if it contains a slug
___
Related PRs:
- https://github.com/cozy/cozy-notes/pull/318
- https://github.com/cozy/cozy-ui/pull/2206
> feat: Add `deconstructCozyWebLinkWithSlug` to extract data from Cozy url

- packages/cozy-stack-client/src/ContactsCollection.spec.js
- packages/cozy-stack-client/src/DocumentCollection.js
- packages/cozy-stack-client/src/DocumentCollection.spec.js
- packages/cozy-stack-client/src/FileCollection.spec.js
When no indexFields option is given in a query definition, the fields to
index are automatically generated to create the index.
However, this might be dangerous as the indexed fields might actually
not entirely comply with the query objective.
> feat: Add warning when selector fields are not indexed

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/DocumentCollection.js
- packages/cozy-stack-client/src/DocumentCollection.spec.js
- packages/cozy-stack-client/src/mangoIndex.js
Equivalent to .find() but fetching all documents, until resp.next is false.
Using the same API than .find()
> feat(stack-client): Add findAll method

- docs/api/cozy-client/classes/StackLink.md
- packages/cozy-client/src/StackLink.js
- packages/cozy-client/src/StackLink.spec.js
- packages/cozy-client/types/StackLink.d.ts
The idea is to check if there is some options
related to _find. If yes, then we should use
this route instead of {normal|all}_docs
Fix #1216
> fix: Use find method where args are for find

- packages/cozy-client/src/index.node.js
- packages/cozy-client/types/index.node.d.ts
In #1217 we forgot to expose this method from `index.node.js`
> fix: Export `deconstructCozyWebLinkWithSlug` from `index.node.js`

- docs/api/cozy-client/README.md
- docs/api/cozy-client/classes/CozyClient.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
- packages/cozy-client/src/hooks/useCapabilities.jsx
- packages/cozy-client/src/hooks/useCapabilities.spec.jsx
- packages/cozy-client/types/CozyClient.d.ts
Current cozy-client implementation calls `loadInstanceOptionsFromDOM`
when initialized
This method only works for web app clients, but would fail for OAuth
clients as those cannot rely on any DOM
To fix this we should retrieve client's options by calling the
cozy-stack
For now we only need to retrieve capabilities. But other props should
be implemented later
As this method is async, we don't want to call it from the constructor.
Instead we chose to call it at the end of `login()`. Which would also
allow to access token data when we will implement this part
___
This PR also modify `useCapabilities` hook to get `client.capabilities` if
it exists instead of fetching info from cozy-stack.
This introduce a breaking change (described in the commit)
___
After merging this, we should update the …
> feat: Fetch capabilities on OAuth login

- docs/api/cozy-client/interfaces/models.file.FileUploadOptions.md
- docs/api/cozy-client/modules/models.file.md
- packages/cozy-client/src/models/file.js
- packages/cozy-client/src/models/file.spec.js
During Drive search optimisation, the number of params of
the note got limited
That's why the isNote needs to check
only metadata title and version, no more
> fix(cozy-client): IsNote should validate note with less params

- packages/cozy-client/src/store/queries.js
- packages/cozy-client/src/store/queries.spec.js
- packages/cozy-client/types/store/queries.d.ts
We had an issue when using the creation mutation.
Document's slice was correctly updated but the
queries' one was not correctly updated. Some of
this date was right, not the other.
This is because since
0f2e8a3f2f13157723fa6395929476d66b860dec
&
d986f59781557a97ff2545b228153325d18307b9
We try to respect the Query Definition even with
a limitBy attribute. But we were using the wrong
data.
Since we're in a mutation context, we need to
use the mutated data, not the one we got during the
request. So instead of relying on old `count` from
the previous query, we rely on `updatedData`.length
to get the right information.
> fix: Fix store issue with creation mutation

- packages/cozy-stack-client/src/mangoIndex.js
- packages/cozy-stack-client/src/mangoIndex.spec.js
If we had an existing index with partial filter
but if we made a request with the same fields but
without partial filter, then isMatchingIndex
returned true and then we used it and then we
renamed it and we destroyed the existing index...
We fixed isMatchingIndex to check if
partialFilters are the same.
> fix: MatchingIndex with partialFilter

- packages/cozy-stack-client/src/DocumentCollection.js
- packages/cozy-stack-client/src/DocumentCollection.spec.js
When we have a mango request that tells us that the index is not used because not valid or not existing, we have a mechanism that fetch all the exising indexes and check if an index can be used for this request. If yes, then we do a few manipulation on it (like renaiming it), if no then we create it.
But in the meantime, since we've fetched all the indexes we check them for inconsistence. By inconsistence we mean that the name is not the right one based on the fields & partialFilterFields.
We use this mechanism to remove & migrate old indexes.
But we had a flaw in this mechanism: Sometimes, an application can launch several requests at the same time with the same index. This use case is valid.
Since the request are treated at the same time, we fetch several times the all existing indexes, …
> fix: Don't throw error when removing inconsistent indexes

- docs/api/cozy-client/classes/CozyClient.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
Sometimes query can error and its legitimate to do so. For instance, if the database doesn't exist yet or else. In that case, since queryAll() is about fetching all the docs and that API doesn't respect query() API, let's return an empty array without throwing anything.
queryAll should ba as close as possible than query() itself
> fix: QueryAll return empty array if error

- packages/cozy-stack-client/src/AppCollection.js
- packages/cozy-stack-client/src/AppCollection.spec.js
Any call to `collection('io.cozy.apps').getById('...')` with not-registry
source was failing to properly return data.
> fix: Get apps method was returning wrong type for not-registry source

- packages/cozy-stack-client/src/CozyStackClient.js
`fetchJSON()` enforce `credential:include` value in fetch options
In our Flagship mobile app, we want to be able to provide a custom value for this option
___
Related PRs:
- https://github.com/cozy/cozy-react-native/pull/425
> feat: Allow to provide `credential` value in `fetchJSON()` options

- docs/api/cozy-client/classes/CozyClient.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
Prefer to use process.env.COZY_CREDENTIALS format to choose
authentication mode sincecozy-jobs-cli does not set NODE_ENV=development
for cozy-konnector-dev command
[anymore](https://github.com/konnectors/libs/pull/851)
> feat: Do not use NODE_ENV=development to detect authentication

- docs/api/cozy-client/interfaces/models.file.FileUploadOptions.md
- docs/api/cozy-client/modules/models.file.md
- packages/cozy-client/src/models/file.js
- packages/cozy-client/types/models/file.d.ts
BREAKING CHANGE: Since the introduction of the photos' clustering, each photo is at least referenced by an automatic album. Therefore, this method which was used to know if a file was referenced by an album, will always return true, does not make sense anymore because it is not what we want to test.
Instead, we now want to see if a file is not referenced by an album that has not been created automatically. This implementation has been done in Drive directly in eb76c831b3deabd0857b9472451830831df5fb3a
Linked to https://github.com/cozy/cozy-drive/pull/2739
> fix: Remove isReferencedByAlbum

- packages/cozy-client/src/queries/dsl.js
We stringify the logged objects to avoid having `[object Object]`
> fix: Properly display objects in warning logs

- packages/cozy-stack-client/src/PermissionCollection.js
It is now more coherent because we expose only methods returning normalized permissions.
> feat: Method fetchPermissionsByLink normalizes permissions

- packages/cozy-client/src/store/queries.js
- packages/cozy-client/src/store/queries.spec.js
When we had a query with no selector but a partial index,
we were missing the sift evaluation.
> fix: Query definition replay with only a partialFilter

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/FileCollection.js
- We should not remove the reference before
deleting the file. cozy-stack needs to know
if the document was shared before moving it
to the Trash in order to revoke the sharing
- Use the route to remove all the referenced_by
by doing only one request instead of one by
reference.
> fix: Delete File

- packages/cozy-stack-client/src/FileCollection.js
- packages/cozy-stack-client/src/FileCollection.spec.js
When filename is used inside the URL we have
to encode it in order to avoid error.
Fix a downloading bug when a file
has "#test.png" as name.
> fix: Encode filename

- packages/cozy-client/src/index.node.js
- packages/cozy-client/types/index.node.d.ts
We centralise all queries into a queries.js file in application. fetchPolicies is often use in query from front-end. As we extract also query from service. Node tries to find fetchPolicies, it's create crashs (ex: [cozy-contact](https://github.com/cozy/cozy-contacts/pull/901)). As fetchPolicies is agnostic from react.js, we can expose to node and prevent future problem.
**Related PRs :**
- https://github.com/cozy/cozy-contacts/pull/901
> feat(index.node.js): Export fetchPolicies

- docs/api/cozy-client/modules/models.paper.md
- packages/cozy-client/src/models/paper.js
- packages/cozy-client/src/models/paper.spec.js
With a few exceptions (already covered), all papers qualifications should have the same treatment as the `residence_permit`.
> feat: Replace isExpiringResidencePermit function to another more generic

- docs/api/cozy-client/modules/models.paper.md
- packages/cozy-client/src/models/paper.js
- packages/cozy-client/src/models/paper.spec.js
Ajout d'un lien pour aider l'utilisateur lorsque son passeport est sur le point d'expiré.
Ainsi que la simplification de la fonction `computeExpirationNoticeLink`, ajoutée il y a quelques jours.
Son but étant de fournir un lien en fonction d'un label de qualification, elle n'a pas à être plus complexe que ça.
> Add helper link for passport

- packages/cozy-client/src/hooks/useQuery.js
- packages/cozy-client/src/hooks/useQuery.spec.jsx
It's a legit use case to have something like this:
```
const id = useParam('id');
const file = useQuery(Q('io.cozy.files').getById(id),
{
enabled: !!id
}
if(!id) return null
if(file.fetchStatus === 'loaded'){
return <File file={file.data} />
}
...
```
This case was failing beforce because getById() checks if the `id` is there or not. And since even if `enabled` was set to false we called the getById(), it throws an error.
This fix a part of https://github.com/cozy/cozy-client/issues/961
I don't know yet what to think about the `fetchStatus` equal to `pending` or `loaded` so I just added a test to be sure to create a BC if we change the behavior. But to me, the called should not rely on the result of the useQuery hook when enabled is set to false.
This fix also enable the fact to be able …
> fix: Do not call the queryDefinition if enabled is false

- docs/api/cozy-client/classes/CozyClient.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
- packages/cozy-client/src/__mocks__/cozy-stack-client.js
- packages/cozy-client/types/CozyClient.d.ts
- packages/cozy-client/types/__mocks__/cozy-stack-client.d.ts
We added to the login, the fetch of the cozy capabilities here https://github.com/cozy/cozy-client/pull/1227
Since then, we had error (not failure!) in tests saying we were missing async call...
So this commit fix this issue by:
- waiting the loginPromise if needed in the fromOldClient() method
- mocking the collection.get method to have the test passing. (we can't not mock stackclient by passing stackclient as the 2nd arg of this method because we'll bypass the all test because of that, so I had to mock it globally...)
> fix: Async login

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/OAuthClient.js
This will allow the flagship app to use a different token on each
connector launch, even from the same slug
> feat: Add new method to fetch konnector token in native context

- packages/cozy-stack-client/src/ContactsCollection.js
- packages/cozy-stack-client/src/ContactsCollection.spec.js
This problem appears when you only have partialIndex so the selector which is where return undefined. This problem was found into : https://github.com/cozy/cozy-contacts/pull/898
> fix(ContactsCollection): Check selector to prevent undefined

- packages/cozy-client/src/models/document/locales/en.json
Translation key `work_disability_recognition` was misnamed in EN translations when added here cozy/cozy-client@25e4953
> fix: Translation key `work_disability_recognition`

- packages/cozy-client/examples/simple-test-query.js
- packages/cozy-stack-client/src/DocumentCollection.js
- packages/cozy-stack-client/src/DocumentCollection.spec.js
Lodash merge modify the source object to apply the merge
on it.
That was causing errors on queries without `.indexfields` but with
selector and a partial filter.
In such situation, the final selector is a merge between the actual
selector and the partial index.
After the first query, the selector became the merge one.
Then, the query is replayed when the index is missing, this time with
a merged selector.
As the indexed fields were not specified, and we are using the
selector fields to guess them, the resulting index was wrong, as
partially based on the partial filter.
> fix: Do not modify selector with lodash merge

- docs/api/cozy-client/README.md
- packages/cozy-client/src/helpers.js
- packages/cozy-client/src/index.js
- packages/cozy-client/src/index.node.js
- packages/cozy-client/types/helpers.d.ts
- packages/cozy-client/types/index.d.ts
- packages/cozy-client/types/index.node.d.ts
since we have already replaced `generateWebLink`
> feat: Expose ensureFirstSlash method to replace the one in cozy-ui

- docs/api/cozy-client/classes/CozyClient.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
We had an issue on `mespapiers-lib` because mespapiers was sending an empty string instead of a boolean. And since this commit https://github.com/cozy/cozy-client/commit/c5b602256f3e4cd747734fa213500191eeb2e3c9 , we don't "resolve" the query definition. And since the `enabled` was not false, the query was executed https://github.com/cozy/cozy-client/blob/c5b602256f3e4cd747734fa213500191eeb2e3c9/packages/cozy-client/src/hooks/useQuery.js#L69-L72 (see https://github.com/cozy/cozy-libs/pull/1983/files) 
This is an alternative implementation of https://github.com/cozy/cozy-client/pull/1305 
I prefer the current approach because `query()` is the central point of cozy-client. If we use `<Query>` `client.query` `useQuery` `useQueryAll` , all these method pass to `CozyClient.query()`. It makes …
> fix: Throw error if enabled is not a boolean

- packages/cozy-client/src/models/document/locales/en.json
- packages/cozy-client/src/models/document/locales/fr.json
Une metadata `contractType` peut-être utilisé sur les files dans le cas d'une création d'un fichier qualifié `contrat de travail` (l'app MesPapiers par exemple ou plus tard un connecteur).
Dans ce cas, on stocke en valeur le type de contrat sous cette forme `cdi|cdd|alternate|internship`
On veut donc pouvoir traduire cette valeur dans la bonne langue, aussi bien dans les apps (MesPapiers), que les libs (cozy-ui). Nous stockons donc cette information dans cozy-client, récupérable depuis la méthode déjà existante `getBoundT`
> feat: Add contract type locales

- docs/api/cozy-client/classes/Registry.md
- packages/cozy-client/src/registry.js
- packages/cozy-client/types/registry.d.ts
Some methods of Registry, use stackClient method `fetchJSON` which return a promise. I adapt the return type to match this specification
> fix: Update registry types to return Promise

- packages/cozy-client/src/associations/HasManyFiles.js
- packages/cozy-client/src/associations/HasManyFiles.spec.js
- packages/cozy-client/src/types.js
- packages/cozy-client/types/associations/HasManyFiles.d.ts
- packages/cozy-client/types/types.d.ts
Some images such as bitmaps do not have any `metadata` object.
However, we were relying on the existence of a `metadata.datetime` date
in order to build the cursor for fetching HasManyFiles relationship,
which was causing errors in the photos clustering service.
Kudos to the inspector @Crash-- for finding out this bug :clap:
> fix: Do not rely on potentially missing datetime

- packages/cozy-stack-client/src/DocumentCollection.js
- packages/cozy-stack-client/src/DocumentCollection.spec.js
Recently, we changed in Banks from
BankTransaction.updateAll() to client.saveAll().
But we had errors in our log saying that we were
calling collection without a doctype
(CozyStackClient.collection() called without a doctype)
In fact, this is because saveAll need to read the
_type for the documents to update them cf:
https://github.com/cozy/cozy-client/blob/master/packages/cozy-client/src/StackLink.js#L122
Sometime it worked for Banks sometime not. It was due to the fact that we have a condition here:
https://github.com/cozy/cozy-banks/blob/master/src/targets/services/helpers/helpers.js#L19-L45
The fix, is to normalize the document returned by fetchChanges() like that we add _type & id automatically.
We have a fetchChangesRaw() to get the real changes without any edition.
> fix: Normalize doc for fetchChanges

- packages/cozy-client/src/context.js
- packages/cozy-client/src/hooks/useClient.js
- packages/cozy-client/types/context.d.ts
- packages/cozy-client/types/hooks/useClient.d.ts
If no `CozyProvider` is set on the components tree, then `useClient()` would return no `client`
> fix: Correctly type nullable return for `useClient()`

- packages/cozy-stack-client/src/JobCollection.js
Every colleciton should extend `DocumentCollection` to benefit from
the fallback methods when not defined specifically.
`JobCollection` was not extending it and has no `find` method so we
could not make use `CozyClient#query()` for example.
> feat: JobCollection extends DocumentCollection

- packages/cozy-client/src/helpers/urlHelper.js
- packages/cozy-client/src/helpers/urlHelper.spec.js
The URL javascript object does not support undefined `pathname`. This member should be an empty string (transformed to `/`) or have a value
```js
const url = new URL('https://cozy.io')
console.log(url.pathname) // prints '/'
console.log(url.toString()) // prints 'https://cozy.io/'
url.pathname = undefined
console.log(url.pathname) // prints '/undefined'
console.log(url.toString()) // prints 'https://cozy.io/undefined'
url.pathname = ''
console.log(url.pathname) // prints '/'
console.log(url.toString()) // prints 'https://cozy.io/'
url.pathname = ensureFirstSlash(undefined)
console.log(url.pathname) // prints '/'
console.log(url.toString()) // prints 'https://cozy.io/'
```
By using 'ensureFirstSlash' method we ensure that the caller can pass undefined `pathname` without negative side …
> fix: Handle undefined `pathname` in `generateWebLink()` method

- packages/cozy-stack-client/src/SettingsCollection.js
- packages/cozy-stack-client/src/SettingsCollection.spec.js
This is a dirty quick fix waiting for this issue to be resolved https://github.com/cozy/cozy-stack/issues/3864
> feat: Query io.cozy.settings.bitwarden in SettingsCollection

- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/hooks/useCapabilities.jsx
The new recommended way. Also to avoid to flood log in flagship-app.
> fix: Use io.cozy.settings.capabilities full id in getById

- packages/cozy-client/CHANGELOG.md
Add missing backticks to the end of the 38.0.0 version
> chore: Fix changelog

- packages/cozy-client/src/types.js
- packages/cozy-client/types/types.d.ts
I realised that the name field was missing from the konnectorsDocument type when I did my [PR](https://github.com/cozy/cozy-libs/pull/2190) on cozy-harvest-lib. 
On the [doctype](https://github.com/cozy/cozy-doctypes/blob/07fa847eac938523e5b60a7a77037b14c56375a0/docs/io.cozy.konnectors.md), there are even more fields, can I add them? Or have they been omitted on purpose?
> feat: Add missing type to konnectors document

- packages/cozy-client/src/models/document/locales/index.js
- packages/cozy-client/src/models/document/locales/index.spec.js
Currently useful for passing an optional default value, if the translation key is not found.
> fix(getBoundT): Propagate polyglot options

- packages/cozy-client/src/flagship-certification/flagship-certification.js
- packages/cozy-client/src/flagship-certification/flagship-certification.spec.js
Added name of instance in console warn for better monitoring.
Will be removed later when Sentry can handle it itself
> feat: Add instance name in certification failure

- packages/cozy-client/src/store/queries.js
- packages/cozy-client/src/store/queries.spec.js
Currently, when we receive a `RECEIVE_QUERY_RESULT`, we merge the received data with the previous data. It works well because the only use case we have for receiving multiple  `RECEIVE_QUERY_RESULT` on the same query is when we use the `fetchMore()` method. And in that case, we indeed want to merge the data.
However, with background fetching, we have already received a result for the query, and in parallel, we send the request to get fresh data. And in this case, we don't want to merge the data; we want to replace it.
I'm not very fan of the current solution, so I will create an issue to explain the entire problem.
> fix: Set the fresh data after getting a new query result

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/SettingsCollection.js
- packages/cozy-stack-client/src/SettingsCollection.spec.js
Realtime provides an object with attributes at the root, whereas in query result, attributes are a property in themselves. When cozy-client tries to merge them, only the root attributes are updated. When normalising, I now spread attributes at the root so that I can access to a data that is always up to date.property. I decided to flatten the attributes property to have a single data source.
> fix(SettingsCollection): Normalize a document spreads attributes to root

- docs/api/cozy-client/interfaces/models.instance.DiskInfos.md
- docs/api/cozy-client/interfaces/models.instance.DiskInfosRaw.md
- docs/api/cozy-client/interfaces/models.instance.SettingsInfo.md
- docs/api/cozy-client/modules/models.instance.md
- docs/api/cozy-client/modules/models.md
- docs/api/cozy-client/modules/models.user.md
- packages/cozy-client/src/models/index.js
- packages/cozy-client/src/models/instance.js
- packages/cozy-client/src/models/instance.spec.js
- packages/cozy-client/types/models/index.d.ts
- packages/cozy-client/types/models/instance.d.ts
These helpers originally come from cozy-settings (cf: [code](https://github.com/cozy/cozy-settings/blob/master/src/lib/makeDiskInfos.ts)), I imported them to share the code with cozy-drive
> feat: Add diskUsage helper

- packages/cozy-client/src/associations/HasManyFiles.js
The interface was not updated after deleting an image because only the mutation causes React rendering. The data was updated afterwards, which is why I changed the order of execution
Before we `save` the target after remove the relationships which led to a React re-render. This mechanism has been removed because it was duplicated (cf: [PR](https://github.com/cozy/cozy-client/pull/1048))
> fix(HasManyFiles): Update after removing a relation

- docs/api/cozy-client/README.md
- docs/api/cozy-client/classes/BlockedCozyError.md
- docs/api/cozy-client/classes/InvalidCozyUrlError.md
- packages/cozy-client/src/helpers/index.js
- packages/cozy-client/src/helpers/urlHelper.js
- packages/cozy-client/src/helpers/urlHelper.spec.js
- packages/cozy-client/src/index.js
- packages/cozy-client/src/index.node.js
- packages/cozy-client/types/helpers/index.d.ts
- packages/cozy-client/types/helpers/urlHelper.d.ts
- packages/cozy-client/types/index.d.ts
- packages/cozy-client/types/index.node.d.ts
When calling `rootCozyUrl` we want the method to throw a specific exception if the Cozy is in a "blocked" state
If a `503 Blocked` is returned we conclude that there is a Cozy behind the URL but we cannot check if the URL points to the Cozy's root or to a specific slug. So it is safer to throw an exception that should then be handled by the caller
BREAKING CHANGE: rootCozyUrl() can now throw a BlockedCozyError exception if the target Cozy is blocked
> fix: Handle `503 Blocked` response when calling `rootCozyUrl`

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/DocumentCollection.js
- packages/cozy-stack-client/src/DocumentCollection.spec.js
- packages/cozy-stack-client/src/mangoIndex.js
- packages/cozy-stack-client/src/mangoIndex.spec.js
We have two issues with indexes in Cozy-Client:
The first one is related to the usage of logical mango operators ($or, $and, $in, etc.) at the top level.Cozy-Client doesn't handle them properly and creates indexes named $or/$and/$etc
(see https://github.com/cozy/cozy-client/issues/1270). This can lead to conflicts with the indexes.
Even worse, when we create a partialFilter without declaring a top-level $and, like [{foo: bar, truc:muche}], the index name on the Cozy-Client side is correct (`foo_truc`). However, when we inspect the design doc, CouchDB automatically adds the $and, and it becomes `$and: [{foo: bar}, {truc: muche}]`
The second issue is the automatic deletion of what Cozy-Client considers "inconsistent" indexes. When Cozy-Client receives an event of type `index_not_found` or …
> fix: Stop destroying inconsistent index

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/AppCollection.js
- packages/cozy-stack-client/src/AppCollection.spec.js
- packages/cozy-stack-client/src/AppsRegistryCollection.js
- packages/cozy-stack-client/src/AppsRegistryCollection.spec.js
- packages/cozy-stack-client/src/CozyStackClient.js
Using the "registry" source via the `io.cozy.apps` doctype is discouraged as it may skew the `io.cozy.apps` entry of the `cozy->documents` store.
For example, if we request data from the registry, the application will be present in `cozy->documents->io.cozy.apps`, which will falsify the return of the `isInstalled()` helper.
That's why we add `AppsRegistryCollection`, in order to separate the 2 sources in 2 different store entries `cozy.documents['io.cozy.apps']` & `cozy.documents['io.cozy.apps_registry']`
> feat: Add AppsRegistryCollection

- packages/cozy-stack-client/src/SettingsCollection.js
- packages/cozy-stack-client/src/SettingsCollection.spec.js
When we tried to update `io.cozy.settings.instance`, the stack returns 409 errors to indicate conflicts. The problem was that we were sending the document directly, whereas the stack was looking for the document information in a data object (cf: [PUT /settings/instance](https://docs.cozy.io/en/cozy-stack/settings/#put-settingsinstance)).  Now, the `cozy-stack-client` wraps the document in a data object before sending it.
This fix has two benefits in `cozy-setting` : 
- no longer makes two requests for each profile update
- be able to use client.save to avoid using redux soon
> fix: Document has to be wrap into a data object to update instance

- docs/api/cozy-client/modules/models.paper.md
- packages/cozy-client/src/models/paper.js
- packages/cozy-client/src/models/paper.spec.js
Pour les permis de conduire, on souhaite afficher un lien dans la note 
d'expiration comme on le fait pour le passeport ou la carte d'identité
> feat: Add link for driver_license expiration note

- docs/api/cozy-client/classes/CozyClient.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
- packages/cozy-client/types/CozyClient.d.ts
We need `locale` attribute on flagship app.
> feat: Add instance data in loadInstanceOptionsFromStack

- docs/api/cozy-client/interfaces/models.file.FileUploadOptions.md
- docs/api/cozy-client/modules/models.file.md
- packages/cozy-client/src/models/file.js
- packages/cozy-client/src/models/file.spec.js
- packages/cozy-client/types/models/file.d.ts
Sometimes, files are named like they already had a conflict like IMG_001.JPG. It is a normal name but in this case, previous implementation would consider _001 as a conflict suffix and would return IMG_2.JPG whereas we expect IMG_001_1.JPG.
By allowing to pass a name format regex, we can tell the new implementation that the name is the original one and it should not try to increment a number even if it corresponds to the conflict format.
> feat: Allow to pass a name format regex to avoid bad renaming

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/TriggerCollection.js
- packages/cozy-stack-client/src/TriggerCollection.spec.js
To use it :
```javascript
await client.save({
_id: 'triggerid',
_rev: 'triggerrev',
message: {
konnector: 'konnectorslug',
account: 'accountid',
folder_to_save: 'folderid'
}  
})
```
Only 'arguments' and message attributes are allowed to be modified other attributes will trigger an error.
> feat: Now allow to update a trigger with cozy-client

- docs/api/cozy-client/classes/CozyClient.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
When navigating on the Flagship app, we can pass into the `securiseUri` method with  window['cozy']?.isSecureProtocol === true.
Result: we call to the toString() method, and then we have a trailing slash.
And since this uri is used when called by client.options.uri some apps can concat that with other string without checking if there is a trailing slash or not.
Apps should not do that, but since we have two different behavior between the flagship and the no flagship app, we fix that here.
> fix: Remove the trailing slash for the URI

- packages/cozy-client/src/models/geo.js
- packages/cozy-client/src/models/geo.spec.js
- packages/cozy-client/src/types.js
- packages/cozy-client/types/models/geo.d.ts
- packages/cozy-client/types/types.d.ts
This is useful for geo computations, such as geodesic distance. This distance is typically required in Photos, for spatial clustering, in CoachCO2, to find close locations, or flagship app, for optional GPS tracking.
> feat: Add geo model

- docs/api/cozy-client/modules/models.document.locales.md
- packages/cozy-client/src/models/document/locales/index.js
Metro does not support dynamic requires and the error was swallowed by
an empty catch.
Replaced the dynamic requires with explicit imports.
I missed this problem before because the warning was not obvious in
flagship app logs and since I did not remove magic folders for my tests
but just the destination folder, magic folders references where still
present and did their job.
> fix: Magic Folders localization does not work with Metro

- packages/cozy-client/src/index.node.js
- packages/cozy-client/types/index.node.d.ts
To develop a service on Photos, I need the getReferencedBy function to be available in a node process
> feat: Export getReferencedBy for node process

- docs/api/cozy-client/modules/models.utils.md
- packages/cozy-client/src/models/utils.js
- packages/cozy-client/src/models/utils.spec.js
- packages/cozy-client/types/models/utils.d.ts
The aim of this function is to provide a link to the download page for the flagship application and its white-label versions. It is used in Harvest but purpose is to share it so that it can also be used in store. I put it in the `utils` model because it seemed the most relevant, but if you have a better place I'd be happy to change it.
> feat: Add getFlagshipDownloadLink function

- packages/cozy-client/src/models/utils.js
A small mistake 😟 By convention, we use hyphen instead of underscore
> fix: Inconsistency in Flagship flag

- packages/cozy-stack-client/src/AppsRegistryCollection.js
- packages/cozy-stack-client/src/AppsRegistryCollection.spec.js
This route is used to get the list of applications under maintenance. This change is a trick to cache the result in the Redux store.
> feat: Cache the result of /registry/maintenance from cozy-stack

- docs/api/cozy-client/README.md
- packages/cozy-client/src/hooks/useAppsInMaintenance.jsx
- packages/cozy-client/src/hooks/useAppsInMaintenance.spec.jsx
- packages/cozy-client/types/hooks/useAppsInMaintenance.d.ts
Since cozy-client 41.9.0 release, we can benefit from the cache for the request to get the apps in maintenance using
Q('io.cozy.apps_registry').getById('maintenance'). This commit updates the useAppsInMaintenance hook to use this request with useQuery. As a result, the hook no longer needs a cozy-client instance.
> feat: Benefit from the cache for the apps in maintenance

- packages/cozy-stack-client/src/AppsRegistryCollection.js
- packages/cozy-stack-client/src/AppsRegistryCollection.spec.js
There are two ways of maintaining an app using registry and cozy-stack.  Apps from the registry have an id that corresponds to the slug. Conversely, apps from the stack do not have an id, which causes cozy-client to crash. I've decided to create an id from the slug for those that don't have one to fix the problem temporarily.
> fix: Handle maintenance app without id

- docs/api/cozy-client/README.md
- packages/cozy-client/src/helpers/urlHelper.js
- packages/cozy-client/src/helpers/urlHelper.spec.js
To infer the root Cozy URL from a given URL, we can go through up to 3
steps:
1. we try to fetch the well known change password URL with the given
URL's origin
2. if that requests fails, we try to remove any potential app slugs
from the origin and try again
3. if that fails as well, we try to remove the first sub-domain from
the origin and try again
However, `cozy-stack` treats some deprecated apps URLs in a different
manner. Specifically, it will redirect requests to the Home app for
any URL with these deprecated apps origin no matter what the requested
path is.
See https://github.com/cozy/cozy-stack/blob/299968d43914066c3147276eea2463ebb292d527/web/apps/serve.go#L101-L108
This results in a successful request at step 1 instead of the expected
error (i.e. we remove app slugs at step 2) …
> fix: Handle URLs that redirect in rootCozyUrl

- docs/api/cozy-client/README.md
- docs/react-integration.md
- packages/cozy-client/src/mock.js
- packages/cozy-client/src/mock.spec.js
This facilitates the development of test cases for error handling with queries. An example of a test is available in the react-integration documentation
> feat: Allow to mock query in error

- docs/api/cozy-client/README.md
- packages/cozy-client/src/hooks/useFetchShortcut.jsx
- packages/cozy-client/src/hooks/useFetchShortcut.spec.jsx
Cozy applications only make their assets available if you are authenticated. As a result, the stack cannot retrieve the favicon. When a link comes from an application in the same Cozy, we can find out its slug and deduce its icon. For the moment, we can't do this for third-party Cozy applications because the URL formats are too diverse
> fix: Get shortcut img for links from applications in the same cozy

- packages/cozy-client/src/types.js
- packages/cozy-client/types/types.d.ts
It was previously declared in cozy-flagship.
It is needed to update documentation in cozy-doctypes
following this commit
> feat: Add IOCozyApp interface

- docs/api/cozy-client/modules/models.note.md
- packages/cozy-client/src/models/note.js
- packages/cozy-client/types/devtools/Flags/FlagEdit.d.ts
- packages/cozy-client/types/devtools/Flags/FlagItem.d.ts
- packages/cozy-client/types/devtools/Flags/Flags.d.ts
- packages/cozy-client/types/devtools/Flags/helpers.d.ts
- packages/cozy-client/types/models/note.d.ts
Each time we create a link, we redirect the user to /public/ outside of a cozy to cozy share, we want to access /preview/. This commit allows you to pass a pathname as an option in order to manage this case
> fix: Preview URL for notes

- docs/api/cozy-client/interfaces/models.file.FileUploadOptions.md
- docs/api/cozy-client/modules/models.file.md
- packages/cozy-client/src/models/file.js
- packages/cozy-client/src/models/file.spec.js
- packages/cozy-client/types/models/file.d.ts
Following the development of @zatteo on the improvement of the "generateNewFileNameOnConflict" function (#1425),
we can take advantage of it to also offer the option in the "uploadFileWithConflictStrategy" function which uses the latter.
> feat: Improve uploadFileWithConflictStrategy

- docs/metadata.md
> docs: Fix A typo in metadata example

- docs/api/cozy-client/modules/models.file.md
- packages/cozy-client/src/models/file.js
- packages/cozy-client/types/models/file.d.ts
I want to reduce [cozy-client.d.ts](https://github.com/cozy/cozy-flagship-app/blob/master/src/%40types/cozy-client.d.ts) size in cozy-flagship-app.
I am currently trying to understand how it works and how to do it correctly. Here is a first very simple but working type.
> docs: Add return type to models.file.splitFilename

- packages/cozy-stack-client/src/AppsRegistryCollection.js
- packages/cozy-stack-client/src/AppsRegistryCollection.spec.js
Applications from the registry have no id. For cozy-client needs, we add one based on the source in the manifest. However, some applications do not have a source, for example banking konnector. This commit ensures that there is an id based on the slug to avoid errors.
> fix(AppsRegistryCollection): Make sure apps always have an id

- docs/api/cozy-client/README.md
- packages/cozy-client/src/mock.js
- packages/cozy-client/src/mock.spec.js
- packages/cozy-client/types/mock.d.ts
This new function will create a client like createMockClient but without the jest mock. It will be useful for demo in documentation because isn't defined in there context. Two usecases are in storybook and in the cozy-ui documentation.
**Remaining work:**
- ~~make unit tests~~
> feat: Add createDemoClient to help with demo

- packages/cozy-client/src/models/document/locales/fr.json
In order to be more homogeneous with the other qualifications concerning taxes
> feat: Rename FR translation of real_estate_tax

- packages/cozy-client/src/flagship-certification/flagship-certification.js
- packages/cozy-client/src/flagship-certification/flagship-certification.spec.js
Failing Flagship certification is expected when the app is run in a dev environment and when the user uses a non-official phone (i.e. alternative Android OS)
This would help developers understanding when this message is problematic and where it is not
> feat: Update warning message when Flagship certification fails

- packages/cozy-client/package.json
- packages/cozy-client/src/flagship-certification/README.md
- packages/cozy-client/src/flagship-certification/flagship-certification.js
- packages/cozy-client/src/flagship-certification/flagship-certification.spec.js
- packages/cozy-client/src/flagship-certification/store-attestation.android.js
- packages/cozy-client/src/flagship-certification/typedefs.js
- packages/cozy-client/types/flagship-certification/typedefs.d.ts
Implement
- Remove SafetyNet from cozy-client
- Add Google Play Integrity to cozy-client
Remarks
- API remains unchanged
- React-native package is forked for now
- Documentation updated
References
- https://github.com/cozy/react-native-google-play-integrity
- https://maven.google.com/web/index.html?hl=fr#com.google.android.play:integrity
- https://developer.android.com/google/play/integrity/standard
> feat: Migrate from safetynet to playintegrity (VO-208)

- docs/api/cozy-client/modules/models.account.md
- packages/cozy-client/src/models/account.js
- packages/cozy-client/src/models/account.spec.js
Now models.account.getAccountLogin (and models.account.getAccountName)
will use the identifier attribute from the account to choose the right
login field, as described in the account doctype documentation.
This identifier attribute is calculated using the `role: identifier`
attribute from account.auth if any.
> feat: Make account model use identifier attribute

- packages/cozy-client/src/hooks/useInstanceInfo.js
Related to : in next versions of cozy-client, it will not be possible to query settings with an incomplete id
> fix: Use complete settings id in useInstanceInfo

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/OAuthClient.js
This will allow skipping 2FA when logging from email in Flagship
> feat: Add email_verified_code in loginFlagship (VO-380)

- docs/api/cozy-client/modules/models.paper.md
- packages/cozy-client/src/models/document/locales/en.json
- packages/cozy-client/src/models/document/locales/fr.json
- packages/cozy-client/src/models/paper.js
- packages/cozy-client/src/models/paper.spec.js
- packages/cozy-client/types/models/paper.d.ts
The Viewer component in cozy-ui displays paper metadata in the side panel. 
We need to display the same paper metadata in cozy-keys-browser which is written in Angular so we can not benefit as is from the Viewer component.
So in this PR, I extract the logic from the Viewer component in cozy-ui to select, format and translate paper metadata to cozy-client so that : 
- cozy-ui will use the logic to create React component (no behavior changes)
- cozy-keys-browser will use the logic to create Angular component
> Move paper metadata formatting in cozy-client 

- docs/api/cozy-client/README.md
- docs/api/cozy-client/classes/QueryDefinition.md
- packages/cozy-client/src/queries/dsl.js
- packages/cozy-client/src/queries/dsl.spec.js
This query is a valid mango query :
```
where({ worker: ['client', 'konnector']})
```
But the library [sift](https://github.com/crcn/sift.js) that we use to replay the query with the same doctype can't apply that selector because it requires MongoDB operators.
As a result, we have issues when some query where emptied and were breaking some feature
That is why we throw an error. I've chosen to have a deep check to avoid too many calculations at runtime.
BREAKING CHANGE: if you use a selector on multiple value without the `$and`  mango operator, you have to change that and use this `$and` operator.
> [VO-524] feat: Prevent array selector without operator before

- docs/api/cozy-client/classes/models.document.Qualification.md
- docs/api/cozy-client/modules/models.document.md
- packages/cozy-client/src/models/document/qualification.js
- packages/cozy-client/src/models/document/qualification.spec.js
- packages/cozy-client/types/models/document/qualification.d.ts
...is present on the file.
Lors d'un développement sur l'amélioration de la modale de qualification de cozy-drive, je souhaite récupérer la qualification courante du fichier.
Cette fonction est là pour ça mais je pense qu'elle devrait prévoir le fait que le document n'a pas de metadata et/ou qualification
> fix: The getQualification function should not crash if no qualification

- docs/api/cozy-client/modules/models.contact.md
- packages/cozy-client/src/models/contact.js
- packages/cozy-client/src/models/contact.spec.js
- packages/cozy-client/types/models/contact.d.ts
This attribute will be used within cozy-contacts.
In this case, we do not want to concatenate in the `displayName` attribute the `additionalName` attribute.
A simple solution is to offer the possibility to `makeFullname` to construct the `displayName` in a personalized way (within the limits of the attributes existing in `name`)
> feat: We don't want to concatenate `additionalName` in the `displayName`

- packages/cozy-client/src/types.js
- packages/cozy-client/types/types.d.ts
- packages/cozy-stack-client/src/ContactsCollection.js
- packages/cozy-stack-client/src/ContactsCollection.spec.js
Depending if a contact has been imported by a konnector or not, there is logic to delete a contact.
We need to delete a contact at least in :
- cozy-contacts
- cozy-keys-browser
So let's centralize this logic.
Original function : https://github.com/cozy/cozy-contacts/blob/5c5df4606b53133fd3b0b2bfffc9fdda48e5052c/src/connections/allContacts.js#L77
> Add an helper to delete a contact

- packages/cozy-client/src/authentication/mobile.native.js
_Road to RN0.72 on cozy-flagship-app_
Linking.removeEventListener has been removed from react-native 0.71. We need to call remove() on the subcription returned by Linking.addEventListener().
Still compatible with react-native 0.66.
> Remove deprecated Linking.removeEventListener

- docs/api/cozy-client/modules/models.paper.md
- packages/cozy-client/src/models/paper.js
- packages/cozy-client/src/models/paper.spec.js
related: c4c1545
A l'origine nous souhaitons que `makeMetadataQualification` retourne `null` si la clé de la metadata n'est pas connue (modulo autre check).
Les derniers changements, pour prendre en compte des attributs profonds, on changés ce comportement en retournant `null` si la valeur de cette metadata est "falsy"
Cette PR conserve le dernier besoin implémenté mais corrige la régression apportée.
> fix: Metadata present but whose value is not specified must be returned in order to be modified in the Viewer

- packages/cozy-client/src/models/document/locales/en.json
- packages/cozy-client/src/models/document/locales/fr.json
When creating a paper, the UI of the step to define a "notice period" before being alerted of the expiration of its document changes.
Its translations were carried by the app, but with the new reworked UI coming from "contract types", the new translations make more sense here.
> feat: Add translation for MesPapiers app

- docs/api/cozy-client/modules/models.contact.md
- packages/cozy-client/src/models/contact.js
- packages/cozy-client/src/models/contact.spec.js
- packages/cozy-client/types/models/contact.d.ts
When we create a new contact with only the email, it creates a contact object with `name: { familyName: '', givenName: '' }`.
So in this case getInitials was always returning an empty string whereas we want to return the first letter of the primary email.
@JF-Cozy @Merkur39 should we use maybe `displayName` to calculate initials ?
> fix: Contact getInitials should  return initials even if name attributes are empty strings

- docs/api/cozy-client/modules/models.document.locales.md
- packages/cozy-client/src/models/document/emojiCountry.js
- packages/cozy-client/src/models/document/emojiCountry.spec.js
- packages/cozy-client/src/models/document/locales/index.js
- packages/cozy-client/src/models/document/locales/index.spec.js
- packages/cozy-client/types/models/document/emojiCountry.d.ts
This PR improves flag emoji generation 🎉 
*Necessary development for ongoing development on MesPapiers*
> feat(getEmojiByCountry): Automatically generate flag emoji

- docs/api/cozy-client/modules/models.paper.md
- packages/cozy-client/src/models/paper.js
- packages/cozy-client/src/models/paper.spec.js
In order to return a more comprehensible value than the ISO 3166-1 alpha-2 code in the viewer information, among other things.
> feat(models/paper): Add translation of "country" metadata

- packages/cozy-client/src/models/document/locales/en.json
- packages/cozy-client/src/models/document/locales/fr.json
- packages/cozy-client/src/models/document/locales/index.js
- packages/cozy-client/src/models/document/locales/index.spec.js
This term had been replaced in the MyPapers app but was forgotten here.
As a result, we've lost the ''(Foreign)'' display on papers such as the foreign driver's license, and this generates a lot of error logs.
> fix(models/document): Rename "stranger" locale

- packages/cozy-client/src/models/country/countries.js
- packages/cozy-client/src/models/country/countries.spec.js
- packages/cozy-client/src/models/country/locales/index.js
- packages/cozy-client/src/models/paper.js
- packages/cozy-client/types/models/country/countries.d.ts
- packages/cozy-client/types/models/country/locales/index.d.ts
Via OCR, the value comes from a text field, and it can have values like "fra," "bob," "aa," etc.
These changes prevent any bad UI/UX behavior.
> feat: We make sure that the translation key matches to an alpha-2 code

- docs/api/cozy-client/README.md
- docs/api/cozy-stack-client.md
- packages/cozy-client/src/hooks/useQuery.js
- packages/cozy-client/types/hooks/useQuery.d.ts
- packages/cozy-stack-client/src/CozyStackClient.js
- packages/cozy-stack-client/src/FileCollection.js
- packages/cozy-stack-client/src/NextcloudFilesCollection.js
- packages/cozy-stack-client/src/utils.js
This PR is the first one to implement the new type `io.cozy.remote.nextcloud.files`. It allow us to interact with Nextcloud server inside Drive 🙂 
**Related PRs :**
- https://github.com/cozy/cozy-stack/pull/4392
> [VO-711] feat: Add a collection to access files into a Nextcloud

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/FileCollection.js
- packages/cozy-stack-client/src/FileCollection.spec.js
Added `createArchiveLinkByIds` method and depreciated `getArchiveLinkByIds` method.
The name is more accurate and it allows us to refine the selection by giving the pages we want for each file.
> feat(FileCollection): Create archive link by file ids with specific pages

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/DocumentCollection.js
- packages/cozy-stack-client/src/DocumentCollection.spec.js
- packages/cozy-stack-client/src/mangoIndex.js
- packages/cozy-stack-client/src/mangoIndex.spec.js
Index naming has two weaknesses: 
- it doesn't include partial index values
This can cause differences between the expected result and the result when modifying queries.
**An example of the new index name**: 
Query definition :
```js
Q('io.cozy.files')
.where({
type: 'file',
})
.partialIndex({
class: {
$or: ['image', 'pdf'] 
}
trashed: {
     $eq: false 
}
})
.sortBy([
{ name: 'desc' }
])
```
Old index name : `_design/by_type_and_name_filter_class_and_trashed`
New index name : `_design/by_type_and_name_filter_(class_(image_$or_pdf))_and_(trashed_$eq_false)`
> [VO-874] feat: Improve index naming

- packages/cozy-client/src/types.js
- packages/cozy-client/types/types.d.ts
Since I've been trying to use Typescript in cozy-drive, I've found some missing types. I've proposed to add it to cozy-client so that it can be used in all your apps 🙂
> [VO-847] feat: Add missing types for IOCozyFile

- packages/cozy-client/src/types.js
- packages/cozy-client/types/types.d.ts
I chose not to use CozyClientDocument with NextcloudFile because the document is a bit special as it is a proxy to Nextcloud and therefore does not have all the fields filled.
> [VO-740] feat: Improve type of NextcloudFile

- packages/cozy-client/src/types.js
- packages/cozy-client/types/types.d.ts
This new property has been added to be able to reload destination folder query after a restore action.
**Related PRs :**
- https://github.com/cozy/cozy-stack/pull/4447
> [VO-740] feat: Add restore_path to NextcloudFile type

- docs/api/cozy-client/classes/CozyClient.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
- packages/cozy-client/src/store/index.js
- packages/cozy-client/types/CozyClient.d.ts
- packages/cozy-client/types/store/index.d.ts
When a query is reset, it may not yet be initialized. This can happens when you want to reset a query for the destination folder of a restored file but the view of this folder has never been accessed. By returning null, this allows the developer to choose whether he really wants to initialise it or take some other action.
> [VO-924] fix(resetQuery): Return null when the query is not found

- docs/api/cozy-client/interfaces/models.file.FileUploadOptions.md
- docs/api/cozy-client/modules/models.file.md
- packages/cozy-client/src/models/file.js
- packages/cozy-client/src/models/file.spec.js
The issue comes from a previous [PR](https://github.com/cozy/cozy-client/pull/1488). Where, I changed the function header to pass an object like `io.cozy.files` instead of his attributes directly.
**Old:** 
```
move(client, fileId, destination, force = false)
``` 
**New:** 
```
move(client, file, destination, { force } = { force: false })
```
The old object `destination` could have a path property which was corresponding to the file path into destination (destination folder path + filename of the moved file). In the new one, as the object is an `io.cozy.files` folder always contains the path of himself only.
When there is a conflit and the destination is not a shared folder (`force`), we want to move into the trash the file that already exists inside destination folder so we could try to …
> [VO-957] fix(move): Trash the conflicting file instead of the destination folder

- docs/api/cozy-client/classes/CozyClient.md
- docs/architecture.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
- packages/cozy-client/src/store/index.js
- packages/cozy-client/src/store/queries.js
- packages/cozy-client/src/store/queries.spec.js
- packages/cozy-client/src/types.js
- packages/cozy-client/types/CozyClient.d.ts
- packages/cozy-client/types/store/index.d.ts
- packages/cozy-client/types/store/queries.d.ts
- packages/cozy-client/types/types.d.ts
We add a new option in the query API called `executeFromStore`. This is useful to allow the execution of a query directly on the store, i.e. without running on the link (StackLink or PouchLink), hence the database.
The use-case for this is to be able to have a very fast query when we have the relevant data on the store, typically after a sync. In such situation, we do not need to make a network call on the database as we can simply benefit from the local store.
> feat: Support executing queries from store

- docs/api/cozy-client/README.md
- packages/cozy-client/src/store/index.js
- packages/cozy-client/src/store/queries.js
- packages/cozy-client/src/store/queries.spec.js
- packages/cozy-client/src/store/stateHelpers.js
- packages/cozy-client/src/types.js
- packages/cozy-client/types/store/index.d.ts
- packages/cozy-client/types/store/queries.d.ts
- packages/cozy-client/types/store/stateHelpers.d.ts
- packages/cozy-client/types/types.d.ts
Small correction to https://github.com/cozy/cozy-client/pull/1511
> fix: Support executing queries from store

- packages/cozy-stack-client/src/DocumentCollection.js
- packages/cozy-stack-client/src/DocumentCollection.spec.js
When specifying fields in a query, e.g.
`Q('io.cozy.todos').where({done: true}).select(['date'])`, the revision was missing if not explicitly given. This is now problematic because we rely on the revision existence to identify "virtual" documents, i.e. not persisted in CouchDB, that never have any revision. See https://github.com/cozy/cozy-client/pull/1486 for more insights.
> feat: Force _rev for queries with .select fields

- docs/api/cozy-pouch-link/classes/PouchLink.md
- packages/cozy-pouch-link/examples/periodic-sync/index.js
- packages/cozy-pouch-link/src/CozyPouchLink.js
- packages/cozy-pouch-link/src/PouchManager.js
- packages/cozy-pouch-link/src/PouchManager.spec.js
- packages/cozy-pouch-link/src/localStorage.js
- packages/cozy-pouch-link/src/platformWeb.js
- packages/cozy-pouch-link/src/startReplication.js
- packages/cozy-pouch-link/src/startReplication.spec.js
- packages/cozy-pouch-link/src/types.js
- packages/cozy-pouch-link/types/CozyPouchLink.d.ts
- packages/cozy-pouch-link/types/PouchManager.d.ts
- packages/cozy-pouch-link/types/localStorage.d.ts
- packages/cozy-pouch-link/types/platformWeb.d.ts
- packages/cozy-pouch-link/types/startReplication.d.ts
- packages/cozy-pouch-link/types/types.d.ts
We want to reduce coupling between CozyPouchLink and the browser's
local storage
This PR adds a `platform` option into the PouchLink constructor in
order to allow injecting custom local storage API, PouchDB adapter, an
isOnline method and a custom event emitter for online/offline and
pause/resume events from the consuming app
This will allow to use CozyPouchLink from a react-native project where
a different PouchDB adapter is used and where none of
`window.localStorage`, `window.navigator.onLine`,
`document.addEventListener` and `document.removeEventListener` API are
available
If no custom `platform` is injected, then `platformWeb.js` will be used
by default
In order to inject a custom `platform`, create a new platform object
containing the same API as `platformWeb.js` and add it into the …
> feat: Make CozyPouchLink compatible with ReactNative

- docs/api/cozy-client/classes/CozyClient.md
- docs/api/cozy-client/classes/CozyLink.md
- docs/api/cozy-client/classes/StackLink.md
- docs/api/cozy-pouch-link/classes/PouchLink.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
- packages/cozy-client/src/CozyLink.js
- packages/cozy-client/src/StackLink.js
- packages/cozy-client/src/types.js
- packages/cozy-client/types/CozyClient.d.ts
- packages/cozy-client/types/CozyLink.d.ts
- packages/cozy-client/types/types.d.ts
- packages/cozy-pouch-link/src/CozyPouchLink.js
- packages/cozy-pouch-link/src/CozyPouchLink.spec.js
- packages/cozy-pouch-link/src/jsonapi.js
- packages/cozy-pouch-link/src/jsonapi.spec.js
- packages/cozy-pouch-link/src/startReplication.js
- packages/cozy-pouch-link/types/CozyPouchLink.d.ts
- packages/cozy-pouch-link/types/jsonapi.d.ts
> [!NOTE]
> This PR follows #1483
When a PouchLink is configured, the synchronization process would retrieve only documents that exists on the remote database
Those documents would be served as usual when a `.query()` is made using the PouchLink
Unfortunately, not all `.query()` correspond to a document that exists on the remote database. With the collection mechanism, some documents are retrieved using an alternative endpoint and then the cozy-stack generate the document on-demand
For example this is the case for `io.cozy.settings.flags`, `io.cozy.settings.context` and `io.cozy.settings.disk-usage`
Because those documents does not actually exist on the remote database, we cannot sync them using the PouchDB sync mechanism and so they won't be available when the device is offline
To fix …
> feat: Handle Virtual Documents persistance in PouchLink

- docs/api/cozy-client/classes/StackLink.md
- packages/cozy-client/src/StackLink.js
- packages/cozy-client/src/utils.js
- packages/cozy-client/types/StackLink.d.ts
- packages/cozy-client/types/utils.d.ts
> [!NOTE]
> This PR follows #1483 and #1486
On the Flagship app we want to serve `.query()` request using the `StackLink` when the device is connected, but we want to fallback to the `PouchLink` when we detect a connection loss
To allow this, we allow the consuming app to provide an `isOnline()` method to the `StackLink`
When provided, the `StackLink` will check for connectivity before doing its request. When offline, instead of processing the request, it will instead forward the request to the next `Link`
The code is generic so the consuming app can configure a `PouchLink` or anything else as the next `Link`
We want to also catch network errors when the `isOnline()` methods fails to detect connection loss, then we also fallback to the next `Link`
___
- #1483
- #1486
- …
> feat: Forward operation in `StackLink.request()` when offline

- docs/api/cozy-pouch-link/classes/PouchLink.md
- packages/cozy-pouch-link/src/CozyPouchLink.js
- packages/cozy-pouch-link/src/CozyPouchLink.spec.js
- packages/cozy-pouch-link/src/PouchManager.js
- packages/cozy-pouch-link/src/PouchManager.spec.js
- packages/cozy-pouch-link/src/localStorage.js
- packages/cozy-pouch-link/src/remote.js
- packages/cozy-pouch-link/src/remote.spec.js
- packages/cozy-pouch-link/src/replicateOnce.js
- packages/cozy-pouch-link/src/startReplication.js
- packages/cozy-pouch-link/src/startReplication.spec.js
- packages/cozy-pouch-link/src/types.js
- packages/cozy-pouch-link/src/utils.js
- packages/cozy-pouch-link/types/CozyPouchLink.d.ts
- packages/cozy-pouch-link/types/PouchManager.d.ts
- packages/cozy-pouch-link/types/remote.d.ts
- packages/cozy-pouch-link/types/replicateOnce.d.ts
- packages/cozy-pouch-link/types/types.d.ts
- packages/cozy-pouch-link/types/utils.d.ts
In previous PRs we implemented react-native support for CozyPouchLink
Some of the doctypes we want to replicate may not always exist in remote database. This is the case for `io.cozy.accounts` that do not exist until the first konnector is configured. When this happens we want the replication process to be resilient and the react-native app to still serve data when offline
Some other doctypes are protected by the remote cozy-stack. When this is the case we still want to have a local Pouch to store cozy-stack answers and make them available offline. This is not a real replication but is considered as is in the code.
This PR adapts the Pouch replication process to those new needs and also make it more robust by fixing some historic bugs
> feat: Make Pouch replication work with react-native

- docs/api/cozy-client/README.md
- docs/api/cozy-client/classes/CozyLink.md
- docs/api/cozy-client/classes/FlagshipLink.md
- packages/cozy-client/package.json
- packages/cozy-client/src/FlagshipLink.js
- packages/cozy-client/src/index.js
- packages/cozy-client/types/FlagshipLink.d.ts
- packages/cozy-client/types/index.d.ts
- yarn.lock
When hosted in the Flagship app, we want the cozy-apps to be able to forward their queries to the native code
This will allow the native code to have control on the data lifecycle and chose between the cozy-stack or a local Pouch database as the source for executing the query
For now we use cozy-intent in order to communicate through post messages as it is the fastest implementation possible but this may change in the future if we encounter performances issues (i.e. using a local HTTP server)
___
- Upgrade cozy-intent after cozy/cozy-libs#2562 being merged (current commit has incorrect version)
___
- cozy/cozy-libs#2562
> feat: Implement FlagshipLink

- docs/api/cozy-pouch-link/classes/PouchLink.md
- docs/api/cozy-stack-client.md
- packages/cozy-pouch-link/src/CozyPouchLink.js
- packages/cozy-pouch-link/src/CozyPouchLink.spec.js
- packages/cozy-pouch-link/src/jsonapi.js
- packages/cozy-pouch-link/src/jsonapi.spec.js
- packages/cozy-pouch-link/src/mango.js
- packages/cozy-pouch-link/src/mango.spec.js
- packages/cozy-pouch-link/src/types.js
- packages/cozy-pouch-link/types/CozyPouchLink.d.ts
- packages/cozy-pouch-link/types/jsonapi.d.ts
- packages/cozy-pouch-link/types/mango.d.ts
- packages/cozy-pouch-link/types/types.d.ts
- packages/cozy-stack-client/src/DocumentCollection.js
- packages/cozy-stack-client/src/mangoIndex.js
In previous PRs we modified cozy-client and cozy-pouch-link to make them compatible with the react-native Flagship app
Since we didn't use this link for a long time but also because we use a newer PouchDB version, some queries do not work anymore (i.e. incompatible indexes, bad selectors etc)
This PR improve PouchLink querying system to make our app ecosystem compatible with new PouchDB version
> feat: Make PouchLink querying system compatible with new PouchDB version

- docs/api/cozy-client/classes/StackLink.md
- docs/api/cozy-pouch-link/classes/PouchLink.md
- packages/cozy-client/src/StackLink.js
- packages/cozy-client/types/StackLink.d.ts
- packages/cozy-pouch-link/src/CozyPouchLink.js
- packages/cozy-pouch-link/types/CozyPouchLink.d.ts
Previous declaration would generate non-optional attributes for options in `.d.ts` files
Also `doctypesReplicationOptions` type was incorrect
> docs: Fix types for CozyPouchLink and StackLink constructors

- docs/api/cozy-client/interfaces/models.file.FileUploadOptions.md
- docs/api/cozy-client/modules/models.file.md
- docs/api/cozy-stack-client.md
- packages/cozy-client/src/models/file.js
- packages/cozy-client/src/models/file.spec.js
- packages/cozy-client/src/types.js
- packages/cozy-client/types/models/file.d.ts
- packages/cozy-client/types/types.d.ts
- packages/cozy-stack-client/src/FileCollection.js
For the Flagship app offline feature, we want to make some files available offline
To make this possible, we want the cozy-apps to download files as usual except when they are hosted in the FlagshipApp
In that scenario, we want the cozy-app to call the new `downloadFile` intent
Also to ease future compatibility, we want to implement a new method hosted in the `file` model instead of in the collection as before
So in order to handle offline files, the cozy-app will now need to call `downloadFile()` method from `models/file`
___
Related PRs:
- cozy/cozy-ui#2690
- cozy/cozy-flagship-app#1237
> feat: Add `downloadFile` method in `file` model

- docs/api/cozy-client/classes/CozyLink.md
- docs/api/cozy-client/classes/FlagshipLink.md
- docs/api/cozy-client/classes/StackLink.md
- docs/api/cozy-pouch-link/classes/PouchLink.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyLink.js
- packages/cozy-client/src/FlagshipLink.js
- packages/cozy-client/src/StackLink.js
- packages/cozy-client/src/types.js
- packages/cozy-client/types/CozyClient.d.ts
- packages/cozy-client/types/CozyLink.d.ts
- packages/cozy-client/types/FlagshipLink.d.ts
- packages/cozy-client/types/types.d.ts
- packages/cozy-pouch-link/src/CozyPouchLink.js
- packages/cozy-pouch-link/src/CozyPouchLink.spec.js
- packages/cozy-pouch-link/src/helpers.js
- packages/cozy-pouch-link/src/helpers.spec.js
- packages/cozy-pouch-link/src/jsonapi.js
- packages/cozy-pouch-link/src/jsonapi.spec.js
- packages/cozy-pouch-link/src/localStorage.js
- packages/cozy-pouch-link/src/localStorage.spec.js
- packages/cozy-pouch-link/src/startReplication.js
- packages/cozy-pouch-link/src/startReplication.spec.js
- packages/cozy-pouch-link/types/CozyPouchLink.d.ts
- packages/cozy-pouch-link/types/helpers.d.ts
- packages/cozy-pouch-link/types/jsonapi.d.ts
- packages/cozy-pouch-link/types/startReplication.d.ts
This PR applies change requests from previous PRs on Offline mode
See all commit messages for more details
___
Related PRs:
- #1507
> fix: Applies PRs change requests for Offline mode

- docs/api/cozy-client/interfaces/models.instance.DiskInfos.md
- docs/api/cozy-client/interfaces/models.instance.DiskInfosRaw.md
- docs/api/cozy-client/modules/models.applications.md
- docs/api/cozy-client/modules/models.instance.md
- docs/api/cozy-pouch-link/classes/PouchLink.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/associations/HasManyFiles.js
- packages/cozy-client/src/hooks/useAppLinkWithStoreFallback.spec.jsx
- packages/cozy-client/src/hooks/useCapabilities.jsx
- packages/cozy-client/src/hooks/useCapabilities.spec.jsx
- packages/cozy-client/src/hooks/useFetchShortcut.jsx
- packages/cozy-client/src/hooks/useFetchShortcut.spec.jsx
- packages/cozy-client/src/models/applications.js
- packages/cozy-client/src/models/applications.spec.js
- packages/cozy-client/src/models/instance.js
- packages/cozy-client/src/models/instance.spec.js
- packages/cozy-pouch-link/src/CozyPouchLink.js
- packages/cozy-pouch-link/types/CozyPouchLink.d.ts
Those doc's attributes are specific to the JSON API and should not be inserted into the Pouch database
This implies that we will have a difference on documents regarding if they are served through the cozy-stack or through a local PouchDB, the first one may include those fields in their result, but not the second one
So from now we should avoid, as much as possible, to relies on the `attributes` member to prevent bugs on Offline mode. Multiple commits to fix usages of `attributes` in cozy-client will be done after this one
Usage of `attributes` and `meta` members on cozy-app will also have to be fixed. This will be a requirement to implement Offline mode on cozy-apps
___
Related PRs:
- #1507
> fix: Remove attributes and meta attributes before persisting docs

- packages/cozy-client/types/store/realtimes.d.ts
`realtime.js` has been renamed to `realtime.js` but the old typing file has not been removed
Related commit: 4aa9ab0d091a111efebf963278ac7a8e208ded7e
> fix: Remove realtimes.d.ts

- docs/api/cozy-client/classes/CozyLink.md
- docs/api/cozy-client/classes/FlagshipLink.md
- docs/api/cozy-client/classes/StackLink.md
- docs/api/cozy-pouch-link/classes/PouchLink.md
- packages/cozy-client/src/CozyLink.js
- packages/cozy-client/src/FlagshipLink.js
- packages/cozy-client/src/StackLink.js
- packages/cozy-client/types/CozyLink.d.ts
- packages/cozy-client/types/FlagshipLink.d.ts
- packages/cozy-client/types/StackLink.d.ts
- packages/cozy-pouch-link/types/CozyPouchLink.d.ts
In the Flagship app, we want to be able to reset the local PouchDB files in order to prevent beta testers to be blocked by an erroneous Pouch replication
To make this possible we want to expose a public method that resets all the cozy-client's links
> feat: Improve CozyLink typing and add `reset()` method

- docs/api/cozy-client/README.md
- docs/api/cozy-client/classes/CozyLink.md
- docs/api/cozy-client/classes/WebFlagshipLink.md
- packages/cozy-client/src/WebFlagshipLink.js
- packages/cozy-client/src/index.js
- packages/cozy-client/types/WebFlagshipLink.d.ts
- packages/cozy-client/types/index.d.ts
This should clarify that this link should be run on the web side and not on the Flagship app side
> feat: Rename FlagshipLink to WebFlagshipLink

- docs/api/cozy-pouch-link/classes/PouchLink.md
- packages/cozy-pouch-link/src/CozyPouchLink.js
- packages/cozy-pouch-link/src/CozyPouchLink.spec.js
- packages/cozy-pouch-link/src/PouchManager.js
We noticed severe performances issues when using pouchdb in a  react-native environment.
See commit descriptions for more insights
**BEFORE**
```
Indexing time : 53 868 ms
Query time : 51 499 ms
```
**AFTER**
```
Indexing time : 31 833 ms
Query time : 1 854 ms
> Improve pouchDB performances

- packages/cozy-client/src/types.js
- packages/cozy-client/types/types.d.ts
This reverts some part of the commit fb1bbf0.
There are existing shortcuts that rely on `metadata.description`. Therefore, we revert this change.
> fix: Revert some updates to file metadata types

- docs/api/cozy-client/README.md
- packages/cozy-client/src/RealTimeQueries.jsx
- packages/cozy-client/src/RealTimeQueries.spec.jsx
- packages/cozy-client/src/helpers/realtime.js
- packages/cozy-client/src/store/realtime.js
- packages/cozy-client/types/helpers/realtime.d.ts
- packages/cozy-client/types/store/realtime.d.ts
This enrichment closes the gap between the results of queries from the cozy-stack and realtime. In fact, realtime returns the document directly from the database, unlike the stack, which can add computed fields. Without them, it can lead to instable behaviour in applications. Some applications fix some issue by reimplementing the RealTimeQueries component.
This commit aims to provide unifed api to avoid duplicated code. It can also be used as a reference when we want to close the gap. 
**Applications reimplementation :**
- cozy-settings : [SettingsRealTimeQueries](https://github.com/cozy/cozy-settings/blob/master/src/components/SettingsRealTimeQueries.jsx)
- cozy-drive : [FilesRealTimeQueries](https://github.com/cozy/cozy-drive/blob/master/src/components/FilesRealTimeQueries.jsx)
**Note …
> feat: Apply data enhancement to realtime results for specific doctypes

- docs/api/cozy-stack-client.md
- packages/cozy-client/src/RealTimeQueries.jsx
- packages/cozy-stack-client/src/AppCollection.js
- packages/cozy-stack-client/src/AppsRegistryCollection.js
- packages/cozy-stack-client/src/ContactsCollection.js
- packages/cozy-stack-client/src/DocumentCollection.js
- packages/cozy-stack-client/src/FileCollection.js
- packages/cozy-stack-client/src/JobCollection.js
- packages/cozy-stack-client/src/KonnectorCollection.js
- packages/cozy-stack-client/src/NextcloudFilesCollection.js
- packages/cozy-stack-client/src/NotesCollection.js
- packages/cozy-stack-client/src/OAuthClientsCollection.js
- packages/cozy-stack-client/src/PermissionCollection.js
- packages/cozy-stack-client/src/SettingsCollection.js
- packages/cozy-stack-client/src/SharingCollection.js
- packages/cozy-stack-client/src/ShortcutsCollection.js
- packages/cozy-stack-client/src/TriggerCollection.js
- packages/cozy-stack-client/src/index.js
- packages/cozy-stack-client/src/normalize.js
This PR moves document properties from the 'attributes' sub-object to the document
root to avoid data inconsistencies between JSON and CouchDB formats.
This ensures compatibility with CouchDB documents, where properties are
at the root level. By spreading attributes directly to the root in the
JSON document, the structure now aligns with CouchDB's format, allowing
seamless interaction across different APIs, including real-time updates
and the data API. This prevents potential issues caused by schema
mismatches in data retrieval and synchronization processes.
> [VO-1125] feat: Spread attributes from JSON:API at document root

- docs/api/cozy-pouch-link/classes/PouchLink.md
- packages/cozy-pouch-link/src/CozyPouchLink.js
- packages/cozy-pouch-link/src/types.js
- packages/cozy-pouch-link/types/CozyPouchLink.d.ts
- packages/cozy-pouch-link/types/types.d.ts
This is useful to get the changes and the db info from a client using a PouchLink
> feat: Add PouchDB API endpoints

- packages/cozy-pouch-link/src/remote.js
- packages/cozy-pouch-link/src/remote.spec.js
When using PouchLink in a web environment, we need to pass the cookies through the fetch method in order to authenticate to the stack. Note we didn't have the issue before we were using PouchLink in a mobile environment, with OAuth authentication.
For more insights, see
```
https://reqbin.com/code/javascript/lcpj87js/
javascript-fetch-with-credentials
```
> fix: Allow remote request on web environment

- docs/api/cozy-pouch-link/classes/PouchLink.md
- packages/cozy-pouch-link/src/CozyPouchLink.js
- packages/cozy-pouch-link/src/types.js
- packages/cozy-pouch-link/types/CozyPouchLink.d.ts
- packages/cozy-pouch-link/types/types.d.ts
When a replication was enabled, we used to automatically start a loop
replication process, on a fixed interval.
However, we might want a one-shot replication that could be manually
triggered through a `pouchLink.startReplication`
> feat: Allow one-shot replication 

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/mangoIndex.js
- packages/cozy-stack-client/src/mangoIndex.spec.js
When CouchDB creates an index, it orders the partial filters alphabetically. This leads to errors in the comparison to find the existing partial filters. To correct the problem, we have improved the function to make our partial filters explicit so that it sorts in the same way as CouchDB.
> [VO-1153] fix(mango): Order alphabetically object inside arrays based on 1st key

- docs/api/cozy-client/classes/CozyClient.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/types/CozyClient.d.ts
THis is useful to be able to manually set links after client instanciation.
Example scenario:
- A client is init
- We query the stack to know if the current session is on a trusted device
- If it is the case, we set a pouchLink
> [PRD-600] feat: Add setLinks method

- docs/api/cozy-stack-client.md
- package.json
- packages/cozy-stack-client/src/FileCollection.js
need to deploy stack before merging...
> feat(FileCollection): Add getAll(), and so Q(`io.cozy.files`).getByIds

- packages/cozy-client/src/types.js
- packages/cozy-client/types/types.d.ts
By typing inside cozy-drive, I found out that `io.cozy.files` have extra fields inside their `cozyMetadata`. Their are documented inside cozy-doctype but not inside cozy-client ([doc](https://github.com/cozy/cozy-doctypes/blob/master/docs/io.cozy.files.md#cozymetadata)). This commit aims to correct this for future use
> fix: Add missing fields on CozyMetadata for io.cozy.files

- .github/workflows/ci-cd.yml
- packages/cozy-client/package.json
- yarn.lock
Lerna has a two-step process. After checking the master branch and publishing the packages. It publishes a commit with the tag of the new version and the modification of the packages.json for use in the next merge. This new commit would trigger the CI again, but this modification avoids this
**Note:** The second commit is also to test the CI working properly
> chore: Avoid running the CI twice after publish

- docs/api/cozy-client/classes/CozyClient.md
- docs/offline/updateDoc.md
- packages/cozy-client/src/CozyClient.js
We want to optimize the flagship app's startup time and this method is in the critical path
By parallelizing those two queries we expect to redue this method's execution duration
> feat: Parallelize `loadInstanceOptionsFromStacks` queries

- packages/cozy-stack-client/src/TriggerCollection.js
- packages/cozy-stack-client/src/TriggerCollection.spec.js
One might want to avoid querying the `/jobs/triggers` route and stick to the `/data` route, to avoid extra work from the stack, that can be costful.
We were using the existence of `worker` and `type` keys in selector, but a partialFilter existence should also force the use of the `/data` route.
> feat: Do not query /jobs/triggers with a partialFilter

- package.json
Since we updated Lerna to V8, the task-runner implementation has been changed from `p-map/p-queue` to `nx`
The side effect is that we now have a very light output when running `yarn watch` with no feedback when the build fails
To fix this, we can add the `--stream` argument in addition to the `--parallel` one in order to get the build logs back
The Lerna's `--stream` argument is equivalent to the Nx's `--output-style=stream` one
More info:
- https://github.com/lerna/lerna/releases/tag/v6.0.0
- https://nx.dev/nx-api/nx/documents/run-many#outputstyle
- https://fig.io/manual/lerna/run
> chore: Improve `watch` script to output result

- docs/api/cozy-client/classes/CozyClient.md
- docs/api/cozy-client/classes/CozyLink.md
- docs/api/cozy-client/classes/StackLink.md
- docs/api/cozy-client/classes/WebFlagshipLink.md
- docs/api/cozy-pouch-link/classes/PouchLink.md
- docs/link-authoring.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/CozyClient.spec.js
- packages/cozy-client/src/CozyLink.js
- packages/cozy-client/src/CozyLink.spec.js
- packages/cozy-client/src/StackLink.js
- packages/cozy-client/src/WebFlagshipLink.js
- packages/cozy-client/src/types.js
- packages/cozy-client/types/CozyClient.d.ts
- packages/cozy-client/types/CozyLink.d.ts
- packages/cozy-client/types/StackLink.d.ts
- packages/cozy-client/types/types.d.ts
- packages/cozy-pouch-link/src/CozyPouchLink.js
- packages/cozy-pouch-link/src/CozyPouchLink.spec.js
- packages/cozy-pouch-link/types/CozyPouchLink.d.ts
In previous commits we implemented supports for offline mode through CozyPouchLink and FlagshipLink
Since this feature, the StackLink is able to check for internet reachability by using the `isOnline()` method. When no internet is detected, then the request is forwarded to the next link (i.e. the CozyPouchLink)
In some scenario we may want to prevent that behavior. This is the case when we are working on a feature that cannot work without internet access, or when the query's result is expected to contain data that is injected by the cozy-stack (and so that is not available in the local Pouch database)
To make this possible we introduce the `forceStack` parameter that can be set in the query options
When set to `true` then the StackLink will not attempt to forward the request when offline, …
> feat: Allow to enforce Stack link on request chain

- packages/cozy-client/src/models/paper.js
Following the date-fns update on cozy-ui and the apps, the date format is changing.
> fix(models/paper): Change date format

- docs/api/cozy-client/modules/models.konnectorFolder.md
- packages/cozy-client/src/models/konnectorFolder.js
- packages/cozy-client/src/models/konnectorFolder.spec.js
- packages/cozy-client/types/models/konnectorFolder.d.ts
When the account folder already exist and has konnector reference and
not the konnector folder
> fix(konnectors): Avoid creating multiple konnector folders (SCR-896)

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/SharingCollection.js
- packages/cozy-stack-client/src/SharingCollection.spec.js
This option allows you to directly redirect users to their Cozy with the share's Shortcut, without using OAuth.
See cozy/cozy-stack#4503
> feat(SharingColl): Add `shortcut` option to getDiscoveryLink

- docs/api/cozy-client/modules/models.sharing.md
- docs/api/cozy-stack-client.md
- packages/cozy-client/src/models/sharing.js
- packages/cozy-client/src/models/sharing.spec.js
- packages/cozy-client/types/models/sharing.d.ts
- packages/cozy-stack-client/src/PermissionCollection.js
- packages/cozy-stack-client/src/PermissionCollection.spec.js
Overall improvement in link sharing
Link with : https://github.com/cozy/cozy-stack/pull/4506
> feat(permissionColl & models/sharing): Improve sharing link feature

- docs/api/cozy-client/classes/CozyClient.md
- docs/api/cozy-pouch-link/classes/PouchLink.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/types/CozyClient.d.ts
- packages/cozy-pouch-link/src/CozyPouchLink.js
The `onLogin` for a link is async, so it should be awaited to ensure
that everything is initialized before we actually use the link
> fix: Links' onLogin should be awaited

- docs/api/cozy-pouch-link/classes/PouchLink.md
- packages/cozy-pouch-link/src/CozyPouchLink.js
- packages/cozy-pouch-link/src/errors.js
- packages/cozy-pouch-link/src/utils.js
- packages/cozy-pouch-link/types/CozyPouchLink.d.ts
- packages/cozy-pouch-link/types/errors.d.ts
- packages/cozy-stack-client/src/CozyStackClient.js
- packages/cozy-stack-client/src/CozyStackClient.spec.js
This includes:
- Proper refreshToken detection in PouchLink
- Proper handling of the refreshToken in worker env
> [DAT-75] Correctly handle refreshToken for dataproxy replication

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/FileCollection.js
- packages/cozy-stack-client/src/FileCollection.spec.js
- packages/cozy-stack-client/src/__snapshots__/FileCollection.spec.js.snap
Some clients, like Cozy Desktop, do their own file name sanitization
and don't expect `cozy-client` to do it for them. In fact, this
sanitization would lead to issues down the road.
To prevent these, we add a `sanitizeName` option to `FileCollection`'s
methods to disable `cozy-client`'s sanitization.
The option's value will be `true` by default so other clients don't
have anything to do.
> fix: Allow disabling file name sanitization

- packages/cozy-stack-client/src/CozyStackClient.js
- packages/cozy-stack-client/src/CozyStackClient.spec.js
BREAKING CHANGE: The `reason` attribute of non-JSON fetch errors is no
longer a string composed of the server response status and status
text.
We used to have 2 different kinds of values for the `reason` attribute
of `FetchError` built in `CozyStackClient`:
- a string representation of the response body sent by the server (which may contain details about what when wrong, especially for 400 status responses) for JSON requests
- a string composed of the server response status and status text for non-JSON requests
In the non-JSON request situation, we lose information by not using
the server response body as the reason of the `FetchError` which
prevents users of `cozy-client` from reacting appropriately when
receiving such an error to their request.
Therefore we homogenize our `FetchError` …
> fix: Always use response body as FetchError reason

- docs/api/cozy-pouch-link/classes/PouchLink.md
- packages/cozy-pouch-link/src/CozyPouchLink.js
- packages/cozy-pouch-link/src/PouchManager.js
- packages/cozy-pouch-link/types/CozyPouchLink.d.ts
- packages/cozy-pouch-link/types/PouchManager.d.ts
If an app wants to trigger replication at different event handling, it
is nice to have some control on it, and prevent multiple parallel
replication processes.
Thus, we introduce a `waitForReplications` param, which is set to true
by default.
Thanks to this, we wait for the previous replication process to complete
before running the new one
> feat: Ensure previous replication are done 

- docs/api/cozy-client/README.md
- packages/cozy-client/src/associations/HasManyFiles.js
- packages/cozy-client/src/store/documents.js
- packages/cozy-client/src/store/queries.js
- packages/cozy-client/src/store/queries.spec.js
- packages/cozy-client/src/store/stateHelpers.js
- packages/cozy-client/types/store/documents.d.ts
- packages/cozy-client/types/store/stateHelpers.d.ts
See https://github.com/cozy/cozy-client/issues/1591
For a query returning 352 docs by ids from a store containing 25K docs, we measure 49ms, against +1000ms before, thanks to k * O(1) evaluation vs O(n)
This is notably useful for search use-case: all the docs are loaded in store, and we need each query to be as fast as possible
> feat: Improve store query performance for id queries

- docs/api/cozy-stack-client.md
- packages/cozy-stack-client/src/FileCollection.js
- packages/cozy-stack-client/src/FileCollection.spec.js
- packages/cozy-stack-client/src/__snapshots__/FileCollection.spec.js.snap
Some `cozy-stack` `io.cozy.files` routes will look for a `If-Match`
header and compare its value with the modified document's revision and
reject the request if they don't match.
This header was set in a few of `FileCollection`'s methods via an
`ifMatch` parameter but not all that make requests supporting this
mechanism.
We've made sure to add the mechanism to all the methods that should
send this header if necessary.
> feat: Add ifMatch option to FileCollection methods

- packages/cozy-client/package.json
- packages/cozy-client/src/store/documents.js
- packages/cozy-client/src/store/documents.spec.js
- packages/cozy-client/types/store/documents.d.ts
- yarn.lock
We used to create a new reference on the `documents` state for any query.
This is problematic because we do a referential comparison on the updated `documents` state to evaluate if there is any update on it, resulting on all store's queries re-evaluation.
So, basically, we were doing a full queries re-evaluation for *any* query execution, even if the same query is run several time with no change.
This is particularly problematic when there are a lot of queries and/or
queries with many documents returned, as their re-evaluation will be
costful. Moreover, the document merging itself is costful.
The comparison between old and new docs is crucial for performances, so
we did some performances measures: we took a worst case where we fill
the store with 25K docs with a query and run again the …
> fix: Correctly handle document's store updates

- docs/api/cozy-client/classes/CozyClient.md
- docs/api/cozy-pouch-link/classes/PouchLink.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/storage.js
- packages/cozy-client/src/storage.spec.js
- packages/cozy-client/types/storage.d.ts
- packages/cozy-pouch-link/src/CozyPouchLink.js
- packages/cozy-pouch-link/src/jsonapi.js
- packages/cozy-pouch-link/src/jsonapi.spec.js
- packages/cozy-pouch-link/types/CozyPouchLink.d.ts
- packages/cozy-pouch-link/types/jsonapi.d.ts
This includes improvements to improve queries performances, after we noticed a high cozy-client overhead on large queries.
The details and performances improvements can be found in dedicated commits. 
For an overall performance insight, we measured a big query retrieving 25K documents, on a Redmi Note 10 mobile.
The query is the following: `await client.query(Q('io.cozy.files').limitBy(null))`
The results are : 
Before: 
- 2328ms to read pouch data 
**- Total: 5303ms**
- **43%** of total time is spent on database side
After:
- 2749ms to read pouch data
**- Total: 3156ms**
- **87%** of total time is spent on database side
Thus, before, 57% of the total query time was spent *outside* of the database. Now it is only 13% :rocket:
> Improve performances on queries

- docs/api/cozy-client/modules/models.applications.md
- packages/cozy-client/src/models/applications.js
- packages/cozy-client/src/models/applications.spec.js
- packages/cozy-client/types/models/applications.d.ts
To start, will be used on cozy-home and cozy-bar with flag `apps.sort` who can be set for example to `["chat", "drive", "mail", "passwords", "notes", "contacts"]`.
It will allow to display apps with this order, and other apps will come after.
> Add helpers to sort apps

- docs/api/cozy-client/modules/models.applications.md
- packages/cozy-client/src/models/applications.js
- packages/cozy-client/src/models/applications.spec.js
We do not want to display "Twake Drive" but just "Drive" like previously with "Cozy Drive". I keep "Cozy" exception for the moment because we may have both in our codebase for a while.
> fix: Ignore "Twake" prefix in getAppDisplayName

- packages/cozy-client/package.json
- yarn.lock
react-native 0.65.x is compatible w/ react 17 only. Because our other libs required react 16, let's downgrade react-native so that every libs require react 16.
> fix: Downgrade react-native 0.65.x to 0.63.x

- docs/api/cozy-client/modules/models.doctypes.md
- docs/api/cozy-client/modules/models.md
- packages/cozy-client/src/models/doctypes/index.js
- packages/cozy-client/src/models/index.js
- packages/cozy-client/types/models/doctypes/index.d.ts
- packages/cozy-client/types/models/index.d.ts
Introduced a new `doctypes` model with a function to fetch all doctypes
from the current Cozy instance.
> feat: Add doctypes model and fetch function

- docs/api/cozy-client/README.md
- docs/api/cozy-client/classes/CozyClient.md
- docs/api/cozy-pouch-link/classes/PouchLink.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/src/links/StackLink.js
- packages/cozy-client/src/queries/dsl.js
- packages/cozy-client/src/types.js
- packages/cozy-client/types/CozyClient.d.ts
- packages/cozy-client/types/queries/dsl.d.ts
- packages/cozy-client/types/types.d.ts
- packages/cozy-pouch-link/src/CozyPouchLink.js
- packages/cozy-pouch-link/src/CozyPouchLink.spec.js
- packages/cozy-pouch-link/types/CozyPouchLink.d.ts
We used to support mutliple updates but not create nor delete.  Thus, we now introduce the `createAll` and `destroyAll` API methods, to respectively bulk create and delete a batch of documents.  `updateAll`is also introduced, which is a simple wrapper for `saveAll`, just like `createAll`.
:warning: The `createAll` is currently not supported for stackClient links, but works for pouchLink. 
Adding the associated dsl mutations is also useful for apps that want to handle themselves store actions. For instance, Drive would be able to dispatch a single mutation action for multiple updates, typically after the deletion of a directory. This would improve performances, by avoiding to make a costful dispatch per document.
> feat: Support multiple create and delete

- docs/api/cozy-client/classes/CozyClient.md
- packages/cozy-client/src/CozyClient.js
- packages/cozy-client/types/CozyClient.d.ts
To create relationships on a document, one can use the dedicated methods after document hydratation.
This is notably used when doing `client.save` if the `references` argument is provided.
However, we changed the hydratation behaviour on the 60.0.0 release: the documents are no longer hydrated if no relationship is found. This breaks creation, so we add an option to force the hydratation for such case.
> fix: Reference creation through hydratation

- docs/api/cozy-client/classes/DataProxyLink.md
- packages/cozy-client/src/links/DataProxyLink.js
- packages/cozy-client/src/links/DataProxyLink.spec.js
- packages/cozy-client/types/links/DataProxyLink.d.ts
The DataProxy needs some time to be initialized and answer requests. However, apps may ask for query execution before it is ready ; to prevent this, we had an init mechanism made in the `DataProxyProvider` to ensure the children are rendered only when the DataProxy is ready.
It works, but if something went wrong, nothing is displayed, which is confusing and hard to debug for the developer.
So, we change this by always rendering the children on the DataProxy side, and implement a queue on the `DataProxyLink` to bufferise requests, waiting for the dataproxy to be ready.
Once it is ready, all the requests in the queue are executed, in FIFO fashion.
> feat: Queue DataProxy requests when it is not ready

- docs/api/cozy-pouch-link/classes/PouchLink.md
- packages/cozy-pouch-link/src/CozyPouchLink.js
When `startReplicationDebounce` is called once, the replication will be executed immediatly. And then, all subsequent calls made in the debounce interval will be delayed.
It is useful for situations where a single action triggering a replication, e.g. a realtime update, should not be delayed to immediatly benefit from local data.
See https://lodash.com/docs/4.17.15#debounce for `leading` option behaviour
> feat: Make `startReplicationDebounce` run immediatly at first call

- packages/cozy-client/package.json
- yarn.lock
Update date-fns and use ^ operator to avoid  duplicate packages.
> feat: Update date-fns

- docs/api/cozy-client/interfaces/models.file.FileUploadOptions.md
- docs/api/cozy-client/modules/models.file.md
- packages/cozy-client/src/models/file.js
- packages/cozy-client/types/models/file.d.ts
Update `getFullpath` function to accept `driveId` to be used in shared drive.
> feat: Update get full path to use in shared drive :sparkles:

- packages/cozy-pouch-link/src/PouchManager.js
- packages/cozy-pouch-link/src/localStorage.js
- packages/cozy-pouch-link/types/localStorage.d.ts
This is useful at cleanup time for old browsers that do not support the `indexeddb.databases()` function.
> feat: Store PouchDB databases locally

- packages/cozy-pouch-link/src/jsonapi.js
- packages/cozy-pouch-link/src/jsonapi.spec.js
File paths are not stored in PouchDB. Therefore, we keep a Map of paths in-memory, for fast retrieval.
This PR adds 2 fixes: 
- The Map was not properly initialized, because we failed to correctly retrieve the parent path from database
- Updates on file paths were not properly handled
Note the paths were still properly displayed to the user at search time, because the paths handling was originally done on search side: https://github.com/cozy/cozy-libs/blob/master/packages/cozy-dataproxy-lib/src/search/helpers/filePaths.ts
But this is better to mutualize the logic here, so both search and pouch queries can benefit from it. So we'll eventually remove the paths handling on dataproxy search.
> Fix file paths handling for Pouch
